### ISSUE TITLE
Helm Install - API server fails to accpet a testcatalog

### ISSUE THREAD

**Issue by Jimbo4794** [galasa-dev/projectmanagement#1005]
The API server cannot push test catalogs to it. The data PVC doesn’t have a init container giving permissions leading to 500 errors and permission denied errors when pushing test catalogs:
From API server:
```
[ERROR] Exception while processing request to /testcatalog
java.io.IOException: Problem processing the test catalog request
	at dev.galasa.framework.api.testcatlog.internal.Testcatalogs.doGet(Testcatalogs.java:105)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:618)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:725)
	at org.apache.felix.http.base.internal.handler.ServletHandler.handle(ServletHandler.java:123)
	at org.apache.felix.http.base.internal.dispatch.InvocationChain.doFilter(InvocationChain.java:86)
	at org.apache.felix.http.base.internal.dispatch.Dispatcher$1.doFilter(Dispatcher.java:146)
	at org.apache.felix.http.base.internal.whiteboard.WhiteboardManager.invokePreprocessors(WhiteboardManager.java:988)
	at org.apache.felix.http.base.internal.dispatch.Dispatcher.dispatch(Dispatcher.java:91)
	at org.apache.felix.http.base.internal.dispatch.DispatcherServlet.service(DispatcherServlet.java:49)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:725)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:852)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:544)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1581)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1307)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:482)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1549)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1204)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:221)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at org.eclipse.jetty.server.Server.handle(Server.java:494)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:374)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:268)
	at [org.eclipse.jetty.io](http://org.eclipse.jetty.io/).AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
	at [org.eclipse.jetty.io](http://org.eclipse.jetty.io/).FillInterest.fillable(FillInterest.java:103)
	at [org.eclipse.jetty.io](http://org.eclipse.jetty.io/).ChannelEndPoint$2.run(ChannelEndPoint.java:117)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:336)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:313)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:171)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:129)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:367)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:782)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:918)
	at java.lang.Thread.run(Thread.java:750)
Caused by: java.nio.file.AccessDeniedException: /galasa/testcatalog/cache.json
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:84)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:214)
	at java.nio.file.spi.FileSystemProvider.newOutputStream(FileSystemProvider.java:434)
	at java.nio.file.Files.newOutputStream(Files.java:216)
	at java.nio.file.Files.write(Files.java:3292)
	at dev.galasa.framework.api.testcatlog.internal.Testcatalogs.rebuildCacheFile(Testcatalogs.java:133)
	at dev.galasa.framework.api.testcatlog.internal.Testcatalogs.doGet(Testcatalogs.java:87)
	... 37 more
```
Error from CLI:
```
…
[DEBUG] -- end configuration --
[ERROR] Deploy to Test Catalog Store failed:-
[ERROR] 500 - Server Error
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for dev.galasa.examples.tests.parent 0.0.1:
[INFO]
[INFO] dev.galasa.examples.tests.parent ................... SUCCESS [ 2.149 s]
[INFO] dev.galasa.examples.tests .......................... SUCCESS [ 8.419 s]
[INFO] dev.galasa.examples.obr ............................ FAILURE [ 3.960 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 15.887 s
[INFO] Finished at: 2022-05-20T16:06:03+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal dev.galasa:galasa-maven-plugin:0.11.0:deploytestcat (default-cli) on project dev.galasa.examples.obr: Problem merging the test catalog: Deploy to Test Catalog Store failed -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal dev.galasa:galasa-maven-plugin:0.11.0:deploytestcat (default-cli) on project dev.galasa.examples.obr: Problem merging the test catalog
```

**Comment by Michael-Baylis** [comment]
replicated

**Comment by Jimbo4794** [comment]
Yeah all it should need is an init container to give file permissions. Have to do the same in the k8s operator

**Comment by Michael-Baylis** [comment]
New helm charts deployed as 0.0.3.   

Needed an init container,  but also need to set runAsUser
