### ISSUE TITLE
Move the minimum support version of Java to 11

### ISSUE THREAD

**Issue by Jimbo4794** [galasa-dev/projectmanagement#1027]
As a resolution for JavaEE included packages issue #1026 and for future security concerns, we are looking to make the lowest supported version of Java to be 11

- [x] Change framework target to 11
- [x] Change the build image to be based on java 11
- [ ] Change the OBR embedded to include java 11
- [ ] Confirm Testing Junits on Java 11

**Comment by Jimbo4794** [comment]
Also need to remove all the Java 8 Tests

**Comment by hobbit1983** [comment]
java8 tests gone

**Comment by Jimbo4794** [comment]
PR in for build image to be moved to Java 11. Changes to the cacerts paths were required for the Java 11 JDK

**Comment by Jimbo4794** [comment]
Changed framework to compile at Java 11. PR failing until build utils approved

**Comment by hobbit1983** [comment]
Running a test on 0.24.0 using Java 8 the following error is written:
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.UnsupportedClassVersionError: dev/galasa/boot/Launcher has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:473)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:355)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:601)


As expected
