### ISSUE TITLE
Error on provision discard when selenium manager finishes

### ISSUE THREAD

**Issue by AaronJhaj** [galasa-dev/projectmanagement#1081]
When trying to use selenium manager when using a local gecko driver, selenium manager fails when freeing slots and discarding after test has ran. 

```
18/08/2022 14:58:41.848 INFO  d.g.f.TestRunner - Starting Provision Stop phase
18/08/2022 14:58:41.848 DEBUG d.g.d.i.DockerContainerImpl - Deleting Docker container 'simbank-webapp'
18/08/2022 14:58:42.019 INFO  d.g.d.i.DockerContainerImpl - Deleted Docker container 'simbank-webapp'
18/08/2022 14:58:42.022 INFO  d.g.d.i.DockerEnvironment - Discarding slot: SLOT_U188_0. on the Docker engine: LOCAL
18/08/2022 14:58:42.022 INFO  d.g.f.TestRunner - Starting Provision Discard phase
18/08/2022 14:58:42.022 FATAL d.g.f.TestRunner - Error within test runner
java.lang.NumberFormatException: null
	at java.lang.Integer.parseInt(Integer.java:614) ~[?:?]
	at java.lang.Integer.valueOf(Integer.java:983) ~[?:?]
	at dev.galasa.selenium.internal.SeleniumEnvironment.freeSlots(SeleniumEnvironment.java:221) ~[?:?]
	at dev.galasa.selenium.internal.SeleniumEnvironment.discard(SeleniumEnvironment.java:205) ~[?:?]
	at dev.galasa.selenium.internal.SeleniumManagerImpl.provisionDiscard(SeleniumManagerImpl.java:173) ~[?:?]
	at dev.galasa.framework.TestRunManagers.provisionDiscard(TestRunManagers.java:516) ~[-1660831110436:?]
	at dev.galasa.framework.TestRunner.discardEnvironment(TestRunner.java:496) ~[-1660831110436:?]
	at dev.galasa.framework.TestRunner.createEnvironment(TestRunner.java:485) ~[-1660831110436:?]
	at dev.galasa.framework.TestRunner.generateEnvironment(TestRunner.java:453) ~[-1660831110436:?]
	at dev.galasa.framework.TestRunner.runTest(TestRunner.java:371) [-1660831110436:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at dev.galasa.boot.felix.FelixFramework.runTest(FelixFramework.java:236) [galasa-boot.jar:?]
	at dev.galasa.boot.Launcher.launch(Launcher.java:166) [galasa-boot.jar:?]
	at dev.galasa.boot.Launcher.main(Launcher.java:120) [galasa-boot.jar:?]
```

**Comment by hobbit1983** [comment]
@AaronJhaj I've reviewed your code and asked for a simple change - thanks for getting stuck in to fix it
