### ISSUE TITLE
SSL_TLSv2 SSLContext not available : can't use zOSMF or RSE

### ISSUE THREAD

**Issue by jasonrhughes** [galasa-dev/projectmanagement#1247]
Galasa 0.24.0 plugins installed
Eclipse 2022-06 (also 2019-09)
java version "11.0.16.1" 2022-08-12
IBM Semeru Runtime Certified Edition 11.0.16.1 (build 11.0.16.1+1)

Whenever an attempt is made to use **IZosFileHandler** the test fails because it can't get a z/OSMF instance (or RSE server, as I've tried that too), and that's because 

`Caused by: java.security.NoSuchAlgorithmException: SSL_TLSv2 SSLContext not available`  (example of full output below).

This used to work fine, but that was Galasa 0.18.0 with Java8. 

The initial error points to code in dev.galasa.http.internal.HttpClientImpl where IHttpClient is checking to see if the Java vendor is IBM or not. If it is, it sets the SSLContext to be "SSL_TLSv2". If not IBM Java, it sets "TLSv1.2". The problem is that SSL_TLSv2 is not available as an SSLContext in IBM Java11 (code run to verify this).

As a test I have temporarily pointed the runtime JRE at a newly installed openjdk14. This works as expected, so the problem seems to stem from an incompatibility between HttpClientImpl and IBM's Java 11 (we can only use IBM J11 or J17 - and Galasa is not compatible with J17).

**Comment by jasonrhughes** [comment]
I've blanked out the z/OS image name below; tried two different systems with same results.

```
----------------------- ****************************************************************************************************
----------------------- *** Failed - Test method FileFromResources#simpleLogonTest,type=Test
----------------------- ****************************************************************************************************
dev.galasa.zosfile.ZosUNIXFileException: dev.galasa.zosmf.ZosmfManagerException: Unable to get zOSMF servers for image "...."
	at dev.galasa.zosfile.zosmf.manager.internal.ZosmfZosUNIXFileImpl.<init>(ZosmfZosUNIXFileImpl.java:139)
	at dev.galasa.zosfile.zosmf.manager.internal.ZosmfZosFileHandlerImpl.newUNIXFile(ZosmfZosFileHandlerImpl.java:71)
	at FileFromResources.simpleLogonTest(FileFromResources.java:97)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at dev.galasa.framework.GenericMethodWrapper.invoke(GenericMethodWrapper.java:82)
	at dev.galasa.framework.TestMethodWrapper.invoke(TestMethodWrapper.java:61)
	at dev.galasa.framework.TestClassWrapper.runTestMethods(TestClassWrapper.java:214)
	at dev.galasa.framework.TestRunner.runTestClassWrapper(TestRunner.java:551)
	at dev.galasa.framework.TestRunner.runEnvironment(TestRunner.java:523)
	at dev.galasa.framework.TestRunner.createEnvironment(TestRunner.java:483)
	at dev.galasa.framework.TestRunner.generateEnvironment(TestRunner.java:453)
	at dev.galasa.framework.TestRunner.runTest(TestRunner.java:371)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at dev.galasa.boot.felix.FelixFramework.runTest(FelixFramework.java:236)
	at dev.galasa.boot.Launcher.launch(Launcher.java:166)
	at dev.galasa.boot.Launcher.main(Launcher.java:120)
Caused by: dev.galasa.zosmf.ZosmfManagerException: Unable to get zOSMF servers for image "...."
	at dev.galasa.zosmf.internal.ZosmfManagerImpl.getZosmfs(ZosmfManagerImpl.java:191)
	at dev.galasa.zosmf.internal.ZosmfManagerImpl.newZosmfRestApiProcessor(ZosmfManagerImpl.java:208)
	at dev.galasa.zosfile.zosmf.manager.internal.ZosmfZosUNIXFileImpl.<init>(ZosmfZosUNIXFileImpl.java:135)
	... 21 more
Caused by: dev.galasa.zosmf.ZosmfException: Unable to create HTTP Client
	at dev.galasa.zosmf.internal.ZosmfImpl.initialize(ZosmfImpl.java:322)
	at dev.galasa.zosmf.internal.ZosmfImpl.<init>(ZosmfImpl.java:79)
	at dev.galasa.zosmf.internal.ZosmfManagerImpl.newZosmf(ZosmfManagerImpl.java:159)
	at dev.galasa.zosmf.internal.ZosmfManagerImpl.getZosmfs(ZosmfManagerImpl.java:185)
	... 23 more
Caused by: dev.galasa.http.HttpClientException: Error attempting to create SSL context
	at dev.galasa.http.internal.HttpClientImpl.setTrustingSSLContext(HttpClientImpl.java:372)
	at dev.galasa.zosmf.internal.ZosmfImpl.initialize(ZosmfImpl.java:318)
	... 26 more
Caused by: java.security.NoSuchAlgorithmException: SSL_TLSv2 SSLContext not available
	at java.base/sun.security.jca.GetInstance.getInstance(GetInstance.java:159)
	at java.base/javax.net.ssl.SSLContext.getInstance(SSLContext.java:168)
	at dev.galasa.http.internal.HttpClientImpl.setTrustingSSLContext(HttpClientImpl.java:366)
	... 27 more
```

**Comment by techcobweb** [comment]
This 'could' (but probably isn't) related ? https://github.com/galasa-dev/projectmanagement/issues/1246

**Comment by jasonrhughes** [comment]
SSL_TLSv2 is a valid context in IBM J8 but is not in IBM J11. We get the problem because HttpClientImpl still expects it to be valid and wants to use it (only) if it's IBM Java. 
I've just checked and openjdk14 also doesn't have SSL_TLSv2 as an available context, so it doesn't appear to be an omission specifically in IBM's Java. It seems the `if (ibmJdk)...` statements in HttpClientImpl need to be updated.

**Comment by techcobweb** [comment]
We should try with a few JDKs and try with logging enabled.
This might be something @KirbyKatcher could look at ? Lets discuss with him when he's back.

**Comment by techcobweb** [comment]
Added to the sprint as thsi is what savvas is working on.

**Comment by KirbyKatcher** [comment]
Having investigated the issue and replicated it I have found the following piece of documentation on IBM J11 that has raised an interesting point.
[https://www.ibm.com/docs/en/semeru-runtime-ce-z/11?topic=security-jsse-provider-differences](https://www.ibm.com/docs/en/semeru-runtime-ce-z/11?topic=security-jsse-provider-differences)
`Protocol aliases SSL_TLS and SSL_TLSv2 are no longer supported in this release.`
As these aliases are currently used by the HTMLClient in galasa it would suggest that we would need to move away from these aliases in order to use IBM J11.
I will make the code changes and test this.

**Comment by techcobweb** [comment]
Hi @KirbyKatcher . What's left to do on this item. Thought you'd submitted it for building. Did you get that far ?

**Comment by hobbit1983** [comment]
I think this is now merged @KirbyKatcher can this be closed?

**Comment by KirbyKatcher** [comment]
Changes merged into managers. Closing issue
