### ISSUE TITLE
Technical Debt: Unit test failures in 'extensions' component when building locally

### ISSUE THREAD

**Issue by techcobweb** [galasa-dev/projectmanagement#1250]
Doing a local build, there are unit test failures in the extensions component.

- Why weren't these unit test failures picked up by the build ?
  - They should stop the main/pr build in its tracks.

```
Starting process 'Gradle Test Executor 1'. Working directory: /Users/mcobbett/builds/galasa/code/external/galasa-dev/extensions/galasa-extensions-parent/dev.galasa.cps.etcd Command: /Library/Java/JavaVirtualMachines/ibm-semeru-certified-11.jdk/Contents/Home/bin/java -Dorg.gradle.native=false @/private/var/folders/3v/tn2_mqv93wz2vb8nx4vhmj1r0000gn/T/gradle-worker-classpath3718713807309437442txt -Xmx512m -Dfile.encoding=UTF-8 -Duser.country=GB -Duser.language=en -Duser.variant -ea worker.org.gradle.process.internal.worker.GradleWorkerMain 'Gradle Test Executor 1'
Successfully started process 'Gradle Test Executor 1'

test.force.codecoverage.ExceptionsTest > testCatchingException STANDARD_ERROR
    SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
    SLF4J: Defaulting to no-operation (NOP) logger implementation
    SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.

test.force.codecoverage.ExceptionsTest > testCatchingException FAILED
    java.lang.IllegalArgumentException: port out of range:-1
        at java.base/java.net.InetSocketAddress.checkPort(InetSocketAddress.java:143)
        at java.base/java.net.InetSocketAddress.<init>(InetSocketAddress.java:224)
        at io.etcd.jetcd.resolver.IPNameResolver.lambda$new$1(IPNameResolver.java:77)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
        at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:497)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:487)
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:239)
        at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
        at io.etcd.jetcd.resolver.IPNameResolver.<init>(IPNameResolver.java:83)
        at io.etcd.jetcd.resolver.IPResolverProvider.newNameResolver(IPResolverProvider.java:48)
        at io.grpc.NameResolverRegistry$NameResolverFactory.newNameResolver(NameResolverRegistry.java:154)
        at io.grpc.internal.ManagedChannelImpl.getNameResolver(ManagedChannelImpl.java:741)
        at io.grpc.internal.ManagedChannelImpl.getNameResolver(ManagedChannelImpl.java:773)
        at io.grpc.internal.ManagedChannelImpl.<init>(ManagedChannelImpl.java:653)
        at io.grpc.internal.ManagedChannelImplBuilder.build(ManagedChannelImplBuilder.java:634)
        at io.grpc.internal.AbstractManagedChannelImplBuilder.build(AbstractManagedChannelImplBuilder.java:264)
        at io.etcd.jetcd.ClientConnectionManager.getChannel(ClientConnectionManager.java:122)
        at io.etcd.jetcd.ClientConnectionManager.newStub(ClientConnectionManager.java:171)
        at io.etcd.jetcd.KVImpl.<init>(KVImpl.java:55)
        at io.etcd.jetcd.ClientImpl.lambda$new$0(ClientImpl.java:38)
        at io.etcd.jetcd.support.MemoizingClientSupplier.get(MemoizingClientSupplier.java:37)
        at io.etcd.jetcd.ClientImpl.getKVClient(ClientImpl.java:55)
        at dev.galasa.cps.etcd.internal.Etcd3ConfigurationPropertyStore.<init>(Etcd3ConfigurationPropertyStore.java:48)
        at test.force.codecoverage.ExceptionsTest.testCatchingException(ExceptionsTest.java:51)

test.force.codecoverage.Ectd3CpsTest > testRegistration FAILED
    java.lang.IllegalArgumentException: port out of range:-1
        at java.base/java.net.InetSocketAddress.checkPort(InetSocketAddress.java:143)
        at java.base/java.net.InetSocketAddress.<init>(InetSocketAddress.java:224)
        at io.etcd.jetcd.resolver.IPNameResolver.lambda$new$1(IPNameResolver.java:77)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)

Gradle Test Executor 1 finished executing tests.

> Task :dev.galasa.cps.etcd:test FAILED
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
        at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:497)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:487)
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:239)
        at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
        at io.etcd.jetcd.resolver.IPNameResolver.<init>(IPNameResolver.java:83)
        at io.etcd.jetcd.resolver.IPResolverProvider.newNameResolver(IPResolverProvider.java:48)
        at io.grpc.NameResolverRegistry$NameResolverFactory.newNameResolver(NameResolverRegistry.java:154)
        at io.grpc.internal.ManagedChannelImpl.getNameResolver(ManagedChannelImpl.java:741)
        at io.grpc.internal.ManagedChannelImpl.getNameResolver(ManagedChannelImpl.java:773)
        at io.grpc.internal.ManagedChannelImpl.<init>(ManagedChannelImpl.java:653)
        at io.grpc.internal.ManagedChannelImplBuilder.build(ManagedChannelImplBuilder.java:634)
        at io.grpc.internal.AbstractManagedChannelImplBuilder.build(AbstractManagedChannelImplBuilder.java:264)
        at io.etcd.jetcd.ClientConnectionManager.getChannel(ClientConnectionManager.java:122)
        at io.etcd.jetcd.ClientConnectionManager.newStub(ClientConnectionManager.java:171)
        at io.etcd.jetcd.KVImpl.<init>(KVImpl.java:55)
        at io.etcd.jetcd.ClientImpl.lambda$new$0(ClientImpl.java:38)
        at io.etcd.jetcd.support.MemoizingClientSupplier.get(MemoizingClientSupplier.java:37)
        at io.etcd.jetcd.ClientImpl.getKVClient(ClientImpl.java:55)
        at dev.galasa.cps.etcd.internal.Etcd3ConfigurationPropertyStore.<init>(Etcd3ConfigurationPropertyStore.java:48)
        at test.force.codecoverage.Ectd3CpsTest.<init>(Ectd3CpsTest.java:50)

test.force.codecoverage.Ectd3CpsTest > testRegistrationwithFile FAILED
    java.lang.IllegalArgumentException: port out of range:-1
        at java.base/java.net.InetSocketAddress.checkPort(InetSocketAddress.java:143)
        at java.base/java.net.InetSocketAddress.<init>(InetSocketAddress.java:224)
        at io.etcd.jetcd.resolver.IPNameResolver.lambda$new$1(IPNameResolver.java:77)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
        at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:497)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:487)
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:239)
        at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
        at io.etcd.jetcd.resolver.IPNameResolver.<init>(IPNameResolver.java:83)
        at io.etcd.jetcd.resolver.IPResolverProvider.newNameResolver(IPResolverProvider.java:48)
        at io.grpc.NameResolverRegistry$NameResolverFactory.newNameResolver(NameResolverRegistry.java:154)
        at io.grpc.internal.ManagedChannelImpl.getNameResolver(ManagedChannelImpl.java:741)
        at io.grpc.internal.ManagedChannelImpl.getNameResolver(ManagedChannelImpl.java:773)
        at io.grpc.internal.ManagedChannelImpl.<init>(ManagedChannelImpl.java:653)
        at io.grpc.internal.ManagedChannelImplBuilder.build(ManagedChannelImplBuilder.java:634)
        at io.grpc.internal.AbstractManagedChannelImplBuilder.build(AbstractManagedChannelImplBuilder.java:264)
        at io.etcd.jetcd.ClientConnectionManager.getChannel(ClientConnectionManager.java:122)
        at io.etcd.jetcd.ClientConnectionManager.newStub(ClientConnectionManager.java:171)
        at io.etcd.jetcd.KVImpl.<init>(KVImpl.java:55)
        at io.etcd.jetcd.ClientImpl.lambda$new$0(ClientImpl.java:38)
        at io.etcd.jetcd.support.MemoizingClientSupplier.get(MemoizingClientSupplier.java:37)
        at io.etcd.jetcd.ClientImpl.getKVClient(ClientImpl.java:55)
        at dev.galasa.cps.etcd.internal.Etcd3ConfigurationPropertyStore.<init>(Etcd3ConfigurationPropertyStore.java:48)
        at test.force.codecoverage.Ectd3CpsTest.<init>(Ectd3CpsTest.java:50)
Finished generating test XML results (0.025 secs) into: /Users/mcobbett/builds/galasa/code/external/galasa-dev/extensions/galasa-extensions-parent/dev.galasa.cps.etcd/build/test-results/test
Generating HTML test report...
Finished generating test html results (0.029 secs) into: /Users/mcobbett/builds/galasa/code/external/galasa-dev/extensions/galasa-extensions-parent/dev.galasa.cps.etcd/build/reports/tests/test
:dev.galasa.cps.etcd:test (Thread[Execution worker for ':' Thread 4,5,main]) completed. Took 8.074 secs.
```

**Comment by techcobweb** [comment]
These unit tests have currently been commented-out, so don't run even if gradle started invoking unit tests.
Part of this story is to get these tests going again, or decide that they are no longer needed.
