### ISSUE TITLE
Galasa unable to connect to a 3270 terminal using CICS TX on Cloud

### ISSUE THREAD

**Issue by hobbit1983** [galasa-dev/projectmanagement#1274]
## Describe the bug
When the Zos3270 terminal is connected to a 3270 terminal exposed by a docker container of CICS TX on Cloud, Galasa fails to connect the terminal.  However the test does not fail but continues to execute even though the terminal is in a disconnected state

## Steps to reproduce
1. Launch a CICS TX on Cloud Container (I used 10.1) with the command `docker run --env LICENSE=accept --publish 3270:3270 ibm-cics-tx-on-cloud:10.1.0.0 `, wait for the container to start, you can check that the container is ready by checking 127.0.0.1:3270 using a 3270 emulator - I used Host On Demand.  I used the following class: 
`@Test
public class TXCloudTest {
	
	@Zos3270Terminal(imageTag = "SIMBANK")
    public ITerminal        terminal;
	
	@Test
	public void TXIVP() {
		assertThat(terminal.retrieveScreen()).containsOnlyOnce("Available CICS Regions");
	}`
Alter the CPS properties to connect to the container.  The test will fail with the following:
`19/11/2022 20:32:43.663 INFO  d.g.z.i.Zos3270ManagerImpl - Generated a terminal for zOS Image tagged SIMBANK
19/11/2022 20:32:43.666 INFO  d.g.f.TestRunner - Starting Provision Build phase
19/11/2022 20:32:43.667 INFO  d.g.f.TestRunner - Starting Provision Start phase
19/11/2022 20:32:43.667 INFO  d.g.z.i.Zos3270ManagerImpl - Connecting zOS3270 Terminals
19/11/2022 20:32:43.677 ERROR d.g.z.i.c.NetworkThread - Problem with Network Thread
dev.galasa.zos3270.spi.NetworkException: logic error, nothing new to negotiate device type with
	at dev.galasa.zos3270.internal.comms.NetworkThread.requestTerminalType(NetworkThread.java:401) ~[jar:?]
	at dev.galasa.zos3270.internal.comms.NetworkThread.doIacSbTerminalTypeSend(NetworkThread.java:362) ~[jar:?]
	at dev.galasa.zos3270.internal.comms.NetworkThread.doIacSbTerminalType(NetworkThread.java:352) ~[jar:?]
	at dev.galasa.zos3270.internal.comms.NetworkThread.doIacSb(NetworkThread.java:259) ~[jar:?]
	at dev.galasa.zos3270.internal.comms.NetworkThread.doIac(NetworkThread.java:228) ~[jar:?]
	at dev.galasa.zos3270.internal.comms.NetworkThread.processMessage(NetworkThread.java:172) ~[jar:?]
	at dev.galasa.zos3270.internal.comms.NetworkThread.run(NetworkThread.java:141) [jar:?]
19/11/2022 20:32:43.725 INFO  d.g.z.i.Zos3270ManagerImpl - Failed to connect zOS 3270 Terminal to 127.0.0.1:3270`
 however the test method continues and the asserts eventually fail

## Expected behavior
The Zos3270Terminal should connect correctly

**Comment by hobbit1983** [comment]
I've had a dig through the code and my initial thoughts is that TX wants the client to connect to it as a generic 3270 terminal, we check for two different devices types before running out of types.  Would probably need to run under debug mode to see what devices the server is offering and then add that as a low priority device type into the 3270 manager

**Comment by techcobweb** [comment]
Or add more logging so we can see what device types are available to use in that situation I guess...
