### ISSUE TITLE
Update OpenStack password to fix failing Docker integration tests

### ISSUE THREAD

**Issue by jadecarino** [galasa-dev/projectmanagement#1317]
### Background/Problem

The Docker integration tests are failing with the following error:
```
05/01/2023 17:06:13.642 WARN  main dev.galasa.openstack.manager.internal.OpenstackHttpClient.connectToOpenstack - OpenStack is not available due to identity responding with HTTP/1.1 401 UNAUTHORIZED
05/01/2023 17:06:13.643 INFO  main dev.galasa.framework.TestRunner.generateEnvironment - Provision Generate failed
dev.galasa.framework.spi.FrameworkException: Problem in provision generate for manager dev.galasa.linux.internal.LinuxManagerImpl
	at dev.galasa.framework.TestRunManagers.provisionGenerate(TestRunManagers.java:478) ~[-1672938363883:?]
	at dev.galasa.framework.TestRunner.generateEnvironment(TestRunner.java:435) [-1672938363883:?]
	at dev.galasa.framework.TestRunner.runTest(TestRunner.java:368) [-1672938363883:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at dev.galasa.boot.felix.FelixFramework.runTest(FelixFramework.java:235) [boot.jar:?]
	at dev.galasa.boot.Launcher.launch(Launcher.java:168) [boot.jar:?]
	at dev.galasa.boot.Launcher.main(Launcher.java:122) [boot.jar:?]
Caused by: dev.galasa.linux.LinuxManagerException: Unable to provision a Linux image for tag DOCKER as no provisioners configured with suitable images
	at dev.galasa.linux.internal.LinuxManagerImpl.generateLinuxImage(LinuxManagerImpl.java:259) ~[?:?]
	at dev.galasa.linux.internal.LinuxManagerImpl.provisionGenerate(LinuxManagerImpl.java:203) ~[?:?]
	at dev.galasa.framework.TestRunManagers.provisionGenerate(TestRunManagers.java:473) ~[-1672938363883:?]
	... 9 more
dev.galasa.framework.spi.FrameworkException: Problem in provision generate for manager dev.galasa.linux.internal.LinuxManagerImpl
	at dev.galasa.framework.TestRunManagers.provisionGenerate(TestRunManagers.java:478) ~[-1672938363883:?]
	at dev.galasa.framework.TestRunner.generateEnvironment(TestRunner.java:435) [-1672938363883:?]
	at dev.galasa.framework.TestRunner.runTest(TestRunner.java:368) [-1672938363883:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at dev.galasa.boot.felix.FelixFramework.runTest(FelixFramework.java:235) [boot.jar:?]
	at dev.galasa.boot.Launcher.launch(Launcher.java:168) [boot.jar:?]
	at dev.galasa.boot.Launcher.main(Launcher.java:122) [boot.jar:?]
Caused by: dev.galasa.linux.LinuxManagerException: Unable to provision a Linux image for tag DOCKER as no provisioners configured with suitable images
	at dev.galasa.linux.internal.LinuxManagerImpl.generateLinuxImage(LinuxManagerImpl.java:259) ~[?:?]
	at dev.galasa.linux.internal.LinuxManagerImpl.provisionGenerate(LinuxManagerImpl.java:203) ~[?:?]
	at dev.galasa.framework.TestRunManagers.provisionGenerate(TestRunManagers.java:473) ~[-1672938363883:?]
	... 9 more

```

It is likely that the OpenStack password has been updated.

### Tasks
- [x] Contact Mike B for new OpenStack password
- [x] Exec onto the creds pod and update the Openstack password

**Comment by jadecarino** [comment]
I have contacted Mike Baylis for help on this.

**Comment by jadecarino** [comment]
Issue opened and assigned to Mike Baylis on GHE.
