### ISSUE TITLE
Docker inttests failing - "Image galasa-ubuntu-1804-nonshared is missing in OpenStack"

### ISSUE THREAD

**Issue by jadecarino** [galasa-dev/projectmanagement#1366]

**Comment by jadecarino** [comment]
James had a quick look during the team meeting and said that the image has been removed for some reason. I raised an issue for the CIT team as advised by James, but it was been closed and we have been told to deal with it. https://github.ibm.com/CICS/cics-ts-tracking/issues/1662

**Comment by Jimbo4794** [comment]
Slack Channel #hdc_user_chat
Openstack Workspace: CICS_TS
Contacts: Barry Packman, Alain Fisher

Contact and mentiont that the images names: "galasa-ubuntu-1804-nonshared, etc"

**Comment by jadecarino** [comment]
I have contacted Barry and Alain in the hdc_user_chat on Slack. Waiting for a response.

**Comment by jadecarino** [comment]
Conversation with Alain and Barry:


Alain Fisher
We'll take a look. If it's been removed it would not have been by us.


Alain Fisher
What HDC project are you using?


Alain Fisher
I can't see this one as being in our database. When did it last get used?


Alain Fisher
The only thing I can find that matches is an image called galasa-ubuntu-1804 which is still there. (edited) 


Jade Carino
Thank you for taking a look.
Re which project, I'm not 100% sure, I have just asked a colleague.
The tests last ran without the failure on Tuesday February 7th (they run daily), so I assume before this would have been the last time it was used.
There were two images, galasa-ubuntu-1804  and galasa-ubuntu-1804-nonshared which is the one the tests attempt to use. (edited) 


Barry Packman
The project is CICS_TS but there is no record of an image in the database with that name. The list we can find  is
+-----------------------------+---------+---------------------+---------------------+
| name                        | deleted | deleted_at          | created_at          |
+-----------------------------+---------+---------------------+---------------------+
| galasa-ubuntu-1804          |       0 | NULL                | 2021-07-19 09:34:21 |
| galasa-windows-10-new       |       1 | 2021-04-28 15:25:09 | 2021-04-28 11:12:27 |
| galasa-ubuntu-1804          |       1 | 2021-07-19 09:34:05 | 2021-05-05 09:02:21 |
| galasa-windows-10           |       0 | NULL                | 2021-04-28 15:25:22 |
| galasa-ubuntu-1804-isolated |       1 | 2021-05-12 09:10:37 | 2021-05-11 16:32:59 |
| galasa-windows-10           |       1 | 2021-04-28 15:25:03 | 2021-04-16 10:15:55 |
| galasa-ubuntu-1804          |       1 | 2021-04-16 10:17:15 | 2021-04-15 13:32:31 |
| galasa-ubuntu-1804          |       1 | 2021-05-05 09:02:03 | 2021-04-16 10:25:26 |
+-----------------------------+---------+---------------------+---------------------+


Barry Packman
Did some more digging and the i can see the last instance on 7th Feb.
+------------------+---------------------+---------------------+---------------------+--------------------------------------+
| hostname         | deleted_at          | created_at          | updated_at          | image_ref                            |
+------------------+---------------------+---------------------+---------------------+--------------------------------------+
| compute-galasa26 | 2023-02-07 06:14:57 | 2023-02-07 06:10:34 | 2023-02-07 06:14:57 | 3ae64caa-5447-4ef5-8c87-0df92f53bead |
+------------------+---------------------+---------------------+---------------------+--------------------------------------+
This used the image stated in the image_ref  which is as below
+--------------------+--------------------------------------+---------+------------+---------------------+---------------------+
| name               | id                                   | deleted | deleted_at | created_at          | updated_at          |
+--------------------+--------------------------------------+---------+------------+---------------------+---------------------+
| galasa-ubuntu-1804 | 3ae64caa-5447-4ef5-8c87-0df92f53bead |       0 | NULL       | 2021-07-19 09:34:21 | 2021-07-19 09:35:38 |
+--------------------+--------------------------------------+---------+------------+---------------------+---------------------+
Therefore the runs never used galasa-ubuntu-1804-nonshared. All the other compute-galasa  instances also used the above image

**Comment by jadecarino** [comment]
From the conversation above, it seems more investigation is required into what the Docker inttests actually do and why it logs to the console that it uses the 'galasa-ubuntu-1804-nonshared' image if it hasn't been. It may be the case that we can just tell the test to use the standard galasa-ubuntu-1804 image which is in OpenStack, but this would require understanding what this image contains first.

**Comment by jadecarino** [comment]
James and I feel that the Openstack API may have been upgraded over maintenance weekend and the API we try to retrieve the images from may be back level.

Some more conversation in the same thread between James and Barry on this subject:


James Davies
@bpackman
 did the openstack api version change with the maintenance? Looking at the automation that cant locate the image its looking at a /v2.5/images, so wondering if we cant find the image galasa-ubuntu-1804becuase of a change


Barry Packman
@James Davies (He/Him)
 No the version didnt change at the maintenance , i have to take another booking to upgrade the rest of the containers.  Not sure where /v2.5/images  comes from ? .  Its not something that openstack would recognise as it stores the images in its backend and that is referenced by the API calls to retrieve the image and that image exists. The image api version changed before the maint weekend around the 26th Jan. (edited) 


James Davies
Ah this has been failing for a bit of time, 
@jade.carino
 might have a better idea of time, but if something has changed in the API that might of affected.
Im not the original developer of the automation but it appears to get a openstack token. Then look through the backend API until it finds the api service:
Image 	https://hdc-prod-cloud.hursley.ibm.com:9292 
After that it does a look up of the image names https://hdc-prod-cloud.hursley.ibm.com:9292/v2.5/images


Barry Packman
Ok looks like it is specifically addressing a particular API microversion which you really shouldnt need to do unless there is something specific in that version that is needed . Its not really best practice,  simply specifying /v2/images   should be sufficient and then it can auto-resolve the micro version. https://docs.openstack.org/api-ref/image/v2 (edited) 


James Davies
Yeah that sounds more appropriate. We will make some changes to the code and hopefully that can resolve the problem. Thank you for the help as always :slightly_smiling_face:

**Comment by jadecarino** [comment]
PR to remove minor version from OpenStack API call, hopefully this auto resolves to the right version: https://github.com/galasa-dev/managers/pull/851

**Comment by jadecarino** [comment]
This is blocked by https://github.com/galasa-dev/projectmanagement/issues/1386

**Comment by jadecarino** [comment]
No longer blocked however changing the API version in the Openstack call has not fixed this issue. Moving back to Active swimlane.

**Comment by jadecarino** [comment]
Added some logging messages to the Openstack Manager and have a more detailed log below:
```
09/03/2023 19:36:30.206 INFO  d.g.f.TestRunner - Starting Provision Generate phase
09/03/2023 19:36:30.393 INFO  d.g.l.i.s.LinuxSharedProvisioner - Selected shared Linux image for PRIMARY host id is GALLNX02, with username galasa59
09/03/2023 19:36:30.406 DEBUG d.g.l.i.s.LinuxSharedImage - Linux shared image GALLNX02 has hostname of 9.20.205.207
09/03/2023 19:36:31.721 INFO  d.g.f.i.c.FrameworkConfidentialTextService - Confidential text registered as '*************1**************', with comment Temporary password for username galasa59
09/03/2023 19:36:32.806 INFO  d.g.l.i.s.LinuxSharedImage - Home directory for linux image tagged PRIMARY is /home/galasa59
09/03/2023 19:36:33.384 DEBUG d.g.o.m.i.OpenstackHttpClient - Connected to the OpenStack server
09/03/2023 19:36:33.384 INFO  d.g.o.m.i.OpenstackManagerImpl - Locating possible images that are available for selection
09/03/2023 19:36:33.389 INFO  d.g.o.m.i.OpenstackManagerImpl - Checking if image galasa-ubuntu-1804 is correct for this test
09/03/2023 19:36:33.392 INFO  d.g.o.m.i.OpenstackManagerImpl - This image had no available capabilities that we need so it is not possible to use
09/03/2023 19:36:33.392 INFO  d.g.o.m.i.OpenstackManagerImpl - Checking if image galasa-ubuntu-1804-nonshared is correct for this test
09/03/2023 19:36:33.394 INFO  d.g.o.m.i.OpenstackManagerImpl - +nonshared is an available capability of this image
09/03/2023 19:36:33.395 INFO  d.g.o.m.i.OpenstackManagerImpl - This image has an available capability nonshared that matches a chosen capability nonshared
09/03/2023 19:36:33.395 INFO  d.g.o.m.i.OpenstackManagerImpl - This image has an available capability nonshared that matches a required capability nonshared
09/03/2023 19:36:33.395 INFO  d.g.o.m.i.OpenstackManagerImpl - The selected image for this test is galasa-ubuntu-1804-nonshared
09/03/2023 19:36:33.488 INFO  d.g.o.m.i.OpenstackManagerImpl - Reserved OpenStack Linux instance compute.GALASA09 with image galasa-ubuntu-1804-nonshared for tag DOCKER
09/03/2023 19:36:33.596 INFO  d.g.f.TestRunner - Starting Provision Build phase
09/03/2023 19:36:33.597 INFO  d.g.o.m.i.OpenstackLinuxImageImpl - Building OpenStack Linux instance compute.GALASA09 with image galasa-ubuntu-1804-nonshared for tag DOCKER
09/03/2023 19:36:33.609 INFO  d.g.o.m.i.OpenstackLinuxImageImpl - The Linux flavor is m1.medium
09/03/2023 19:36:33.612 INFO  d.g.o.m.i.OpenstackLinuxImageImpl - The image name is galasa-ubuntu-1804
09/03/2023 19:36:33.613 INFO  d.g.o.m.i.OpenstackHttpClient - Openstack token is okay
09/03/2023 19:36:33.613 INFO  d.g.o.m.i.OpenstackHttpClient - Attempting to get a list of the images from https://hdc-prod-cloud.hursley.ibm.com:9292/v2/images
09/03/2023 19:36:34.322 INFO  d.g.o.m.i.OpenstackHttpClient - dev.galasa.openstack.manager.internal.json.Images@4b4814d0
09/03/2023 19:36:34.323 INFO  d.g.o.m.i.OpenstackHttpClient - No matching imageId found that matched galasa-ubuntu-1804
09/03/2023 19:36:34.400 ERROR d.g.f.TestRunner - Provision build failed
dev.galasa.framework.spi.FrameworkException: Problem in provision build for manager dev.galasa.openstack.manager.internal.OpenstackManagerImpl
	at dev.galasa.framework.TestRunManagers.provisionBuild(TestRunManagers.java:488) ~[-1678390583696:?]
	at dev.galasa.framework.TestRunner.createEnvironment(TestRunner.java:464) [-1678390583696:?]
	at dev.galasa.framework.TestRunner.generateEnvironment(TestRunner.java:450) [-1678390583696:?]
	at dev.galasa.framework.TestRunner.runTest(TestRunner.java:368) [-1678390583696:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at dev.galasa.boot.felix.FelixFramework.runTest(FelixFramework.java:235) [boot.jar:?]
	at dev.galasa.boot.Launcher.launch(Launcher.java:168) [boot.jar:?]
	at dev.galasa.boot.Launcher.main(Launcher.java:122) [boot.jar:?]
Caused by: dev.galasa.openstack.manager.OpenstackManagerException: Image galasa-ubuntu-1804-nonshared is missing in OpenStack
	at dev.galasa.openstack.manager.internal.OpenstackLinuxImageImpl.build(OpenstackLinuxImageImpl.java:108) ~[?:?]
	at dev.galasa.openstack.manager.internal.OpenstackManagerImpl.provisionBuild(OpenstackManagerImpl.java:132) ~[?:?]
	at dev.galasa.framework.TestRunManagers.provisionBuild(TestRunManagers.java:486) ~[-1678390583696:?]
	... 10 more
dev.galasa.framework.spi.FrameworkException: Problem in provision build for manager dev.galasa.openstack.manager.internal.OpenstackManagerImpl
	at dev.galasa.framework.TestRunManagers.provisionBuild(TestRunManagers.java:488) ~[-1678390583696:?]
	at dev.galasa.framework.TestRunner.createEnvironment(TestRunner.java:464) [-1678390583696:?]
	at dev.galasa.framework.TestRunner.generateEnvironment(TestRunner.java:450) [-1678390583696:?]
	at dev.galasa.framework.TestRunner.runTest(TestRunner.java:368) [-1678390583696:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at dev.galasa.boot.felix.FelixFramework.runTest(FelixFramework.java:235) [boot.jar:?]
	at dev.galasa.boot.Launcher.launch(Launcher.java:168) [boot.jar:?]
	at dev.galasa.boot.Launcher.main(Launcher.java:122) [boot.jar:?]
Caused by: dev.galasa.openstack.manager.OpenstackManagerException: Image galasa-ubuntu-1804-nonshared is missing in OpenStack
	at dev.galasa.openstack.manager.internal.OpenstackLinuxImageImpl.build(OpenstackLinuxImageImpl.java:108) ~[?:?]
	at dev.galasa.openstack.manager.internal.OpenstackManagerImpl.provisionBuild(OpenstackManagerImpl.java:132) ~[?:?]
	at dev.galasa.framework.TestRunManagers.provisionBuild(TestRunManagers.java:486) ~[-1678390583696:?]
	... 10 more
```
