### ISSUE TITLE
Integration tests are not updating the state of the Ecosystem after they finish

### ISSUE THREAD

**Issue by jadecarino** [galasa-dev/projectmanagement#1400]
## Describe the bug
After a test finishes in the ecosystem, some resources should be updated to state the test is finished, free up resources, etc. Especially important is the DSS which shows which resources etc are being used currently. This is not happening for some reason which needs investigation, NullPointerExceptions are being thrown. The DSS has recently got completely full up which caused big issues in the ecosystem. We need to fix this.

```
05/03/2023 16:49:16.260 INFO  d.g.f.TestRunner - Starting Provision Discard phase
05/03/2023 16:49:16.286 WARN  d.g.g.i.LocalLinuxEcosystemImpl - Failed to save the local ecosystem CPS
java.lang.NullPointerException: null
	at dev.galasa.galasaecosystem.internal.LocalEcosystemImpl.discard(LocalEcosystemImpl.java:482) [-1678034948870:?]
	at dev.galasa.galasaecosystem.internal.LocalLinuxEcosystemImpl.discard(LocalLinuxEcosystemImpl.java:86) [-1678034948870:?]
	at dev.galasa.galasaecosystem.internal.GalasaEcosystemManagerImpl.provisionDiscard(GalasaEcosystemManagerImpl.java:518) [-1678034948870:?]
	at dev.galasa.framework.TestRunManagers.provisionDiscard(TestRunManagers.java:514) [-1678034945866:?]
	at dev.galasa.framework.TestRunner.discardEnvironment(TestRunner.java:493) [-1678034945866:?]
	at dev.galasa.framework.TestRunner.createEnvironment(TestRunner.java:482) [-1678034945866:?]
	at dev.galasa.framework.TestRunner.generateEnvironment(TestRunner.java:450) [-1678034945866:?]
	at dev.galasa.framework.TestRunner.runTest(TestRunner.java:368) [-1678034945866:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at dev.galasa.boot.felix.FelixFramework.runTest(FelixFramework.java:235) [boot.jar:?]
	at dev.galasa.boot.Launcher.launch(Launcher.java:168) [boot.jar:?]
	at dev.galasa.boot.Launcher.main(Launcher.java:122) [boot.jar:?]
java.lang.NullPointerException: null
	at dev.galasa.galasaecosystem.internal.LocalEcosystemImpl.discard(LocalEcosystemImpl.java:482) [-1678034948870:?]
	at dev.galasa.galasaecosystem.internal.LocalLinuxEcosystemImpl.discard(LocalLinuxEcosystemImpl.java:86) [-1678034948870:?]
	at dev.galasa.galasaecosystem.internal.GalasaEcosystemManagerImpl.provisionDiscard(GalasaEcosystemManagerImpl.java:518) [-1678034948870:?]
	at dev.galasa.framework.TestRunManagers.provisionDiscard(TestRunManagers.java:514) [-1678034945866:?]
	at dev.galasa.framework.TestRunner.discardEnvironment(TestRunner.java:493) [-1678034945866:?]
	at dev.galasa.framework.TestRunner.createEnvironment(TestRunner.java:482) [-1678034945866:?]
	at dev.galasa.framework.TestRunner.generateEnvironment(TestRunner.java:450) [-1678034945866:?]
	at dev.galasa.framework.TestRunner.runTest(TestRunner.java:368) [-1678034945866:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at dev.galasa.boot.felix.FelixFramework.runTest(FelixFramework.java:235) [boot.jar:?]
	at dev.galasa.boot.Launcher.launch(Launcher.java:168) [boot.jar:?]
	at dev.galasa.boot.Launcher.main(Launcher.java:122) [boot.jar:?]
05/03/2023 16:49:16.289 WARN  d.g.g.i.LocalLinuxEcosystemImpl - Failed to save the local ecosystem DSS
java.lang.NullPointerException: null
	at dev.galasa.galasaecosystem.internal.LocalEcosystemImpl.discard(LocalEcosystemImpl.java:489) [-1678034948870:?]
	at dev.galasa.galasaecosystem.internal.LocalLinuxEcosystemImpl.discard(LocalLinuxEcosystemImpl.java:86) [-1678034948870:?]
	at dev.galasa.galasaecosystem.internal.GalasaEcosystemManagerImpl.provisionDiscard(GalasaEcosystemManagerImpl.java:518) [-1678034948870:?]
	at dev.galasa.framework.TestRunManagers.provisionDiscard(TestRunManagers.java:514) [-1678034945866:?]
	at dev.galasa.framework.TestRunner.discardEnvironment(TestRunner.java:493) [-1678034945866:?]
	at dev.galasa.framework.TestRunner.createEnvironment(TestRunner.java:482) [-1678034945866:?]
	at dev.galasa.framework.TestRunner.generateEnvironment(TestRunner.java:450) [-1678034945866:?]
	at dev.galasa.framework.TestRunner.runTest(TestRunner.java:368) [-1678034945866:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at dev.galasa.boot.felix.FelixFramework.runTest(FelixFramework.java:235) [boot.jar:?]
	at dev.galasa.boot.Launcher.launch(Launcher.java:168) [boot.jar:?]
	at dev.galasa.boot.Launcher.main(Launcher.java:122) [boot.jar:?]
java.lang.NullPointerException: null
	at dev.galasa.galasaecosystem.internal.LocalEcosystemImpl.discard(LocalEcosystemImpl.java:489) [-1678034948870:?]
	at dev.galasa.galasaecosystem.internal.LocalLinuxEcosystemImpl.discard(LocalLinuxEcosystemImpl.java:86) [-1678034948870:?]
	at dev.galasa.galasaecosystem.internal.GalasaEcosystemManagerImpl.provisionDiscard(GalasaEcosystemManagerImpl.java:518) [-1678034948870:?]
	at dev.galasa.framework.TestRunManagers.provisionDiscard(TestRunManagers.java:514) [-1678034945866:?]
	at dev.galasa.framework.TestRunner.discardEnvironment(TestRunner.java:493) [-1678034945866:?]
	at dev.galasa.framework.TestRunner.createEnvironment(TestRunner.java:482) [-1678034945866:?]
	at dev.galasa.framework.TestRunner.generateEnvironment(TestRunner.java:450) [-1678034945866:?]
	at dev.galasa.framework.TestRunner.runTest(TestRunner.java:368) [-1678034945866:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at dev.galasa.boot.felix.FelixFramework.runTest(FelixFramework.java:235) [boot.jar:?]
	at dev.galasa.boot.Launcher.launch(Launcher.java:168) [boot.jar:?]
	at dev.galasa.boot.Launcher.main(Launcher.java:122) [boot.jar:?]
05/03/2023 16:49:16.289 WARN  d.g.g.i.LocalLinuxEcosystemImpl - Failed to save the local ecosystem overrides
java.lang.NullPointerException: null
	at dev.galasa.galasaecosystem.internal.LocalEcosystemImpl.discard(LocalEcosystemImpl.java:496) [-1678034948870:?]
	at dev.galasa.galasaecosystem.internal.LocalLinuxEcosystemImpl.discard(LocalLinuxEcosystemImpl.java:86) [-1678034948870:?]
	at dev.galasa.galasaecosystem.internal.GalasaEcosystemManagerImpl.provisionDiscard(GalasaEcosystemManagerImpl.java:518) [-1678034948870:?]
	at dev.galasa.framework.TestRunManagers.provisionDiscard(TestRunManagers.java:514) [-1678034945866:?]
	at dev.galasa.framework.TestRunner.discardEnvironment(TestRunner.java:493) [-1678034945866:?]
	at dev.galasa.framework.TestRunner.createEnvironment(TestRunner.java:482) [-1678034945866:?]
	at dev.galasa.framework.TestRunner.generateEnvironment(TestRunner.java:450) [-1678034945866:?]
	at dev.galasa.framework.TestRunner.runTest(TestRunner.java:368) [-1678034945866:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at dev.galasa.boot.felix.FelixFramework.runTest(FelixFramework.java:235) [boot.jar:?]
	at dev.galasa.boot.Launcher.launch(Launcher.java:168) [boot.jar:?]
	at dev.galasa.boot.Launcher.main(Launcher.java:122) [boot.jar:?]
java.lang.NullPointerException: null
	at dev.galasa.galasaecosystem.internal.LocalEcosystemImpl.discard(LocalEcosystemImpl.java:496) [-1678034948870:?]
	at dev.galasa.galasaecosystem.internal.LocalLinuxEcosystemImpl.discard(LocalLinuxEcosystemImpl.java:86) [-1678034948870:?]
	at dev.galasa.galasaecosystem.internal.GalasaEcosystemManagerImpl.provisionDiscard(GalasaEcosystemManagerImpl.java:518) [-1678034948870:?]
	at dev.galasa.framework.TestRunManagers.provisionDiscard(TestRunManagers.java:514) [-1678034945866:?]
	at dev.galasa.framework.TestRunner.discardEnvironment(TestRunner.java:493) [-1678034945866:?]
	at dev.galasa.framework.TestRunner.createEnvironment(TestRunner.java:482) [-1678034945866:?]
	at dev.galasa.framework.TestRunner.generateEnvironment(TestRunner.java:450) [-1678034945866:?]
	at dev.galasa.framework.TestRunner.runTest(TestRunner.java:368) [-1678034945866:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at dev.galasa.boot.felix.FelixFramework.runTest(FelixFramework.java:235) [boot.jar:?]
	at dev.galasa.boot.Launcher.launch(Launcher.java:168) [boot.jar:?]
	at dev.galasa.boot.Launcher.main(Launcher.java:122) [boot.jar:?]
05/03/2023 16:49:16.379 WARN  d.g.g.i.LocalLinuxEcosystemImpl - Failed to save the local ecosystem bootstrap
java.lang.NullPointerException: null
	at dev.galasa.galasaecosystem.internal.LocalEcosystemImpl.discard(LocalEcosystemImpl.java:503) [-1678034948870:?]
	at dev.galasa.galasaecosystem.internal.LocalLinuxEcosystemImpl.discard(LocalLinuxEcosystemImpl.java:86) [-1678034948870:?]
	at dev.galasa.galasaecosystem.internal.GalasaEcosystemManagerImpl.provisionDiscard(GalasaEcosystemManagerImpl.java:518) [-1678034948870:?]
	at dev.galasa.framework.TestRunManagers.provisionDiscard(TestRunManagers.java:514) [-1678034945866:?]
	at dev.galasa.framework.TestRunner.discardEnvironment(TestRunner.java:493) [-1678034945866:?]
	at dev.galasa.framework.TestRunner.createEnvironment(TestRunner.java:482) [-1678034945866:?]
	at dev.galasa.framework.TestRunner.generateEnvironment(TestRunner.java:450) [-1678034945866:?]
	at dev.galasa.framework.TestRunner.runTest(TestRunner.java:368) [-1678034945866:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at dev.galasa.boot.felix.FelixFramework.runTest(FelixFramework.java:235) [boot.jar:?]
	at dev.galasa.boot.Launcher.launch(Launcher.java:168) [boot.jar:?]
	at dev.galasa.boot.Launcher.main(Launcher.java:122) [boot.jar:?]
java.lang.NullPointerException: null
	at dev.galasa.galasaecosystem.internal.LocalEcosystemImpl.discard(LocalEcosystemImpl.java:503) [-1678034948870:?]
	at dev.galasa.galasaecosystem.internal.LocalLinuxEcosystemImpl.discard(LocalLinuxEcosystemImpl.java:86) [-1678034948870:?]
	at dev.galasa.galasaecosystem.internal.GalasaEcosystemManagerImpl.provisionDiscard(GalasaEcosystemManagerImpl.java:518) [-1678034948870:?]
	at dev.galasa.framework.TestRunManagers.provisionDiscard(TestRunManagers.java:514) [-1678034945866:?]
	at dev.galasa.framework.TestRunner.discardEnvironment(TestRunner.java:493) [-1678034945866:?]
	at dev.galasa.framework.TestRunner.createEnvironment(TestRunner.java:482) [-1678034945866:?]
	at dev.galasa.framework.TestRunner.generateEnvironment(TestRunner.java:450) [-1678034945866:?]
	at dev.galasa.framework.TestRunner.runTest(TestRunner.java:368) [-1678034945866:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at dev.galasa.boot.felix.FelixFramework.runTest(FelixFramework.java:235) [boot.jar:?]
	at dev.galasa.boot.Launcher.launch(Launcher.java:168) [boot.jar:?]
	at dev.galasa.boot.Launcher.main(Launcher.java:122) [boot.jar:?]
05/03/2023 16:49:16.380 INFO  d.g.g.i.LocalLinuxEcosystemImpl - Not saving credentials into stored artifacts for security reasons
05/03/2023 16:49:16.417 INFO  d.g.l.i.s.LinuxSharedImage - Discarded Linux shared image GALLNX01 with username galasa25
05/03/2023 16:49:16.859 INFO  d.g.o.m.i.OpenstackServerImpl - OpenStack Linux instance compute.GALASA61 for tag DOCKER has been discarded
05/03/2023 16:49:17.401 INFO  d.g.r.c.i.CouchdbRasWriteByteChannel - Stored artifact /framework/cps_record.properties, length=0, contentType=plain/text
05/03/2023 16:49:17.447 INFO  d.g.r.c.i.CouchdbRasWriteByteChannel - Stored artifact /framework/cps_record.properties, length=3699, contentType=plain/text
05/03/2023 16:49:17.448 INFO  d.g.f.Framework - Shutting down the framework
```

**Comment by techcobweb** [comment]
@jadecarino  How to reproduce this issue ?

**Comment by techcobweb** [comment]
@jadecarino Any idea which tests fails with the above stack trace ?

**Comment by techcobweb** [comment]
Unpreproduceable currently. Closing until it re-occurs.
