### ISSUE TITLE
--class parameter of 'galasactl runs submit' not working

### ISSUE THREAD

**Issue by jadecarino** [galasa-dev/projectmanagement#1430]
## Describe the bug
The --class parameter of 'galasactl runs submit' should enable you to submit tests in the ecosystem, without first generating a test portfolio, however this does not seem to be working. The documentation specifies: 
```
The --class parameter tells the tool which test class to run. The string is in the format of <osgi-bundle-id>/<fully-qualified-java-class>. All the test methods within the class will be run. You can use multiple such flags to test multiple classes.
```

## Steps to reproduce
1. Run `galasactl runs submit --bootstrap $bootstrap --class dev.galasa.inttests/dev.galasa.inttests.core.local.CoreLocalJava11Ubuntu --throttle 1 --poll 10 --progress 1 --log -`
2. The test will come back as UNKNOWN, and you should see this message in the log for the test run itself: 
```
12/04/2023 09:44:20.239 ERROR d.g.f.TestRunner - Unable to load the test bundle dev.galasa.inttests
dev.galasa.framework.spi.FrameworkException: Unable to install bundle "dev.galasa.inttests" from OBR repository
	at dev.galasa.framework.BundleManagement.loadBundle(BundleManagement.java:55) ~[-1681292658247:?]
	at dev.galasa.framework.TestRunner.runTest(TestRunner.java:222) [-1681292658247:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at dev.galasa.boot.felix.FelixFramework.runTest(FelixFramework.java:235) [boot.jar:?]
	at dev.galasa.boot.Launcher.launch(Launcher.java:168) [boot.jar:?]
	at dev.galasa.boot.Launcher.main(Launcher.java:122) [boot.jar:?]
Caused by: dev.galasa.framework.spi.FrameworkException: Unable to locate bundle "dev.galasa.inttests" in OBR repository
	at dev.galasa.framework.BundleManagement.loadBundle(BundleManagement.java:50) ~[-1681292658247:?]
	... 8 more
dev.galasa.framework.spi.FrameworkException: Unable to install bundle "dev.galasa.inttests" from OBR repository
	at dev.galasa.framework.BundleManagement.loadBundle(BundleManagement.java:55) ~[-1681292658247:?]
	at dev.galasa.framework.TestRunner.runTest(TestRunner.java:222) [-1681292658247:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at dev.galasa.boot.felix.FelixFramework.runTest(FelixFramework.java:235) [boot.jar:?]
	at dev.galasa.boot.Launcher.launch(Launcher.java:168) [boot.jar:?]
	at dev.galasa.boot.Launcher.main(Launcher.java:122) [boot.jar:?]
Caused by: dev.galasa.framework.spi.FrameworkException: Unable to locate bundle "dev.galasa.inttests" in OBR repository
	at dev.galasa.framework.BundleManagement.loadBundle(BundleManagement.java:50) ~[-1681292658247:?]
	... 8 more
```

## Expected behavior
The test dev.galasa.inttests/dev.galasa.inttests.core.local.CoreLocalJava11Ubuntu exists in our ecosystem so galasactl should be able to find it and run it without issues.

## Additional context
N/A

**Comment by techcobweb** [comment]
Did this ever work ? When ?

**Comment by Akyiaa** [comment]
In simplatform run-locally.sh, there is a tests function which runs the following "galasactl runs submit" command **successfully**:
```
cmd="galasactl runs submit local --log - \
    --obr mvn:dev.galasa.example.banking/dev.galasa.example.banking.obr/0.0.1-SNAPSHOT/obr \
    --class dev.galasa.example.banking.account/dev.galasa.example.banking.account.TestAccount \
    "
```

**Comment by Akyiaa** [comment]
When build-locally.sh is called, the command below fails, but does not show UNKNOWN error as above. 
`galasactl runs submit local     --obr mvn:dev.galasa.example.banking/dev.galasa.example.banking.obr/0.0.1-SNAPSHOT/obr     --class dev.galasa.example.banking.payee/dev.galasa.example.banking.payee.TestPayeeExtended     --throttle 1     --requesttype MikeCLI     --poll 10     --progress 1     --log -`

```
2023/08/15 13:29:57 ***
*** Final report
*** ---------------
***
*** Passed test runs:-
***     None
***
*** Failed test runs:-
***     None
***
*** Passed With Defects test runs:-
***     None
***
*** Failed With Defects test runs:-
***     None
***
*** Other test runs:-
***     None
***
*** results
*** results , Lost=1, Passed=0, Failed=0, Passed With Defects=0, Failed With Defects=0
***
*** Final report
*** ---------------
***
*** Passed test runs:-
***     None
***
*** Failed test runs:-
***     None
***
*** Passed With Defects test runs:-
***     None
***
*** Failed With Defects test runs:-
***     None
***
*** Other test runs:-
***     None
***
*** results
*** results , Lost=1, Passed=0, Failed=0, Passed With Defects=0, Failed With Defects=0
2023/08/15 13:29:57 GAL1017E: Not all runs passed. 1 failed.
GAL1017E: Not all runs passed. 1 failed.
2023/08/15 13:29:57 Exit code is 2
```

**Comment by KirbyKatcher** [comment]
After changing this code in BundleMangement
from 
```Java
   try {
            if (resources.length == 0) {
                throw new FrameworkException("Unable to locate bundle \"" + bundleSymbolicName + "\" in OBR repository");
            }
            // *** Only load the first one
            addResource(bundleContext, bundleSymbolicName, resolver, resources[0]);
        } catch (FrameworkException e) {
            throw new FrameworkException("Unable to install bundle \"" + bundleSymbolicName + "\" from OBR repository",
                    e);
        }
```
to
```Java
        if (resources.length == 0) {
            throw new FrameworkException("Unable to locate bundle \"" + bundleSymbolicName + "\" in OBR repository");
        }
        try {
            // *** Only load the first one
            addResource(bundleContext, bundleSymbolicName, resolver, resources[0]);
        } catch (FrameworkException e) {
            throw new FrameworkException("Unable to install bundle \"" + bundleSymbolicName + "\" from OBR repository",e);
        }
```
We are getting the `dev.galasa.framework.spi.FrameworkException: Unable to locate bundle "dev.galasa.inttests" in OBR repository` Exception which suggest that we are not locating the obr correctly.

**Comment by KirbyKatcher** [comment]
When running with the obr supplied in the command
```shell
./bin/galasactl-darwin-amd64 runs submit local    --class dev.galasa.inttests/dev.galasa.inttests.core.local.CoreLocalJava11Ubuntu   --obr mvn:dev.galasa/dev.galasa.inttests.obr/0.14.0/obr  --throttle 1     --poll 10     --progress 1     --noexitcodeontestfailures     --log -
```
the obr is downlaoded from maven central, however the test fails due 
```
dev.galasa.framework.TestRunException: Unable to load test class dev.galasa.inttests.core.local.CoreLocalJava11Ubuntu
        at dev.galasa.framework.TestRunner.getTestClass(TestRunner.java:725) ~[-1692194430452:?]
        at dev.galasa.framework.TestRunner.runTest(TestRunner.java:235) [-1692194430452:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
        at dev.galasa.boot.felix.FelixFramework.runTest(FelixFramework.java:236) [galasa-boot-0.30.0.jar:?]
        at dev.galasa.boot.Launcher.launch(Launcher.java:176) [galasa-boot-0.30.0.jar:?]
        at dev.galasa.boot.Launcher.main(Launcher.java:126) [galasa-boot-0.30.0.jar:?]
Caused by: java.lang.ClassNotFoundException: dev.galasa.inttests.core.local.CoreLocalJava11Ubuntu not found by dev.galasa.inttests [35]
        at org.apache.felix.framework.BundleWiringImpl.findClassOrResourceByDelegation(BundleWiringImpl.java:1585) ~[galasa-boot-0.30.0.jar:?]
        at org.apache.felix.framework.BundleWiringImpl.access$300(BundleWiringImpl.java:79) ~[galasa-boot-0.30.0.jar:?]
        at org.apache.felix.framework.BundleWiringImpl$BundleClassLoader.loadClass(BundleWiringImpl.java:1970) ~[galasa-boot-0.30.0.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:1074) ~[?:?]
        at org.apache.felix.framework.Felix.loadBundleClass(Felix.java:2116) ~[galasa-boot-0.30.0.jar:?]
        at org.apache.felix.framework.BundleImpl.loadClass(BundleImpl.java:987) ~[galasa-boot-0.30.0.jar:?]
        at dev.galasa.framework.TestRunner.getTestClass(TestRunner.java:723) ~[-1692194430452:?]
        ... 8 more
```

**Comment by Akyiaa** [comment]
Class is on an ecosystem so should be running on stream. Since stream flag is not specified, it does not know how to locate the test.
Obr flag is not needed since we're looking for the test in the stream and not locally.

```
./bin/galasactl-darwin-amd64 runs submit 
--class dev.galasa.inttests/dev.galasa.inttests.core.local.CoreLocalJava11Ubuntu 
--throttle 1 --poll 10 
--progress 1 --bootstrap http://galasa-cicsk8s.hursley.ibm.com/bootstrap 
 --stream inttests --log -
```

**Comment by techcobweb** [comment]
How can the framework on a remote ecosystem know where to load the class from, if the stream is not specified ?

You would have to add the local maven flag ?

**Comment by techcobweb** [comment]
So it seems to me that the --class parameter can't be used without the --stream parameter, and the error message should say that.

What do you think @jadecarino ?

**Comment by techcobweb** [comment]
@Jimbo4794 confirmed that a test should not run on the ecosystem unless the test is drawn from a stream, as the stream points to a trusted source of test material, and informs the ecosystem where to load the test from.

Anything else is a security vulnerability.

The readme is wrong suggesting you can run such tests in the remote ecosystem.

The readme needs to change.

The docs may need to change.

**Comment by techcobweb** [comment]
The readme has been updated to remove any examples which are missing the --stream parameter.

**Comment by techcobweb** [comment]
So only the docs need correcting and we can close this issue.
