### ISSUE TITLE
@ZosImage does not work

### ISSUE THREAD

**Issue by ChrisAtkinson1** [galasa-dev/projectmanagement#1431]
Setting this as per https://galasa.dev/docs/writing-own-tests/binding-tests#gatsby-focus-wrapper with my zos images set.

It does not pick up the image for use.

Error is

20/02/2023 15:08:57.500 INFO  d.g.f.TestRunner - Provision Generate failed
dev.galasa.framework.spi.FrameworkException: Problem in provision generate for manager dev.galasa.zos.internal.ZosManagerImpl
        at dev.galasa.framework.TestRunManagers.provisionGenerate(TestRunManagers.java:478) ~[-1676905729865:?]
        at dev.galasa.framework.TestRunner.generateEnvironment(TestRunner.java:435) [-1676905729865:?]
        at dev.galasa.framework.TestRunner.runTest(TestRunner.java:368) [-1676905729865:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
        at dev.galasa.boot.felix.FelixFramework.runTest(FelixFramework.java:236) [galasa-boot.jar:?]
        at dev.galasa.boot.Launcher.launch(Launcher.java:166) [galasa-boot.jar:?]
        at dev.galasa.boot.Launcher.main(Launcher.java:120) [galasa-boot.jar:?]
Caused by: dev.galasa.zos.ZosManagerException: Unable to locate zOS images for cluster DEFAULT, see property zos.cluster.*.images
        at dev.galasa.zos.internal.properties.ClusterImages.get(ClusterImages.java:39) ~[?:?]
        at dev.galasa.zos.internal.ZosManagerImpl.selectNewImage(ZosManagerImpl.java:380) ~[?:?]
        at dev.galasa.zos.internal.ZosManagerImpl.generateZosImage(ZosManagerImpl.java:327) ~[?:?]
        at dev.galasa.zos.internal.ZosManagerImpl.generateZosImage(ZosManagerImpl.java:274) ~[?:?]
        at dev.galasa.zos.internal.ZosManagerImpl.provisionGenerate(ZosManagerImpl.java:234) ~[?:?]
        at dev.galasa.framework.TestRunManagers.provisionGenerate(TestRunManagers.java:473) ~[-1676905729865:?]
        ... 9 more

**Comment by hobbit1983** [comment]
@ChrisAtkinson1 finally got around to figuring this out.  You just need to add the following CPS property:
`zos.tag.PLEX.clusterid.PLEX` to associate the PLEX that you have specified in the image tag with the cluster ID of PLEX.

**Comment by hobbit1983** [comment]
I've submitted a PR to add some logging when selecting a zosImage to make debugging this a lot easier.  However the rules that are encoded are as follows.  @CaroMac can you check that we get this into the doc - alongside the guide that @Jimbo4794 wrote.  

If a tag is specified in the annotation then that is used, else PRIMARY is used

Check is there a zos.dse.tag for the selected tag
zos.dse.tag.PRIMARY.imageid=<image>
zos.dse.tag.PRIMARY.clusterid=<cluster> (Although this is not needed)
-->Image can be looked up, generated and returned

If no DSE tag is found:
zos.tag.PRIMARY.imageid=<image>
-->Image can be looked up, generated and returned

If no IMAGEID is found
zos.tag.PRIMARY.clusterid=<cluster>
If cluster cannot be found then CLUSTER is defaulted to DEFAULT

zos.cluster.DEFAULT.images=image1,image2
-->attempt to find a image with slots free in the cluster

Obviously the normal image hostname, port etc need to be defined

@ChrisAtkinson1 I've managed to use the rules above to build and run a test that uses a zosImage annotation.  Can you take a look and see if this resolves your issues
