### ISSUE TITLE
visible stack trace when galasactl tries to write log content to a directory

### ISSUE THREAD

**Issue by hobbit1983** [galasa-dev/projectmanagement#1451]
## Describe the bug
Running the command:
`galasactl project create --features one --features two --log . --package test.com`
and accidentally using `.` rather than `-` to specify that the log should go to stdout gives the following error:

```2023/05/04 18:38:42 goroutine 1 [running]:
github.com/galasa.dev/cli/pkg/errors.LogStackTrace()
	/workspace/git/repo-cli-main-w4b75/cli/pkg/errors/debug.go:16 +0x38
github.com/galasa.dev/cli/pkg/errors.NewGalasaError(0x14000142260, {0x14000189d08?, 0x602?, 0x1022d7410?})
	/workspace/git/repo-cli-main-w4b75/cli/pkg/errors/errorMessage.go:53 +0xb8
github.com/galasa.dev/cli/pkg/utils.CaptureLog({0x16dcb39ad, 0x1})
	/workspace/git/repo-cli-main-w4b75/cli/pkg/utils/logRedirector.go:39 +0x12c
github.com/galasa.dev/cli/pkg/cmd.executeCreateProject(0x102c65e00?, {0x1400017a680?, 0x8?, 0x8?})
	/workspace/git/repo-cli-main-w4b75/cli/pkg/cmd/projectCreate.go:81 +0x2c
github.com/spf13/cobra.(*Command).execute(0x102c65e00, {0x1400017a600, 0x8, 0x8})
	/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:856 +0x4ac
github.com/spf13/cobra.(*Command).ExecuteC(0x102c65b80)
	/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:960 +0x34c
github.com/spf13/cobra.(*Command).Execute(...)
	/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:897
github.com/galasa.dev/cli/pkg/cmd.Execute()
	/workspace/git/repo-cli-main-w4b75/cli/pkg/cmd/root.go:47 +0x44
main.main()
	/workspace/git/repo-cli-main-w4b75/cli/cmd/galasactl/main.go:14 +0x1c

GAL1020E: Failed to open log file '.' for writing. Reason is open .: is a directory```

## Expected behavior
The error (GAL1020E) is fine but we should suppress the panic

**Comment by techcobweb** [comment]
Each error is set up so that if it happens, it can optionally produce a stack trace sent to the log.

Setting up the log is the first thing that all the commands try to do.

If the log isn't set up, by default, it gets pushed to stderr.

So in this case, the log can't be set up, so the stack trace is created. Normally the stack trace goes to the log, but in this case the log can't be set up.

Sounds like we just need to turn off the stack tracing for GAL1020E and it will be fine.

**Comment by techcobweb** [comment]
Code now does this:
```
>galasactl project create --features a,b --package mypackage1 --log .
GAL1069E: Could not open log file for writing. '.' is a directory, the --log parameter should refer to a file path (existing or not), or '-' (the console)
```

**Comment by hobbit1983** [comment]
Perfect!
