### ISSUE TITLE
CLI: galasa bootstrap default location bad for local launch on Windows

### ISSUE THREAD

**Issue by techcobweb** [galasa-dev/projectmanagement#1502]
## Bug

- On Windows. 
- `GALASA_BOOTSTRAP` env var is not set
- Command to run doesn't use the `--bootstrap` flag.
- `GALASA_HOME` is set
- The command `galasactl submit runs local` is being used to run a local test.

- The result:

```
C:\temp\GLTest>galasactl runs submit local --log - --obr mvn:com.ibm.cics.exampletests/com.ibm.cics.exampletests.obr/0.0.1-SNAPSHOT/obr --class com.ibm.cics.exampletests.cemt/com.ibm.cics.exampletests.cemt.TestCemt --reportjunit test.xml
2023/06/15 15:38:21 Galasa CLI - Submit tests (Local)
2023/06/15 15:38:21 Galasa home is 'C:\temp\GLTest\GLHOME'
2023/06/15 15:38:21 goroutine 1 [running]:
github.com/galasa.dev/cli/pkg/errors.LogStackTrace()
        /Users/hobbit/git/galasa/cli/pkg/errors/debug.go:16 +0x39
github.com/galasa.dev/cli/pkg/errors.NewGalasaError(0xc0000a0920, {0xc0000c7b08?, 0x30?, 0x115a560?})
        /Users/hobbit/git/galasa/cli/pkg/errors/errorMessage.go:53 +0xae
github.com/galasa.dev/cli/pkg/utils.(*OSFileSystem).ReadTextFile(0xee0840, {0xc0000be747, 0x2b})
        /Users/hobbit/git/galasa/cli/pkg/utils/fileSystem.go:126 +0xb4
github.com/galasa.dev/cli/pkg/api.loadBootstrapFromFile({0xc0000be740, 0x32}, {0xa32f50, 0x10}, {0xee0840, 0x11af2b8})
        /Users/hobbit/git/galasa/cli/pkg/api/bootstrap.go:172 +0xe7
github.com/galasa.dev/cli/pkg/api.LoadBootstrap({0xedcc08?, 0xc00014a090?}, {0xee0840, 0x11af2b8}, {0xedb340?, 0x11af2b8?}, {0x0?, 0x0?}, {0xedb2a0, 0x11af2b8})
        /Users/hobbit/git/galasa/cli/pkg/api/bootstrap.go:124 +0x1b6
github.com/galasa.dev/cli/pkg/cmd.executeSubmitLocal(0x1152480?, {0xc000076280?, 0x8?, 0x8?})
        /Users/hobbit/git/galasa/cli/pkg/cmd/runsSubmitLocal.go:108 +0x134
github.com/spf13/cobra.(*Command).execute(0x1152480, {0xc000076200, 0x8, 0x8})
        /Users/hobbit/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:856 +0x663
github.com/spf13/cobra.(*Command).ExecuteC(0x1152700)
        /Users/hobbit/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:960 +0x39d
github.com/spf13/cobra.(*Command).Execute(...)
        /Users/hobbit/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:897
github.com/galasa.dev/cli/pkg/cmd.Execute()
        /Users/hobbit/git/galasa/cli/pkg/cmd/root.go:47 +0x45
main.main()
        /Users/hobbit/git/galasa/cli/cmd/galasactl/main.go:14 +0x17

2023/06/15 15:38:21 goroutine 1 [running]:
github.com/galasa.dev/cli/pkg/errors.LogStackTrace()
        /Users/hobbit/git/galasa/cli/pkg/errors/debug.go:16 +0x39
github.com/galasa.dev/cli/pkg/errors.NewGalasaError(0xc0000a0aa0, {0xc0000c7b90?, 0x2b?, 0x32?})
        /Users/hobbit/git/galasa/cli/pkg/errors/errorMessage.go:53 +0xae
github.com/galasa.dev/cli/pkg/api.loadBootstrapFromFile({0xc0000be740, 0x32}, {0xa32f50, 0x10}, {0xee0840, 0x11af2b8})
        /Users/hobbit/git/galasa/cli/pkg/api/bootstrap.go:176 +0x185
github.com/galasa.dev/cli/pkg/api.LoadBootstrap({0xedcc08?, 0xc00014a090?}, {0xee0840, 0x11af2b8}, {0xedb340?, 0x11af2b8?}, {0x0?, 0x0?}, {0xedb2a0, 0x11af2b8})
        /Users/hobbit/git/galasa/cli/pkg/api/bootstrap.go:124 +0x1b6
github.com/galasa.dev/cli/pkg/cmd.executeSubmitLocal(0x1152480?, {0xc000076280?, 0x8?, 0x8?})
        /Users/hobbit/git/galasa/cli/pkg/cmd/runsSubmitLocal.go:108 +0x134
github.com/spf13/cobra.(*Command).execute(0x1152480, {0xc000076200, 0x8, 0x8})
        /Users/hobbit/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:856 +0x663
github.com/spf13/cobra.(*Command).ExecuteC(0x1152700)
        /Users/hobbit/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:960 +0x39d
github.com/spf13/cobra.(*Command).Execute(...)
        /Users/hobbit/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:897
github.com/galasa.dev/cli/pkg/cmd.Execute()
        /Users/hobbit/git/galasa/cli/pkg/cmd/root.go:47 +0x45
main.main()
        /Users/hobbit/git/galasa/cli/cmd/galasactl/main.go:14 +0x17

2023/06/15 15:38:21 goroutine 1 [running]:
github.com/galasa.dev/cli/pkg/errors.LogStackTrace()
        /Users/hobbit/git/galasa/cli/pkg/errors/debug.go:16 +0x39
github.com/galasa.dev/cli/pkg/errors.NewGalasaError(0xc0000a0b00, {0xc0000c7c28?, 0xa32f50?, 0x10?})
        /Users/hobbit/git/galasa/cli/pkg/errors/errorMessage.go:53 +0xae
github.com/galasa.dev/cli/pkg/api.LoadBootstrap({0xedcc08?, 0xc00014a090?}, {0xee0840, 0x11af2b8}, {0xedb340?, 0x11af2b8?}, {0x0?, 0x0?}, {0xedb2a0, 0x11af2b8})
        /Users/hobbit/git/galasa/cli/pkg/api/bootstrap.go:143 +0x2d8
github.com/galasa.dev/cli/pkg/cmd.executeSubmitLocal(0x1152480?, {0xc000076280?, 0x8?, 0x8?})
        /Users/hobbit/git/galasa/cli/pkg/cmd/runsSubmitLocal.go:108 +0x134
github.com/spf13/cobra.(*Command).execute(0x1152480, {0xc000076200, 0x8, 0x8})
        /Users/hobbit/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:856 +0x663
github.com/spf13/cobra.(*Command).ExecuteC(0x1152700)
        /Users/hobbit/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:960 +0x39d
github.com/spf13/cobra.(*Command).Execute(...)
        /Users/hobbit/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:897
github.com/galasa.dev/cli/pkg/cmd.Execute()
        /Users/hobbit/git/galasa/cli/pkg/cmd/root.go:47 +0x45
main.main()
        /Users/hobbit/git/galasa/cli/cmd/galasactl/main.go:14 +0x17

2023/06/15 15:38:21 GAL1058E: Failed to load bootstrap file 'file:///C:/temp/GLTest/GLHOME/bootstrap.properties'. Reason is 'GAL1055E: Failed to read bootstrap file '/C:/temp/GLTest/GLHOME/bootstrap.properties'. Reason is 'GAL1043E: Failed to open file '/C:/temp/GLTest/GLHOME/bootstrap.properties' for reading. Reason is 'open /C:/temp/GLTest/GLHOME/bootstrap.properties: The filename, directory name, or volume label syntax is incorrect.'. Check that you have permissions to read the file and try again.''
GAL1058E: Failed to load bootstrap file 'file:///C:/temp/GLTest/GLHOME/bootstrap.properties'. Reason is 'GAL1055E: Failed to read bootstrap file '/C:/temp/GLTest/GLHOME/bootstrap.properties'. Reason is 'GAL1043E: Failed to open file '/C:/temp/GLTest/GLHOME/bootstrap.properties' for reading. Reason is 'open /C:/temp/GLTest/GLHOME/bootstrap.properties: The filename, directory name, or volume label syntax is incorrect.'. Check that you have permissions to read the file and try again.''
2023/06/15 15:38:21 Exit code is 1
```

... so it looks like the file name '/C:/temp/GLTest/GLHOME/bootstrap.properties' has one extra leading '/' character...

**Comment by techcobweb** [comment]
Marking with 'adoption' label and high priority because Chris Atkinson from IBM had a problem with this, and it will be a common issue.

**Comment by techcobweb** [comment]
You may be able to work around this by using the --boostrap parameter explicitly. (Not tried that yet).

**Comment by techcobweb** [comment]
>Andy Farrell
I noticed today that the following parm worked:  --bootstrap file://c/:/Users/1A5600897/.galasa/bootstrap.properties

> Andy Farrell
but --bootstrap [file:///C](file://c/):/Users/1A5600897/.galasa/bootstrap.properties ... gave the I can't read the file error.

So that's a workaround for now, though it shouldn't be necessary.

**Comment by Wyvinar** [comment]
Made changes with Savvas so should work, however needs testing. Working on Fiona-holly-1502--bootstrap-windows.
