### ISSUE TITLE
CLI: Local tests failing due to NullPointerException in framework properties reading code.

### ISSUE THREAD

**Issue by techcobweb** [galasa-dev/projectmanagement#1533]
Local test runs, then fails to launch...

```
Caused by: dev.galasa.framework.TestRunException: Unable to initialise the Framework Services
	at dev.galasa.framework.TestRunner.runTest(TestRunner.java:111)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at dev.galasa.boot.felix.FelixFramework.runTest(FelixFramework.java:235)
	... 2 more
Caused by: java.lang.NullPointerException
	at dev.galasa.framework.internal.ras.directory.DirectoryResultArchiveStoreRegistration.initialise(DirectoryResultArchiveStoreRegistration.java:50)
2023/07/19 14:37:48 JVM output: (runid:L1) : at dev.galasa.framework.FrameworkInitialisation.initialiseResultsArchiveStore(FrameworkInitialisation.java:621)
	at dev.galasa.framework.FrameworkInitialisation.<init>(FrameworkInitialisation.java:132)
	at dev.galasa.framework.FrameworkInitialisation.<init>(FrameworkInitialisation.java:55)
	at dev.galasa.framework.TestRunner.runTest(TestRunner.java:105)
	... 7 more
```

**Comment by techcobweb** [comment]
The problem was in the recently changed FrameworkInitialiser code.
Fixed now I believe.
