### ISSUE TITLE
Zos3270LocalJava11Ubuntu Unable to find a field containing 'CICS FOR GALASA TEST'

### ISSUE THREAD

**Issue by techcobweb** [galasa-dev/projectmanagement#1548]
## Bug

Test failed.

```
>../bin/galasactl-darwin-arm64 runs get --name C12569 --format details
name           : C12569
status         : finished
result         : Failed
submitted-time : 2023-08-16 06:00:34
start-time     : 2023-08-16 06:04:12
end-time       : 2023-08-16 06:07:51
duration(ms)   : 218496
test-name      : dev.galasa.inttests.zos3270.local.Zos3270LocalJava11Ubuntu
requestor      : unknown
bundle         : dev.galasa.inttests
run-log        : http://galasa-cicsk8s.hursley.ibm.com/ras/runs/cdb-4c39dc907c2f641e5b45d4fd3314a5ad/runlog

method             type        status   result start-time          end-time            duration(ms)
setupRunID         BeforeClass finished Passed 2023-08-16 06:05:38 2023-08-16 06:05:38 50
testZos3270IvtTest Test        finished Failed 2023-08-16 06:05:38 2023-08-16 06:07:48 130797

Total:1 Failed:1
```

The test itself stands up a Galasa ecosystem and calls a test inside it.

The outer test run log fails like this:
```
16/08/2023 06:05:38.135 INFO  main dev.galasa.framework.GenericMethodWrapper.invoke - Starting
----------------------- ****************************************************************************************************
----------------------- *** Start of test method dev.galasa.inttests.zos3270.local.Zos3270LocalJava11Ubuntu#testZos3270IvtTest,type=Test
----------------------- ****************************************************************************************************
16/08/2023 06:05:38.155 TRACE main dev.galasa.ipnetwork.spi.SSHClient.issueCommand - Issuing 'sh /home/galasa21/galasaconfig/galasaboot.sh'
16/08/2023 06:05:44.317 INFO  main dev.galasa.galasaecosystem.internal.LocalLinuxEcosystemImpl.submitRun - Submitted test run with run name of TESTGA1
16/08/2023 06:06:40.302 DEBUG GalasaSSHClient timeout thread dev.galasa.ipnetwork.spi.SSHClient.run - SSH Client unused after 60000 milliseconds, freeing session
16/08/2023 06:07:48.932 INFO  main dev.galasa.framework.GenericMethodWrapper.invoke - Ending
----------------------- ****************************************************************************************************
----------------------- *** Failed - Test method dev.galasa.inttests.zos3270.local.Zos3270LocalJava11Ubuntu#testZos3270IvtTest,type=Test
----------------------- ****************************************************************************************************
java.lang.AssertionError: [The test indicates the test passes] 
Expecting:
 <"Failed">
to be equal to:
 <"Passed">
but was not.
	at dev.galasa.inttests.zos3270.AbstractZos3270Local.testZos3270IvtTest(AbstractZos3270Local.java:48)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
```

The 'inner' test fails like this:
```
=| WINMVS2D VAMP         HIT ENTER FOR LATEST STATUS    SCREEN  IYCXTC12/         |
=|             IBM INTERNAL SYSTEMS MUST BE USED FOR IBM BUSINESS ONLY            |
=|                        07:05, WEDNESDAY , AUGUST    16, 2023                   |
=| SERVICE   STATUS         | SERVICE   STATUS         | SERVICE   STATUS         |
=|................................................................................|
=| MVSQTSO    UP    07:18   | MVS2CVMP   UP    07:18   |                          |
=| MVS26TSO   UP    07:18   | MVS2GVMP   UP    07:23   |                          |
=| MVS27TSO   UP    10:08   | MVS2HVMP   UP    07:23   |                          |
=| MVS28TSO   UP    07:18   | MVS2IVMP   UP    07:28   |                          |
=| MVS29TSO   UP    07:18   |                          |                          |
=| MVS2CTSO   UP    07:18   |                          |                          |
=| MVS2DTSO   UP    07:18   |                          |                          |
=| MVS2GTSO   UP    07:23   |                          |                          |
=| MVS2HTSO   UP    07:23   |                          |                          |
=| MVS2ITSO   UP    07:28   |                          |                          |
=| MVS26VMP   UP    07:18   |                          |                          |
=| MVS27VMP   UP    10:08   |                          |                          |
=| MVS28VMP   UP    07:18   |                          |                          |
=| MVS29VMP   UP    07:18   |                          |                          |
=|................................................................................|
=|  TYPE  SERVICE  AS SHOWN ABOVE FOR CONNECTION  - USE PF KEYS FOR OTHER MENUS   |
=|                     HELP ? FOR HELP OR  LOGOFF  TO LOGOFF.                     |
=| VAMP152  CLSDST/PASS TO IYK2ZNB5 FAILED, RTNCD=1000 , SENSE=087D               |
=|==> logon applid(IYK2ZNB5)                                                      |
^|                          ^
!| Connected-Plain Size=24x80 Cursor=1866,24x26 Keyboard Unlocked

16/08/2023 06:07:47.430 INFO  main dev.galasa.framework.GenericMethodWrapper.invoke - Ending
----------------------- ****************************************************************************************************
----------------------- *** Failed - Test method dev.galasa.zos3270.manager.ivt.Zos3270IVT#logon,type=Test
----------------------- ****************************************************************************************************
dev.galasa.zos3270.TextNotFoundException: Unable to find a field containing 'CICS FOR GALASA TEST'
```

**Comment by techcobweb** [comment]
inner run log: 
[run.log](https://github.com/galasa-dev/projectmanagement/files/12370538/run.log)


outer run log: 
[run.log](https://github.com/galasa-dev/projectmanagement/files/12370536/run.log)


All the files in RAS:
[C12569.zip](https://github.com/galasa-dev/projectmanagement/files/12370547/C12569.zip)

**Comment by techcobweb** [comment]
@eamansour tells me that the "VAMP152  CLSDST/PASS TO IYK2ZNB5 FAILED" error is due to @hobbit1983 's partition/application not being stood up properly.

We are still reliant on this. Seems to happen a lot. What are our options for preventing this in future ?
