### ISSUE TITLE
RegressionRuns: Tests fail due to a need to write exception

### ISSUE THREAD

**Issue by KirbyKatcher** [galasa-dev/projectmanagement#1776]

**Comment by KirbyKatcher** [comment]
example log for run C21363

```
22/02/2024 09:49:33.292 WARN  d.g.g.i.LocalLinuxEcosystemImpl - Failed to save the local ecosystem CPS
java.lang.UnsupportedOperationException: need to write
	at dev.galasa.ipnetwork.internal.ssh.filesystem.SSHFileSystemProvider.copy(SSHFileSystemProvider.java:97) ~[?:?]
	at java.nio.file.Files.copy(Files.java:1295) ~[?:?]
	at dev.galasa.galasaecosystem.internal.LocalEcosystemImpl.saveArtifactFile(LocalEcosystemImpl.java:480) [-1708595227946:?]
	at dev.galasa.galasaecosystem.internal.LocalEcosystemImpl.discard(LocalEcosystemImpl.java:545) [-1708595227946:?]
	at dev.galasa.galasaecosystem.internal.LocalLinuxEcosystemImpl.discard(LocalLinuxEcosystemImpl.java:88) [-1708595227946:?]
	at dev.galasa.galasaecosystem.internal.GalasaEcosystemManagerImpl.provisionDiscard(GalasaEcosystemManagerImpl.java:521) [-1708595227946:?]
	at dev.galasa.framework.TestRunManagers.provisionDiscard(TestRunManagers.java:516) [-1708595221153:?]
	at dev.galasa.framework.TestRunner.discardEnvironment(TestRunner.java:538) [-1708595221153:?]
	at dev.galasa.framework.TestRunner.createEnvironment(TestRunner.java:530) [-1708595221153:?]
	at dev.galasa.framework.TestRunner.generateEnvironment(TestRunner.java:485) [-1708595221153:?]
	at dev.galasa.framework.TestRunner.runTest(TestRunner.java:416) [-1708595221153:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at dev.galasa.boot.felix.FelixFramework.runTest(FelixFramework.java:233) [boot.jar:?]
	at dev.galasa.boot.Launcher.launch(Launcher.java:176) [boot.jar:?]
	at dev.galasa.boot.Launcher.main(Launcher.java:126) [boot.jar:?]
java.lang.UnsupportedOperationException: need to write
	at dev.galasa.ipnetwork.internal.ssh.filesystem.SSHFileSystemProvider.copy(SSHFileSystemProvider.java:97) ~[?:?]
	at java.nio.file.Files.copy(Files.java:1295) ~[?:?]
	at dev.galasa.galasaecosystem.internal.LocalEcosystemImpl.saveArtifactFile(LocalEcosystemImpl.java:480) [-1708595227946:?]
	at dev.galasa.galasaecosystem.internal.LocalEcosystemImpl.discard(LocalEcosystemImpl.java:545) [-1708595227946:?]
	at dev.galasa.galasaecosystem.internal.LocalLinuxEcosystemImpl.discard(LocalLinuxEcosystemImpl.java:88) [-1708595227946:?]
	at dev.galasa.galasaecosystem.internal.GalasaEcosystemManagerImpl.provisionDiscard(GalasaEcosystemManagerImpl.java:521) [-1708595227946:?]
	at dev.galasa.framework.TestRunManagers.provisionDiscard(TestRunManagers.java:516) [-1708595221153:?]
	at dev.galasa.framework.TestRunner.discardEnvironment(TestRunner.java:538) [-1708595221153:?]
	at dev.galasa.framework.TestRunner.createEnvironment(TestRunner.java:530) [-1708595221153:?]
	at dev.galasa.framework.TestRunner.generateEnvironment(TestRunner.java:485) [-1708595221153:?]
	at dev.galasa.framework.TestRunner.runTest(TestRunner.java:416) [-1708595221153:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at dev.galasa.boot.felix.FelixFramework.runTest(FelixFramework.java:233) [boot.jar:?]
	at dev.galasa.boot.Launcher.launch(Launcher.java:176) [boot.jar:?]
	at dev.galasa.boot.Launcher.main(Launcher.java:126) [boot.jar:?]
22/02/2024 09:49:33.312 WARN  d.g.g.i.LocalLinuxEcosystemImpl - Failed to save the local ecosystem DSS
java.lang.UnsupportedOperationException: need to write
	at dev.galasa.ipnetwork.internal.ssh.filesystem.SSHFileSystemProvider.copy(SSHFileSystemProvider.java:97) ~[?:?]
	at java.nio.file.Files.copy(Files.java:1295) ~[?:?]
	at dev.galasa.galasaecosystem.internal.LocalEcosystemImpl.saveArtifactFile(LocalEcosystemImpl.java:480) [-1708595227946:?]
	at dev.galasa.galasaecosystem.internal.LocalEcosystemImpl.discard(LocalEcosystemImpl.java:546) [-1708595227946:?]
	at dev.galasa.galasaecosystem.internal.LocalLinuxEcosystemImpl.discard(LocalLinuxEcosystemImpl.java:88) [-1708595227946:?]
	at dev.galasa.galasaecosystem.internal.GalasaEcosystemManagerImpl.provisionDiscard(GalasaEcosystemManagerImpl.java:521) [-1708595227946:?]
	at dev.galasa.framework.TestRunManagers.provisionDiscard(TestRunManagers.java:516) [-1708595221153:?]
	at dev.galasa.framework.TestRunner.discardEnvironment(TestRunner.java:538) [-1708595221153:?]
	at dev.galasa.framework.TestRunner.createEnvironment(TestRunner.java:530) [-1708595221153:?]
	at dev.galasa.framework.TestRunner.generateEnvironment(TestRunner.java:485) [-1708595221153:?]
	at dev.galasa.framework.TestRunner.runTest(TestRunner.java:416) [-1708595221153:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at dev.galasa.boot.felix.FelixFramework.runTest(FelixFramework.java:233) [boot.jar:?]
	at dev.galasa.boot.Launcher.launch(Launcher.java:176) [boot.jar:?]
	at dev.galasa.boot.Launcher.main(Launcher.java:126) [boot.jar:?]
java.lang.UnsupportedOperationException: need to write
	at dev.galasa.ipnetwork.internal.ssh.filesystem.SSHFileSystemProvider.copy(SSHFileSystemProvider.java:97) ~[?:?]
	at java.nio.file.Files.copy(Files.java:1295) ~[?:?]
	at dev.galasa.galasaecosystem.internal.LocalEcosystemImpl.saveArtifactFile(LocalEcosystemImpl.java:480) [-1708595227946:?]
	at dev.galasa.galasaecosystem.internal.LocalEcosystemImpl.discard(LocalEcosystemImpl.java:546) [-1708595227946:?]
	at dev.galasa.galasaecosystem.internal.LocalLinuxEcosystemImpl.discard(LocalLinuxEcosystemImpl.java:88) [-1708595227946:?]
	at dev.galasa.galasaecosystem.internal.GalasaEcosystemManagerImpl.provisionDiscard(GalasaEcosystemManagerImpl.java:521) [-1708595227946:?]
	at dev.galasa.framework.TestRunManagers.provisionDiscard(TestRunManagers.java:516) [-1708595221153:?]
	at dev.galasa.framework.TestRunner.discardEnvironment(TestRunner.java:538) [-1708595221153:?]
	at dev.galasa.framework.TestRunner.createEnvironment(TestRunner.java:530) [-1708595221153:?]
	at dev.galasa.framework.TestRunner.generateEnvironment(TestRunner.java:485) [-1708595221153:?]
	at dev.galasa.framework.TestRunner.runTest(TestRunner.java:416) [-1708595221153:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at dev.galasa.boot.felix.FelixFramework.runTest(FelixFramework.java:233) [boot.jar:?]
	at dev.galasa.boot.Launcher.launch(Launcher.java:176) [boot.jar:?]
	at dev.galasa.boot.Launcher.main(Launcher.java:126) [boot.jar:?]
22/02/2024 09:49:33.376 WARN  d.g.g.i.LocalLinuxEcosystemImpl - Failed to save the local ecosystem Overrides
java.lang.UnsupportedOperationException: need to write
	at dev.galasa.ipnetwork.internal.ssh.filesystem.SSHFileSystemProvider.copy(SSHFileSystemProvider.java:97) ~[?:?]
	at java.nio.file.Files.copy(Files.java:1295) ~[?:?]
	at dev.galasa.galasaecosystem.internal.LocalEcosystemImpl.saveArtifactFile(LocalEcosystemImpl.java:480) [-1708595227946:?]
	at dev.galasa.galasaecosystem.internal.LocalEcosystemImpl.discard(LocalEcosystemImpl.java:547) [-1708595227946:?]
	at dev.galasa.galasaecosystem.internal.LocalLinuxEcosystemImpl.discard(LocalLinuxEcosystemImpl.java:88) [-1708595227946:?]
	at dev.galasa.galasaecosystem.internal.GalasaEcosystemManagerImpl.provisionDiscard(GalasaEcosystemManagerImpl.java:521) [-1708595227946:?]
	at dev.galasa.framework.TestRunManagers.provisionDiscard(TestRunManagers.java:516) [-1708595221153:?]
	at dev.galasa.framework.TestRunner.discardEnvironment(TestRunner.java:538) [-1708595221153:?]
	at dev.galasa.framework.TestRunner.createEnvironment(TestRunner.java:530) [-1708595221153:?]
	at dev.galasa.framework.TestRunner.generateEnvironment(TestRunner.java:485) [-1708595221153:?]
	at dev.galasa.framework.TestRunner.runTest(TestRunner.java:416) [-1708595221153:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at dev.galasa.boot.felix.FelixFramework.runTest(FelixFramework.java:233) [boot.jar:?]
	at dev.galasa.boot.Launcher.launch(Launcher.java:176) [boot.jar:?]
	at dev.galasa.boot.Launcher.main(Launcher.java:126) [boot.jar:?]
java.lang.UnsupportedOperationException: need to write
	at dev.galasa.ipnetwork.internal.ssh.filesystem.SSHFileSystemProvider.copy(SSHFileSystemProvider.java:97) ~[?:?]
	at java.nio.file.Files.copy(Files.java:1295) ~[?:?]
	at dev.galasa.galasaecosystem.internal.LocalEcosystemImpl.saveArtifactFile(LocalEcosystemImpl.java:480) [-1708595227946:?]
	at dev.galasa.galasaecosystem.internal.LocalEcosystemImpl.discard(LocalEcosystemImpl.java:547) [-1708595227946:?]
	at dev.galasa.galasaecosystem.internal.LocalLinuxEcosystemImpl.discard(LocalLinuxEcosystemImpl.java:88) [-1708595227946:?]
	at dev.galasa.galasaecosystem.internal.GalasaEcosystemManagerImpl.provisionDiscard(GalasaEcosystemManagerImpl.java:521) [-1708595227946:?]
	at dev.galasa.framework.TestRunManagers.provisionDiscard(TestRunManagers.java:516) [-1708595221153:?]
	at dev.galasa.framework.TestRunner.discardEnvironment(TestRunner.java:538) [-1708595221153:?]
	at dev.galasa.framework.TestRunner.createEnvironment(TestRunner.java:530) [-1708595221153:?]
	at dev.galasa.framework.TestRunner.generateEnvironment(TestRunner.java:485) [-1708595221153:?]
	at dev.galasa.framework.TestRunner.runTest(TestRunner.java:416) [-1708595221153:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at dev.galasa.boot.felix.FelixFramework.runTest(FelixFramework.java:233) [boot.jar:?]
	at dev.galasa.boot.Launcher.launch(Launcher.java:176) [boot.jar:?]
	at dev.galasa.boot.Launcher.main(Launcher.java:126) [boot.jar:?]
```
