### ISSUE TITLE
Bug: Internal Server error on `/api/cps/namespace`

### ISSUE THREAD

**Issue by techcobweb** [galasa-dev/projectmanagement#1835]
# To reproduce
Use this url against an ecosystem... `.../api/cps/namespace`
And we get an internal server exception with stack trace and everything.
```
>curl -X GET -H "Authorization: Bearer $GALASA_JWT" https://galasa-ecosystem1.galasa.dev/api/cps/namespace
<html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=ISO-8859-1"/>
<title>Error 500 Server Error</title>
</head>
<body><h2>HTTP ERROR 500 Server Error</h2>
<table>
<tr><th>URI:</th><td>/cps/namespace</td></tr>
<tr><th>STATUS:</th><td>500</td></tr>
<tr><th>MESSAGE:</th><td>Server Error</td></tr>
<tr><th>SERVLET:</th><td>org.apache.felix.http.base.internal.dispatch.DispatcherServlet-19f21b6b</td></tr>
<tr><th>CAUSED BY:</th><td>java.lang.NullPointerException</td></tr>
</table>
<h3>Caused by:</h3><pre>java.lang.NullPointerException
        at java.base/java.util.regex.Matcher.getTextLength(Matcher.java:1770)
        at java.base/java.util.regex.Matcher.reset(Matcher.java:416)
        at java.base/java.util.regex.Matcher.&lt;init&gt;(Matcher.java:253)
        at java.base/java.util.regex.Pattern.matcher(Pattern.java:1133)
        at dev.galasa.framework.api.cps.internal.AccessCps.doGet(AccessCps.java:102)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:655)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:764)
        at org.apache.felix.http.base.internal.jakartawrappers.ServletWrapper.service(ServletWrapper.java:74)
        at org.apache.felix.http.base.internal.handler.ServletHandler.handle(ServletHandler.java:127)
        at org.apache.felix.http.base.internal.dispatch.InvocationChain.doFilter(InvocationChain.java:86)
        at org.apache.felix.http.base.internal.javaxwrappers.FilterChainWrapper.doFilter(FilterChainWrapper.java:45)
        at dev.galasa.framework.api.authentication.JwtAuthFilter.doFilter(JwtAuthFilter.java:104)
        at org.apache.felix.http.base.internal.jakartawrappers.FilterWrapper.doFilter(FilterWrapper.java:58)
        at org.apache.felix.http.base.internal.handler.FilterHandler.handle(FilterHandler.java:145)
        at org.apache.felix.http.base.internal.dispatch.InvocationChain.doFilter(InvocationChain.java:81)
        at org.apache.felix.http.base.internal.dispatch.Dispatcher$1.doFilter(Dispatcher.java:153)
        at org.apache.felix.http.base.internal.whiteboard.WhiteboardManager.invokePreprocessors(WhiteboardManager.java:930)
        at org.apache.felix.http.base.internal.dispatch.Dispatcher.dispatch(Dispatcher.java:95)
        at org.apache.felix.http.base.internal.dispatch.DispatcherServlet.service(DispatcherServlet.java:49)
        at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:587)
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:764)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:529)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:221)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1570)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:221)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1380)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:176)
```

The following works:
```
>curl -X GET -H "Authorization: Bearer $GALASA_JWT" https://galasa-ecosystem1.galasa.dev/api/cps/namespace/
[
  "mcobbett",
  "framework",
  "dex"
]%    
```

The problem should never happen. Never should we return a stack trace on an HTTP request.

The bug is that final slash appears to be needed, if missing it provokes this error.

**Comment by KirbyKatcher** [comment]
That is not a valid url endpoint  as the endpoint being hit is `cps/` in thie example. I will update the regex to ensure it doesn't match the extra `namespace`
