### ISSUE TITLE
Failure to build CLI main branch

### ISSUE THREAD

**Issue by techcobweb** [galasa-dev/projectmanagement#1839]
# Bug
The current main branch of CLI fails to build !

# Symptoms
```
2024/04/22 15:38:46 JVM output: 22/04/2024 15:38:46.709 ERROR dev.galasa.boot.Launcher.launch - Unable to run test class
2024/04/22 15:38:46 JVM output: 
2024/04/22 15:38:46 JVM output: dev.galasa.boot.LauncherException: Unable to create and initialize Felix framework
2024/04/22 15:38:46 JVM output: 
2024/04/22 15:38:46 JVM output: at dev.galasa.boot.Launcher.buildFramework([Launcher.java:221](http://launcher.java:221/))
2024/04/22 15:38:46 JVM output: 
2024/04/22 15:38:46 JVM output: at dev.galasa.boot.Launcher.launch([Launcher.java:160](http://launcher.java:160/))
2024/04/22 15:38:46 JVM output: 
2024/04/22 15:38:46 JVM output: at dev.galasa.boot.Launcher.main([Launcher.java:126](http://launcher.java:126/))
2024/04/22 15:38:46 JVM output: 
2024/04/22 15:38:46 JVM output: Caused by: dev.galasa.boot.LauncherException: Unable to initialise the Felix framework
2024/04/22 15:38:46 JVM output: 
2024/04/22 15:38:46 JVM output: at dev.galasa.boot.felix.FelixFramework.buildFramework([FelixFramework.java:146](http://felixframework.java:146/))
2024/04/22 15:38:46 JVM output: 
2024/04/22 15:38:46 JVM output: at dev.galasa.boot.Launcher.buildFramework([Launcher.java:218](http://launcher.java:218/))
2024/04/22 15:38:46 JVM output: 
2024/04/22 15:38:46 JVM output: ... 2 more
2024/04/22 15:38:46 JVM output: 
2024/04/22 15:38:46 JVM output: Caused by: org.apache.commons.io.IOExceptionList: /root/.galasa/felix-cache
2024/04/22 15:38:46 JVM output: 
2024/04/22 15:38:46 JVM output: at org.apache.commons.io.FileUtils.cleanDirectory([FileUtils.java:330](http://fileutils.java:330/))
2024/04/22 15:38:46 JVM output: 
2024/04/22 15:38:46 JVM output: at org.apache.commons.io.FileUtils.deleteDirectory([FileUtils.java:1191](http://fileutils.java:1191/))
2024/04/22 15:38:46 JVM output: 
2024/04/22 15:38:46 JVM output: at dev.galasa.boot.felix.FelixFramework.buildFramework([FelixFramework.java:83](http://felixframework.java:83/))
2024/04/22 15:38:46 JVM output: 
2024/04/22 15:38:46 JVM output: ... 3 more
2024/04/22 15:38:46 JVM output: 
2024/04/22 15:38:46 JVM output: Caused by: java.io.IOException: Cannot delete file: /root/.galasa/felix-cache/bundle22
2024/04/22 15:38:46 JVM output: 
2024/04/22 15:38:46 JVM output: at org.apache.commons.io.FileUtils.forceDelete([FileUtils.java:1343](http://fileutils.java:1343/))
2024/04/22 15:38:46 JVM output: 
2024/04/22 15:38:46 JVM output: at org.apache.commons.io.FileUtils.cleanDirectory([FileUtils.java:323](http://fileutils.java:323/))
2024/04/22 15:38:46 JVM output: 
2024/04/22 15:38:46 JVM output: ... 5 more
2024/04/22 15:38:46 JVM output: 
2024/04/22 15:38:46 JVM output: Caused by: java.nio.file.NoSuchFileException: /root/.galasa/felix-cache/bundle22/version0.0
2024/04/22 15:38:46 JVM output: 
2024/04/22 15:38:46 JVM output: at java.base/sun.nio.fs.UnixException.translateToIOException([UnixException.java:92](http://unixexception.java:92/))
2024/04/22 15:38:46 JVM output: 
2024/04/22 15:38:46 JVM output: at java.base/sun.nio.fs.UnixException.rethrowAsIOException([UnixException.java:111](http://unixexception.java:111/))
2024/04/22 15:38:46 JVM output: 
2024/04/22 15:38:46 JVM output: at java.base/sun.nio.fs.UnixException.rethrowAsIOException([UnixException.java:116](http://unixexception.java:116/))
2024/04/22 15:38:46 JVM output: 
2024/04/22 15:38:46 JVM output: at java.base/sun.nio.fs.UnixFileSystemProvider.newDirectoryStream([UnixFileSystemProvider.java:432](http://unixfilesystemprovider.java:432/))
2024/04/22 15:38:46 JVM output: 
2024/04/22 15:38:46 JVM output: at java.base/java.nio.file.Files.newDirectoryStream([Files.java:472](http://files.java:472/))
2024/04/22 15:38:46 JVM output: 
2024/04/22 15:38:46 JVM output: at org.apache.commons.io.file.PathUtils.isEmptyDirectory([PathUtils.java:763](http://pathutils.java:763/))
2024/04/22 15:38:46 JVM output: 
2024/04/22 15:38:46 JVM output: at org.apache.commons.io.file.DeletingPathVisitor.postVisitDirectory([DeletingPathVisitor.java:141](http://deletingpathvisitor.java:141/))
2024/04/22 15:38:46 JVM output: 
2024/04/22 15:38:46 JVM output: at org.apache.commons.io.file.DeletingPathVisitor.postVisitDirectory([DeletingPathVisitor.java:37](http://deletingpathvisitor.java:37/))
2024/04/22 15:38:46 JVM output: 
2024/04/22 15:38:46 JVM output: at java.base/java.nio.file.Files.walkFileTree([Files.java:2743](http://files.java:2743/))
2024/04/22 15:38:46 JVM output: 
2024/04/22 15:38:46 JVM output: at java.base/java.nio.file.Files.walkFileTree([Files.java:2797](http://files.java:2797/))
2024/04/22 15:38:46 JVM output: 
2024/04/22 15:38:46 JVM output: at org.apache.commons.io.file.PathUtils.visitFileTree([PathUtils.java:976](http://pathutils.java:976/))
2024/04/22 15:38:46 JVM output: 
2024/04/22 15:38:46 JVM output: at org.apache.commons.io.file.PathUtils.deleteDirectory([PathUtils.java:434](http://pathutils.java:434/))
2024/04/22 15:38:46 JVM output: 
2024/04/22 15:38:46 JVM output: at org.apache.commons.io.file.PathUtils.delete([PathUtils.java:391](http://pathutils.java:391/))
2024/04/22 15:38:46 JVM output: 
2024/04/22 15:38:46 JVM output: at org.apache.commons.io.FileUtils.forceDelete([FileUtils.java:1340](http://fileutils.java:1340/))
2024/04/22 15:38:46 JVM output: 
2024/04/22 15:38:46 JVM output: ... 6 more
2024/04/22 15:38:46 JVM output: 
2024/04/22 15:38:46 JVM output: 22/04/2024 15:38:46.721 DEBUG dev.galasa.boot.felix.FelixFramework.stopFramework - Stopping Felix framework
2024/04/22 15:38:46 JVM output: 
2024/04/22 15:38:46 JVM output: 22/04/2024 15:38:46.722 ERROR dev.galasa.boot.Launcher.main - Exiting launcher due to exception
2024/04/22 15:38:46 JVM output: 
2024/04/22 15:38:46 JVM output: dev.galasa.boot.LauncherException: Unable to create and initialize Felix framework
2024/04/22 15:38:46 JVM output: 
2024/04/22 15:38:46 JVM output: at dev.galasa.boot.Launcher.buildFramework([Launcher.java:221](http://launcher.java:221/))
2024/04/22 15:38:46 JVM output: 
2024/04/22 15:38:46 JVM output: at dev.galasa.boot.Launcher.launch([Launcher.java:160](http://launcher.java:160/))
2024/04/22 15:38:46 JVM output: 
2024/04/22 15:38:46 JVM output: at dev.galasa.boot.Launcher.main([Launcher.java:126](http://launcher.java:126/))
2024/04/22 15:38:46 JVM output: 
2024/04/22 15:38:46 JVM output: Caused by: dev.galasa.boot.LauncherException: Unable to initialise the Felix framework
2024/04/22 15:38:46 JVM output: 
2024/04/22 15:38:46 JVM output: at dev.galasa.boot.felix.FelixFramework.buildFramework([FelixFramework.java:146](http://felixframework.java:146/))
2024/04/22 15:38:46 JVM output: 
2024/04/22 15:38:46 JVM output: at dev.galasa.boot.Launcher.buildFramework([Launcher.java:218](http://launcher.java:218/))
2024/04/22 15:38:46 JVM output: 
2024/04/22 15:38:46 JVM output: ... 2 more
2024/04/22 15:38:46 JVM output: 
2024/04/22 15:38:46 JVM output: Caused by: org.apache.commons.io.IOExceptionList: /root/.galasa/felix-cache
2024/04/22 15:38:46 JVM output: 
2024/04/22 15:38:46 JVM output: at org.apache.commons.io.FileUtils.cleanDirectory([FileUtils.java:330](http://fileutils.java:330/))
2024/04/22 15:38:46 JVM output: 
2024/04/22 15:38:46 JVM output: at org.apache.commons.io.FileUtils.deleteDirectory([FileUtils.java:1191](http://fileutils.java:1191/))
2024/04/22 15:38:46 JVM output: 
2024/04/22 15:38:46 JVM output: at dev.galasa.boot.felix.FelixFramework.buildFramework([FelixFramework.java:83](http://felixframework.java:83/))
2024/04/22 15:38:46 JVM output: 
2024/04/22 15:38:46 JVM output: ... 3 more
2024/04/22 15:38:46 JVM output: 
2024/04/22 15:38:46 JVM output: Caused by: java.io.IOException: Cannot delete file: /root/.galasa/felix-cache/bundle22
2024/04/22 15:38:46 JVM output: 
2024/04/22 15:38:46 JVM output: at org.apache.commons.io.FileUtils.forceDelete([FileUtils.java:1343](http://fileutils.java:1343/))
2024/04/22 15:38:46 JVM output: 
2024/04/22 15:38:46 JVM output: at org.apache.commons.io.FileUtils.cleanDirectory([FileUtils.java:323](http://fileutils.java:323/))
2024/04/22 15:38:46 JVM output: 
2024/04/22 15:38:46 JVM output: ... 5 more
2024/04/22 15:38:46 JVM output: 
2024/04/22 15:38:46 JVM output: Caused by: java.nio.file.NoSuchFileException: /root/.galasa/felix-cache/bundle22/version0.0
2024/04/22 15:38:46 JVM output: 
2024/04/22 15:38:46 JVM output: at java.base/sun.nio.fs.UnixException.translateToIOException([UnixException.java:92](http://unixexception.java:92/))
2024/04/22 15:38:46 JVM output: 
2024/04/22 15:38:46 JVM output: at java.base/sun.nio.fs.UnixException.rethrowAsIOException([UnixException.java:111](http://unixexception.java:111/))
2024/04/22 15:38:46 JVM output: 
2024/04/22 15:38:46 JVM output: at java.base/sun.nio.fs.UnixException.rethrowAsIOException([UnixException.java:116](http://unixexception.java:116/))
2024/04/22 15:38:46 JVM output: 
2024/04/22 15:38:46 JVM output: at java.base/sun.nio.fs.UnixFileSystemProvider.newDirectoryStream([UnixFileSystemProvider.java:432](http://unixfilesystemprovider.java:432/))
2024/04/22 15:38:46 JVM output: at java.base/java.nio.file.Files.newDirectoryStream([Files.java:472](http://files.java:472/))
2024/04/22 15:38:46 JVM output: 
2024/04/22 15:38:46 JVM output: at org.apache.commons.io.file.PathUtils.isEmptyDirectory([PathUtils.java:763](http://pathutils.java:763/))
2024/04/22 15:38:46 JVM output: 
2024/04/22 15:38:46 JVM output: at org.apache.commons.io.file.DeletingPathVisitor.postVisitDirectory([DeletingPathVisitor.java:141](http://deletingpathvisitor.java:141/))
2024/04/22 15:38:46 JVM output: 
2024/04/22 15:38:46 JVM output: at org.apache.commons.io.file.DeletingPathVisitor.postVisitDirectory([DeletingPathVisitor.java:37](http://deletingpathvisitor.java:37/))
2024/04/22 15:38:46 JVM output: at java.base/java.nio.file.Files.walkFileTree([Files.java:2743](http://files.java:2743/))
2024/04/22 15:38:46 JVM output: 
2024/04/22 15:38:46 JVM output: at java.base/java.nio.file.Files.walkFileTree([Files.java:2797](http://files.java:2797/))
2024/04/22 15:38:46 JVM output: at org.apache.commons.io.file.PathUtils.visitFileTree([PathUtils.java:976](http://pathutils.java:976/))
2024/04/22 15:38:46 JVM output: 
2024/04/22 15:38:46 JVM output: at org.apache.commons.io.file.PathUtils.deleteDirectory([PathUtils.java:434](http://pathutils.java:434/))
2024/04/22 15:38:46 JVM output: at org.apache.commons.io.file.PathUtils.delete([PathUtils.java:391](http://pathutils.java:391/))
2024/04/22 15:38:46 JVM output: 
2024/04/22 15:38:46 JVM output: at org.apache.commons.io.FileUtils.forceDelete([FileUtils.java:1340](http://fileutils.java:1340/))
	... 6 more
2024/04/22 15:38:46 Failed to wait for the JVM test to complete. exit status 16
2024/04/22 15:38:46 Don't have enough information to find the structure.json in the RAS folder.
2024/04/22 15:38:46 Interrupting the timing service sleeping. Test run  completed.
2024/04/22 15:38:47 Message received from JVM launch thread: DONE
2024/04/22 15:38:47 Don't have enough information to find the structure.json in the RAS folder.
2024/04/22 15:38:47 GAL1057E: The run identifier could not be detected in trace output of the child process
2024/04/22 15:38:47 goroutine 1 [running]:
[github.com/galasa-dev/cli/pkg/errors.LogStackTrace()](http://github.com/galasa-dev/cli/pkg/errors.LogStackTrace())
	/workspace/git/repo-cli-main-x7m98/cli/pkg/errors/debug.go:18 +0x39
[github.com/galasa-dev/cli/pkg/errors.NewGalasaError](http://github.com/galasa-dev/cli/pkg/errors.NewGalasaError)(0xc00013a8e0, {0x0?, 0xc000196a48?, 0x440340?})
	/workspace/git/repo-cli-main-x7m98/cli/pkg/errors/errorMessage.go:68 +0xe9
[github.com/galasa-dev/cli/pkg/launcher.(*LocalTest).waitForRunIdAllocation](http://github.com/galasa-dev/cli/pkg/launcher.(*LocalTest).waitForRunIdAllocation)(0xc000132a00, 0xc0001abb30)
	/workspace/git/repo-cli-main-x7m98/cli/pkg/launcher/localTest.go:163 +0xd8
[github.com/galasa-dev/cli/pkg/launcher.(*LocalTest).launch](http://github.com/galasa-dev/cli/pkg/launcher.(*LocalTest).launch)(0xc000132a00, {0xc0001367c0, 0x1e}, {0xc0001cb800, 0x10, 0x10})
	/workspace/git/repo-cli-main-x7m98/cli/pkg/launcher/localTest.go:96 +0x245
[github.com/galasa-dev/cli/pkg/launcher.(*JvmLauncher).SubmitTestRun](http://github.com/galasa-dev/cli/pkg/launcher.(*JvmLauncher).SubmitTestRun)(0xc0001cb700, {0xc00013c690, 0x24}, {0x9281e8, 0x1}, {0x92851c, 0x3}, {0xc000136780, 0x4}, {0x0, ...}, ...)
	/workspace/git/repo-cli-main-x7m98/cli/pkg/launcher/jvmLauncher.go:274 +0x985
[github.com/galasa-dev/cli/pkg/runs.(*Submitter).submitRun](http://github.com/galasa-dev/cli/pkg/runs.(*Submitter).submitRun)(0xc000197b10, {0xc00013c690, 0x24}, {0xc0001d8750, 0x1, 0x1}, 0x0?, 0x0?, 0x4c?, 0x0, ...)
	/workspace/git/repo-cli-main-x7m98/cli/pkg/runs/submitter.go:332 +0x3c5
[github.com/galasa-dev/cli/pkg/runs.(*Submitter).executeSubmitRuns](http://github.com/galasa-dev/cli/pkg/runs.(*Submitter).executeSubmitRuns)(0xc000197b10, {0x1e, 0x0, {0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}, {0xc00013c690, ...}, ...}, ...)
	/workspace/git/repo-cli-main-x7m98/cli/pkg/runs/submitter.go:174 +0x79c
[github.com/galasa-dev/cli/pkg/runs.(*Submitter).executePortfolio](http://github.com/galasa-dev/cli/pkg/runs.(*Submitter).executePortfolio)(0x0?, 0xc000197870?, 0x40d8e8?, {0x1e, 0x0, {0x0, 0x0}, {0x0, 0x0}, {0x0, ...}, ...})
	/workspace/git/repo-cli-main-x7m98/cli/pkg/runs/submitter.go:98 +0x91
[github.com/galasa-dev/cli/pkg/runs.(*Submitter).ExecuteSubmitRuns](http://github.com/galasa-dev/cli/pkg/runs.(*Submitter).ExecuteSubmitRuns)(0xc000100550?, 0xc0001b2000, 0xecf300?)
	/workspace/git/repo-cli-main-x7m98/cli/pkg/runs/submitter.go:76 +0x1d0
[github.com/galasa-dev/cli/pkg/cmd.(*RunsSubmitLocalCommand).executeSubmitLocal](http://github.com/galasa-dev/cli/pkg/cmd.(*RunsSubmitLocalCommand).executeSubmitLocal)(0xc00010c800, {0xed3e48, 0xc00013b660}, 0x0?, 0xc00010c5b0, 0xc000111470)
	/workspace/git/repo-cli-main-x7m98/cli/pkg/cmd/runsSubmitLocal.go:225 +0x53c
[github.com/galasa-dev/cli/pkg/cmd.(*RunsSubmitLocalCommand).createRunsSubmitLocalCobraCmd.func1](http://github.com/galasa-dev/cli/pkg/cmd.(*RunsSubmitLocalCommand).createRunsSubmitLocalCobraCmd.func1)(0xc0001c0000?, {0xc000117260?, 0x6?, 0x6?})
	/workspace/git/repo-cli-main-x7m98/cli/pkg/cmd/runsSubmitLocal.go:96 +0x85
[github.com/spf13/cobra.(*Command).execute](http://github.com/spf13/cobra.(*Command).execute)(0xc0001c0000, {0xc000117200, 0x6, 0x6})
	/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:983 +0xaaa
[github.com/spf13/cobra.(*Command).ExecuteC(0xc0001a2000)](http://github.com/spf13/cobra.(*Command).ExecuteC(0xc0001a2000))
	/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1115 +0x425
[github.com/spf13/cobra.(*Command).Execute(...)](http://github.com/spf13/cobra.(*Command).Execute(...))
	/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1039
[github.com/galasa-dev/cli/pkg/cmd.(*commandCollectionImpl).Execute](http://github.com/galasa-dev/cli/pkg/cmd.(*commandCollectionImpl).Execute)(0xc000124270?, {0xc00011c010, 0x9, 0x9})
	/workspace/git/repo-cli-main-x7m98/cli/pkg/cmd/commandCollection.go:96 +0x8b
[github.com/galasa-dev/cli/pkg/cmd.Execute](http://github.com/galasa-dev/cli/pkg/cmd.Execute)({0xed3e48, 0xc00013b660}, {0xc00011c010, 0x9, 0x9})
	/workspace/git/repo-cli-main-x7m98/cli/pkg/cmd/execute.go:28 +0x139
main.main()
	/workspace/git/repo-cli-main-x7m98/cli/cmd/galasactl/main.go:16 +0x7c

2024/04/22 15:38:47 Failed to submit test / - GAL1057E: The run identifier could not be detected in trace output of the child process
2024/04/22 15:38:47 GAL1093E: Failed to submit test (bundle: , class: ). Reason is: GAL1057E: The run identifier could not be detected in trace output of the child process
2024/04/22 15:38:47 JvmLauncher: GetRunsByGroup(groupName=8fca62ad-67f0-4da9-95b8-7bbd7366a208) entered. 
2024/04/22 15:38:47 JvmLauncher: GetRunsByGroup(groupName=8fca62ad-67f0-4da9-95b8-7bbd7366a208) exiting. isComplete:true testRuns returned:0
2024/04/22 15:38:47 GAL1093E: Failed to submit test (bundle: , class: ). Reason is: GAL1057E: The run identifier could not be detected in trace output of the child process
2024/04/22 15:38:47 Exit code is 1
GAL1093E: Failed to submit test (bundle: , class: ). Reason is: GAL1057E: The run identifier could not be detected in trace output of the child process
Error: GAL1093E: Failed to submit test (bundle: , class: ). Reason is: GAL1057E: The run identifier could not be detected in trace output of the child process
✖ Failed to run gherkin test
```

**Comment by techcobweb** [comment]
Jade took the test out which causes this issue. It will be put back under a separate issue.

**Comment by techcobweb** [comment]
Don't think this is re-creatable now. Closing.
