### ISSUE TITLE
ZosManagerFileDatasetIVT: EXEC datasets aren't being deleted after running LISTDSI EXEC

### ISSUE THREAD

**Issue by eamansour** [galasa-dev/projectmanagement#1849]
## Describe the bug
After running the zosFileDataset integration tests, we discovered that the EXEC dataset created before running a LISTDSI command doesn't get deleted once we've listed out the dataset information. This is leaving debris from past test runs, and has eventually led to IVT failures.

The error we were getting was:
```
dev.galasa.zosfile.ZosDatasetException: Unable to create LISTDSI EXEC command
	at dev.galasa.zosfile.rseapi.manager.internal.RseapiZosDatasetAttributesListdsi.initialise(RseapiZosDatasetAttributesListdsi.java:116)
	at dev.galasa.zosfile.rseapi.manager.internal.RseapiZosDatasetAttributesListdsi.get(RseapiZosDatasetAttributesListdsi.java:122)
	at dev.galasa.zosfile.rseapi.manager.internal.RseapiZosDatasetImpl.retrieveAttibutes(RseapiZosDatasetImpl.java:716)
	at dev.galasa.zos.manager.ivt.ZosManagerFileDatasetIVT.datasetAttributeCheck(ZosManagerFileDatasetIVT.java:169)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at dev.galasa.framework.GenericMethodWrapper.invoke(GenericMethodWrapper.java:88)
	at dev.galasa.framework.TestMethodWrapper.invoke(TestMethodWrapper.java:61)
	at dev.galasa.framework.TestClassWrapper.runTestMethods(TestClassWrapper.java:213)
	at dev.galasa.framework.TestRunner.runTestClassWrapper(TestRunner.java:607)
	at dev.galasa.framework.TestRunner.runEnvironment(TestRunner.java:581)
	at dev.galasa.framework.TestRunner.createEnvironment(TestRunner.java:546)
	at dev.galasa.framework.TestRunner.generateEnvironment(TestRunner.java:503)
	at dev.galasa.framework.TestRunner.runTest(TestRunner.java:424)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at dev.galasa.boot.felix.FelixFramework.runTest(FelixFramework.java:233)
	at dev.galasa.boot.Launcher.launch(Launcher.java:176)
	at dev.galasa.boot.Launcher.main(Launcher.java:126)
Caused by: dev.galasa.zosfile.ZosDatasetException: Data set "GALASA.GALASA.TESTYA1.EXEC" is not a partitioned data set
	at dev.galasa.zosfile.rseapi.manager.internal.RseapiZosDatasetImpl.memberExists(RseapiZosDatasetImpl.java:401)
	at dev.galasa.zosfile.rseapi.manager.internal.RseapiZosDatasetAttributesListdsi.createExecDataset(RseapiZosDatasetAttributesListdsi.java:369)
	at dev.galasa.zosfile.rseapi.manager.internal.RseapiZosDatasetAttributesListdsi.initialise(RseapiZosDatasetAttributesListdsi.java:113)
	... 22 more
```

For now, we can work around failures by manually deleting EXEC datasets left over from past runs.

## Steps to reproduce
1. Run any of the zosFileDataset integration tests on prod1
2. Open a 3270 terminal
3. Log on to plex 2
4. Open ISPF
5. View datasets using `GALASA.GALASA.TEST*.*`
6. See several datasets ending in `.EXEC`

## Expected behavior
No datasets should be left over after running the zosFileDataset integration tests.

## Tasks
- [ ] In the zosFile manager, delete the EXEC dataset after running the LISTDSI command
- [ ] Test to make sure that the EXEC dataset was deleted

**Comment by eamansour** [comment]
Investigated further - the EXEC datasets are being deleted at the end of the zosFile manager test runs, but occasionally for tests using the RSE API to delete the datasets, the RSE API server is returning a 500 server error:

```
07/07/2024 06:04:01.589 TRACE main dev.galasa.zosrseapi.internal.RseapiImpl.delete - Request: DELETE https://<mvs2d>/rseapi/api/v1/datasets/GALASA.GALASA.TESTHA1.EXEC
07/07/2024 06:04:01.683 TRACE main dev.galasa.zosrseapi.internal.RseapiImpl.delete - Response: HTTP/1.1 500  - DELETE https://<mvs2d>/rseapi/api/v1/datasets/GALASA.GALASA.TESTHA1.EXEC
07/07/2024 06:04:01.684 TRACE main dev.galasa.zosfile.rseapi.manager.internal.RseapiZosDatasetImpl.buildErrorString - {"error":"Internal Server Error","message":"Unable to obtain the lock owner of dataset 'GALASA.GALASA.TESTHA1.EXEC' with the error: 'JSONObject[\"lockOwner\"] not found.'","status":500,"timestamp":"2024-06-10 at 05:35:33 EDT"}
07/07/2024 06:04:01.705 ERROR main dev.galasa.zosfile.rseapi.manager.internal.RseapiZosDatasetImpl.delete - Error delete GALASA.GALASA.TESTHA1.EXEC, HTTP Status Code 500 : HTTP/1.1 500 
status: 500
message: Unable to obtain the lock owner of dataset 'GALASA.GALASA.TESTHA1.EXEC' with the error: 'JSONObject["lockOwner"] not found.'
07/07/2024 06:04:01.722 ERROR main dev.galasa.zosfile.rseapi.manager.internal.RseapiZosFileHandlerImpl.cleanupDatasets - Problem in data set cleanup phase
dev.galasa.zosfile.ZosDatasetException: Error delete GALASA.GALASA.TESTHA1.EXEC, HTTP Status Code 500 : HTTP/1.1 500 
status: 500
message: Unable to obtain the lock owner of dataset 'GALASA.GALASA.TESTHA1.EXEC' with the error: 'JSONObject["lockOwner"] not found.'
	at dev.galasa.zosfile.rseapi.manager.internal.RseapiZosDatasetImpl.delete(RseapiZosDatasetImpl.java:1007) ~[-1720332134244:?]
	at dev.galasa.zosfile.rseapi.manager.internal.RseapiZosDatasetImpl.delete(RseapiZosDatasetImpl.java:214) ~[-1720332134244:?]
	at dev.galasa.zosfile.rseapi.manager.internal.RseapiZosFileHandlerImpl.cleanupDatasets(RseapiZosFileHandlerImpl.java:120) [-1720332134244:?]
	at dev.galasa.zosfile.rseapi.manager.internal.RseapiZosFileHandlerImpl.cleanup(RseapiZosFileHandlerImpl.java:105) [-1720332134244:?]
	at dev.galasa.zosfile.rseapi.manager.internal.RseapiZosFileManagerImpl.cleanup(RseapiZosFileManagerImpl.java:253) [-1720332134244:?]
	at dev.galasa.zosfile.rseapi.manager.internal.RseapiZosFileManagerImpl.endOfTestRun(RseapiZosFileManagerImpl.java:245) [-1720332134244:?]
	at dev.galasa.framework.TestRunManagers.endOfTestRun(TestRunManagers.java:619) [-1720332129675:?]
	at dev.galasa.framework.TestRunner.runTest(TestRunner.java:438) [-1720332129675:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at dev.galasa.boot.felix.FelixFramework.runTest(FelixFramework.java:248) [galasa-boot-0.34.0.jar:?]
	at dev.galasa.boot.Launcher.launch(Launcher.java:172) [galasa-boot-0.34.0.jar:?]
	at dev.galasa.boot.Launcher.main(Launcher.java:122) [galasa-boot-0.34.0.jar:?]
dev.galasa.zosfile.ZosDatasetException: Error delete GALASA.GALASA.TESTHA1.EXEC, HTTP Status Code 500 : HTTP/1.1 500 
status: 500
message: Unable to obtain the lock owner of dataset 'GALASA.GALASA.TESTHA1.EXEC' with the error: 'JSONObject["lockOwner"] not found.'
	at dev.galasa.zosfile.rseapi.manager.internal.RseapiZosDatasetImpl.delete(RseapiZosDatasetImpl.java:1007) ~[-1720332134244:?]
	at dev.galasa.zosfile.rseapi.manager.internal.RseapiZosDatasetImpl.delete(RseapiZosDatasetImpl.java:214) ~[-1720332134244:?]
	at dev.galasa.zosfile.rseapi.manager.internal.RseapiZosFileHandlerImpl.cleanupDatasets(RseapiZosFileHandlerImpl.java:120) [-1720332134244:?]
	at dev.galasa.zosfile.rseapi.manager.internal.RseapiZosFileHandlerImpl.cleanup(RseapiZosFileHandlerImpl.java:105) [-1720332134244:?]
	at dev.galasa.zosfile.rseapi.manager.internal.RseapiZosFileManagerImpl.cleanup(RseapiZosFileManagerImpl.java:253) [-1720332134244:?]
	at dev.galasa.zosfile.rseapi.manager.internal.RseapiZosFileManagerImpl.endOfTestRun(RseapiZosFileManagerImpl.java:245) [-1720332134244:?]
	at dev.galasa.framework.TestRunManagers.endOfTestRun(TestRunManagers.java:619) [-1720332129675:?]
	at dev.galasa.framework.TestRunner.runTest(TestRunner.java:438) [-1720332129675:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at dev.galasa.boot.felix.FelixFramework.runTest(FelixFramework.java:248) [galasa-boot-0.34.0.jar:?]
	at dev.galasa.boot.Launcher.launch(Launcher.java:172) [galasa-boot-0.34.0.jar:?]
	at dev.galasa.boot.Launcher.main(Launcher.java:122) [galasa-boot-0.34.0.jar:?]
```
