### ISSUE TITLE
Selenium manager: Kubernetes driver throws "No such artifact" error

### ISSUE THREAD

**Issue by eamansour** [galasa-dev/projectmanagement#1911]
## Describe the bug
Original issue raised by an internal user:

I am trying to run selenium tests on my openshift cluster where galasa ecosystem is running.
Here are the cps properties used

```
selenium.default.driver=CHROME
selenium.driver.type=kubernetes
selenium.image.node.version=4.0.0-beta-2-20210317
selenium.driver.max.slots=1
```

However I am getting an error in the logs saying :

```
26/06/2024 06:30:18.296 INFO  d.g.f.TestRunner - Starting Provision Generate phase
26/06/2024 06:30:18.545 DEBUG d.g.a.i.BundleResourcesImpl - Searching for artifact: resources/selenium-node-deployment.yaml in bundle dev.galasa.selenium.manager
26/06/2024 06:30:18.547 INFO  d.g.f.TestRunner - Provision Generate failed
dev.galasa.framework.spi.FrameworkException: Problem in provision generate for manager dev.galasa.selenium.internal.SeleniumManagerImpl
	at dev.galasa.framework.TestRunManagers.provisionGenerate(TestRunManagers.java:482) ~[-1719383412456:?]
	at dev.galasa.framework.TestRunner.generateEnvironment(TestRunner.java:502) [-1719383412456:?]
	at dev.galasa.framework.TestRunner.runTest(TestRunner.java:424) [-1719383412456:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at dev.galasa.boot.felix.FelixFramework.runTest(FelixFramework.java:248) [boot.jar:?]
	at dev.galasa.boot.Launcher.launch(Launcher.java:172) [boot.jar:?]
	at dev.galasa.boot.Launcher.main(Launcher.java:122) [boot.jar:?]
Caused by: dev.galasa.ManagerException: Problem generating Test Class fields
	at dev.galasa.framework.spi.AbstractManager.generateAnnotatedFields(AbstractManager.java:193) ~[-1719383412456:?]
	at dev.galasa.selenium.internal.SeleniumManagerImpl.provisionGenerate(SeleniumManagerImpl.java:156) ~[?:?]
	at dev.galasa.framework.TestRunManagers.provisionGenerate(TestRunManagers.java:477) ~[-1719383412456:?]
	... 9 more
Caused by: java.lang.reflect.InvocationTargetException
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at dev.galasa.framework.spi.AbstractManager.generateAnnotatedFields(AbstractManager.java:176) ~[-1719383412456:?]
	at dev.galasa.selenium.internal.SeleniumManagerImpl.provisionGenerate(SeleniumManagerImpl.java:156) ~[?:?]
	at dev.galasa.framework.TestRunManagers.provisionGenerate(TestRunManagers.java:477) ~[-1719383412456:?]
	... 9 more
Caused by: dev.galasa.selenium.SeleniumManagerException: Unable to generate pod yaml
	at dev.galasa.selenium.internal.RemoteDriverImpl.generatePodYaml(RemoteDriverImpl.java:222) ~[?:?]
	at dev.galasa.selenium.internal.RemoteDriverImpl.provisionK8s(RemoteDriverImpl.java:152) ~[?:?]
	at dev.galasa.selenium.internal.RemoteDriverImpl.<init>(RemoteDriverImpl.java:94) ~[?:?]
	at dev.galasa.selenium.internal.SeleniumEnvironment.allocateWebDriver(SeleniumEnvironment.java:117) ~[?:?]
	at dev.galasa.selenium.internal.SeleniumManagerImpl.generateWebDriver(SeleniumManagerImpl.java:193) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at dev.galasa.framework.spi.AbstractManager.generateAnnotatedFields(AbstractManager.java:176) ~[-1719383412456:?]
	at dev.galasa.selenium.internal.SeleniumManagerImpl.provisionGenerate(SeleniumManagerImpl.java:156) ~[?:?]
	at dev.galasa.framework.TestRunManagers.provisionGenerate(TestRunManagers.java:477) ~[-1719383412456:?]
	... 9 more
Caused by: dev.galasa.artifact.TestBundleResourceException: No such artifact: resources/selenium-node-deployment.yaml in bundle dev.galasa.selenium.manager
	at dev.galasa.artifact.internal.BundleResourcesImpl.retrieveFile(BundleResourcesImpl.java:104) ~[?:?]
	at dev.galasa.artifact.internal.BundleResourcesImpl.retrieveFileAsString(BundleResourcesImpl.java:588) ~[?:?]
	at dev.galasa.selenium.internal.RemoteDriverImpl.generatePodYaml(RemoteDriverImpl.java:204) ~[?:?]
	at dev.galasa.selenium.internal.RemoteDriverImpl.provisionK8s(RemoteDriverImpl.java:152) ~[?:?]
	at dev.galasa.selenium.internal.RemoteDriverImpl.<init>(RemoteDriverImpl.java:94) ~[?:?]
	at dev.galasa.selenium.internal.SeleniumEnvironment.allocateWebDriver(SeleniumEnvironment.java:117) ~[?:?]
	at dev.galasa.selenium.internal.SeleniumManagerImpl.generateWebDriver(SeleniumManagerImpl.java:193) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at dev.galasa.framework.spi.AbstractManager.generateAnnotatedFields(AbstractManager.java:176) ~[-1719383412456:?]
	at dev.galasa.selenium.internal.SeleniumManagerImpl.provisionGenerate(SeleniumManagerImpl.java:156) ~[?:?]
	at dev.galasa.framework.TestRunManagers.provisionGenerate(TestRunManagers.java:477) ~[-1719383412456:?]
	... 9 more
```

On further inspection, the Selenium manager contains the [selenium-node-deployment.yaml](https://github.com/galasa-dev/managers/blob/main/galasa-managers-parent/galasa-managers-testingtools-parent/dev.galasa.selenium.manager/src/main/resources/selenium-node-deployment.yaml) file, and the [driver implementation](https://github.com/galasa-dev/managers/blob/294c6ef3ccde1fbb0c9b58a100dff3a0d7590b5c/galasa-managers-parent/galasa-managers-testingtools-parent/dev.galasa.selenium.manager/src/main/java/dev/galasa/selenium/internal/RemoteDriverImpl.java#L204) contains:

```java
String yaml = resources.retrieveFileAsString("resources/selenium-node-deployment.yaml");
```

[This PR](https://github.com/galasa-dev/managers/pull/811) removed the need to explicitly specify `resources` in paths when retrieving files using the Artifact manager, so it's likely that the above Selenium manager code is actually looking for `resources/resources/selenium-node-deployment.yaml`, which doesn't exist.

Based on the changes in the PR mentioned above, the above code should probably be:

```java
String yaml = resources.retrieveFileAsString("selenium-node-deployment.yaml");
```

## Tasks
- [ ] Remove the `resources` part of the `resources/selenium-node-deployment.yaml` path and any other similar paths in the Selenium manager that were not updated
- [ ] Run the Selenium IVT in an ecosystem to verify that the fix works

**Comment by techcobweb** [comment]
This looks like a duplicate of this defect: [Selenium manager screenshot artifact error #460](https://github.com/galasa-dev/projectmanagement/issues/460)
