### ISSUE TITLE
OpenStack create floating IP Bad Request

### ISSUE THREAD

**Issue by jadecarino** [galasa-dev/projectmanagement#1956]
## Describe the bug
A 400 bad request response is being returned to the Openstack Manager when trying to create a new floating IP address by sending a POST to the floatingips endpoint. A change in the HDC a couple of weeks ago means there is a new external network available and so the request object needs to specify which floating IP network it wants.

## Steps to reproduce
1. Run the DockerLocalJava11Ubuntu integration test.
2. See the run.log:
```
05/08/2024 12:56:10.124 ERROR main dev.galasa.framework.TestRunner.createEnvironment - Provision build failed
dev.galasa.framework.spi.FrameworkException: Problem in provision build for manager dev.galasa.openstack.manager.internal.OpenstackManagerImpl
	at dev.galasa.framework.TestRunManagers.provisionBuild(TestRunManagers.java:492) ~[-1722862529289:?]
	at dev.galasa.framework.TestRunner.createEnvironment(TestRunner.java:533) [-1722862529289:?]
	at dev.galasa.framework.TestRunner.generateEnvironment(TestRunner.java:506) [-1722862529289:?]
	at dev.galasa.framework.TestRunner.runTest(TestRunner.java:427) [-1722862529289:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at dev.galasa.boot.felix.FelixFramework.runTest(FelixFramework.java:248) [boot.jar:?]
	at dev.galasa.boot.Launcher.launch(Launcher.java:172) [boot.jar:?]
	at dev.galasa.boot.Launcher.main(Launcher.java:122) [boot.jar:?]
Caused by: dev.galasa.openstack.manager.OpenstackManagerException: OpenStack list image failed - HTTP/1.1 400 Bad Request
	at dev.galasa.openstack.manager.internal.OpenstackHttpClient.allocateFloatingip(OpenstackHttpClient.java:636) ~[?:?]
	at dev.galasa.openstack.manager.internal.OpenstackServerImpl.createServer(OpenstackServerImpl.java:326) ~[?:?]
	at dev.galasa.openstack.manager.internal.OpenstackLinuxImageImpl.build(OpenstackLinuxImageImpl.java:120) ~[?:?]
	at dev.galasa.openstack.manager.internal.OpenstackManagerImpl.provisionBuild(OpenstackManagerImpl.java:134) ~[?:?]
	at dev.galasa.framework.TestRunManagers.provisionBuild(TestRunManagers.java:490) ~[-1722862529289:?]
	... 10 more
```

## Expected behavior
The test should be able to create a floating IP address and pass.

## Additional context
If applicable, add screenshots or any relevant output logs to help explain your problem.

**Comment by jadecarino** [comment]
From the Openstack API docs:

> The operation returns the Bad Request (400) response code for one of reasons:

The network is not external, such as router:external=False.

The internal OpenStack Networking port is not associated with the floating IP address.

The requested floating IP address does not fall in the subnet range for the external network.

The fixed IP address is not valid.
