### ISSUE TITLE
'Read timed out' exception when sending requests to /unixcommands endpoint of RSE API

### ISSUE THREAD

**Issue by jadecarino** [galasa-dev/projectmanagement#1961]
## Describe the bug
The following inttests have been failing since Monday 5th August. Whenever requests are made to the RSE API, to the `/v1/unixcommands` endpoint specifically, we are getting back a `Read timed out` exception. Requests to other endpoints like `/v1/datasets` work okay.

- ZosFileDatasetLocalJava11UbuntuIsolatedRse, ZosFileDatasetLocalJava11UbuntuMvpRse and  ZosFileDatasetLocalJava11UbuntuRse > runs the ZosManagerFileDatasetIVT and fails in method datasetAttributeCheck
- ZosVSAMLocalJava11UbuntuIsolatedRse, ZosVSAMLocalJava11UbuntuRse and ZosVSAMLocalJava11UbuntuMvpRse > runs the ZosManagerFileVSAMIVT and fails in method basicKSDSDefine

Within these test methods, the RSE API is being sent a request to create or read details about datasets. The exception being thrown which causes the failure is below. These same tests successfully make requests to the RSE API server on the `/datasets` endpoint but any request to `/unixcommands/` fails with this exception.
```
12/08/2024 12:43:54.946 DEBUG main dev.galasa.zosrseapi.internal.RseapiRestApiProcessor.getCurrentRseapiServer - Using RSE API server on XXXX https://XXXXX
12/08/2024 12:43:54.946 TRACE main dev.galasa.zosrseapi.internal.RseapiImpl.addCommonHeaders - Adding HTTP header: accept: */*
12/08/2024 12:43:54.946 TRACE main dev.galasa.zosrseapi.internal.RseapiImpl.postJson - Request: POST https://XXXXX/rseapi/api/v1/unixcommands
12/08/2024 12:43:54.947 TRACE main dev.galasa.zosrseapi.internal.RseapiImpl.postJson - body: 
{"invocation":"tsocmd \"XXXXX","path":"/usr/bin"}
12/08/2024 12:46:55.010 ERROR main dev.galasa.zosrseapi.internal.RseapiImpl.postJson - dev.galasa.http.HttpClientException: Error executing http request
12/08/2024 12:46:55.012 ERROR main dev.galasa.zosrseapi.internal.RseapiRestApiProcessor.sendRequest - Problem with RSE API request
dev.galasa.zosrseapi.RseapiException: Problem with POST to RSE API server
	at dev.galasa.zosrseapi.internal.RseapiImpl.postJson(RseapiImpl.java:215) ~[-1723466580197:?]
	at dev.galasa.zosrseapi.internal.RseapiRestApiProcessor.sendRequest(RseapiRestApiProcessor.java:91) [-1723466580197:?]
	at dev.galasa.zosfile.rseapi.manager.internal.RseapiZosUnixCommand.execute(RseapiZosUnixCommand.java:43) [-1723466580132:?]
	at dev.galasa.zosfile.rseapi.manager.internal.RseapiZosDatasetAttributesListdsi.execListdsi(RseapiZosDatasetAttributesListdsi.java:323) [-1723466580132:?]
	at dev.galasa.zosfile.rseapi.manager.internal.RseapiZosDatasetAttributesListdsi.get(RseapiZosDatasetAttributesListdsi.java:124) [-1723466580132:?]
	at dev.galasa.zosfile.rseapi.manager.internal.RseapiZosDatasetImpl.retrieveAttibutes(RseapiZosDatasetImpl.java:716) [-1723466580132:?]
	at dev.galasa.zos.manager.ivt.ZosManagerFileDatasetIVT.datasetAttributeCheck(ZosManagerFileDatasetIVT.java:169) [-1723466578507:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at dev.galasa.framework.GenericMethodWrapper.invoke(GenericMethodWrapper.java:88) [-1723466576250:?]
	at dev.galasa.framework.TestMethodWrapper.invoke(TestMethodWrapper.java:61) [-1723466576250:?]
	at dev.galasa.framework.TestClassWrapper.runTestMethods(TestClassWrapper.java:216) [-1723466576250:?]
	at dev.galasa.framework.TestRunner.runTestClassWrapper(TestRunner.java:610) [-1723466576250:?]
	at dev.galasa.framework.TestRunner.runEnvironment(TestRunner.java:584) [-1723466576250:?]
	at dev.galasa.framework.TestRunner.createEnvironment(TestRunner.java:549) [-1723466576250:?]
	at dev.galasa.framework.TestRunner.generateEnvironment(TestRunner.java:506) [-1723466576250:?]
	at dev.galasa.framework.TestRunner.runTest(TestRunner.java:427) [-1723466576250:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at dev.galasa.boot.felix.FelixFramework.runTest(FelixFramework.java:248) [boot.jar:?]
	at dev.galasa.boot.Launcher.launch(Launcher.java:172) [boot.jar:?]
	at dev.galasa.boot.Launcher.main(Launcher.java:122) [boot.jar:?]
Caused by: dev.galasa.http.HttpClientException: Error executing http request
	at dev.galasa.http.internal.HttpClientImpl.execute(HttpClientImpl.java:864) ~[?:?]
	at dev.galasa.http.internal.HttpClientImpl.executeJsonRequest(HttpClientImpl.java:214) ~[?:?]
	at dev.galasa.http.internal.HttpClientImpl.postJson(HttpClientImpl.java:180) ~[?:?]
	at dev.galasa.zosrseapi.internal.RseapiImpl.postJson(RseapiImpl.java:208) ~[-1723466580197:?]
	... 25 more
Caused by: java.net.SocketTimeoutException: Read timed out
	at java.net.SocketInputStream.socketRead0(Native Method) ~[?:?]
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:115) ~[?:?]
	at java.net.SocketInputStream.read(SocketInputStream.java:168) ~[?:?]
	at java.net.SocketInputStream.read(SocketInputStream.java:140) ~[?:?]
	at sun.security.ssl.SSLSocketInputRecord.read(SSLSocketInputRecord.java:478) ~[?:?]
	at sun.security.ssl.SSLSocketInputRecord.readHeader(SSLSocketInputRecord.java:472) ~[?:?]
	at sun.security.ssl.SSLSocketInputRecord.bytesInCompletePacket(SSLSocketInputRecord.java:70) ~[?:?]
	at sun.security.ssl.SSLSocketImpl.readApplicationRecord(SSLSocketImpl.java:1364) ~[?:?]
	at sun.security.ssl.SSLSocketImpl$AppInputStream.read(SSLSocketImpl.java:973) ~[?:?]
	at org.apache.http.impl.io.SessionInputBufferImpl.streamRead(SessionInputBufferImpl.java:137) ~[?:?]
	at org.apache.http.impl.io.SessionInputBufferImpl.fillBuffer(SessionInputBufferImpl.java:153) ~[?:?]
	at org.apache.http.impl.io.SessionInputBufferImpl.readLine(SessionInputBufferImpl.java:280) ~[?:?]
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:138) ~[?:?]
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:56) ~[?:?]
	at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:259) ~[?:?]
	at org.apache.http.impl.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClientConnection.java:163) ~[?:?]
	at org.apache.http.impl.conn.CPoolProxy.receiveResponseHeader(CPoolProxy.java:157) ~[?:?]
	at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:273) ~[?:?]
	at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:125) ~[?:?]
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:272) ~[?:?]
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186) ~[?:?]
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89) ~[?:?]
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110) ~[?:?]
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185) ~[?:?]
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83) ~[?:?]
	at dev.galasa.http.internal.HttpClientImpl.execute(HttpClientImpl.java:862) ~[?:?]
	at dev.galasa.http.internal.HttpClientImpl.executeJsonRequest(HttpClientImpl.java:214) ~[?:?]
	at dev.galasa.http.internal.HttpClientImpl.postJson(HttpClientImpl.java:180) ~[?:?]
	at dev.galasa.zosrseapi.internal.RseapiImpl.postJson(RseapiImpl.java:208) ~[-1723466580197:?]
	... 25 more
```

## Steps to reproduce
1. Build the 'galasa' repo and the 'cli' repo.
2. Set up the CPS properties for using the z/OS Manager
3. Add into your credentials.properties the username and password we use for z/OS testing.
4. Add into your overrides.properties: `zos.bundle.extra.file.manager=dev.galasa.zosfile.rseapi.manager`
5. Run the two affected tests locally with either `galasactl runs submit local --log - \--obr mvn:dev.galasa/dev.galasa.uber.obr/0.39.0/obr \--class dev.galasa.zos.manager.ivt/dev.galasa.zos.manager.ivt.ZosManagerFileDatasetIVT --trace` or `galasactl runs submit local --log - \
--obr mvn:dev.galasa/dev.galasa.uber.obr/0.39.0/obr \
--class dev.galasa.zos.manager.ivt/dev.galasa.zos.manager.ivt.ZosManagerFileVSAMIVT --trace`

## Expected behavior
Requests to `/unixcommands` should get an OK response within a few minutes.

## Additional context
The weekend prior to the tests beginning to fail, there were some updates on Plex2 to do with TLS and ports but we haven't been able to determine if this is related or a coincidence.

## Things found so far:
- Properly configuring which RSE API server to use was never finished, and so the RSE API server is selected based on whichever the z/OS image is being used for the test. So if the test is using z/OS image A, the RSE API used will always be on image A, even if the CPS property `rseapi.sysplex.PLEX.default.servers` is pointing at B.
- The Galasa HTTP Manager is being used to send the request and the socket timeout of 3 minutes is being set in the class dev.galasa.http.internal.HttpClientImpl, and is passed from line 79 of HttpManagerImpl. I changed this in the code to timeouts of 10-minutes and the Read timed out still appeared. I then changed this to 15-minutes and the request was successful and the test could proceed.

# Update:
Requests to the `/unixcommands` endpoint do receive a response but after about 10-12 minutes so only worked when I changed the HTTP Client's socket timeout time to 15 minutes locally and ran the IVTs locally. The requests previously received responses within the 3 minutes socket timeout time so its still unclear why the requests take so long now. So it is not a problem with the endpoint, the way the request is formed or the RSE API server, but we need to figure out why the requests are now so slow, as we don't want to change the HTTP Manager in production to have a 15 minute timeout.

**Comment by techcobweb** [comment]
We think it's something wrong with the RSE deployment galasa is talking to.
It's difficult to debug, and not found any failure yet.
- Jade to chase up with her contact in Z hardware and possibly escalate the issue.

**Comment by jadecarino** [comment]
I found in the logs that the unsuccessful request is being retried 3 additional times after the first failure, which is causing the tests to be very long in length. This is because the default number of retries is set to 3 in the class dev.galasa.zosrseapi.internal.properties.RequestRetry. As we know the request is not going to succeed no matter how many times it's retried, I have now set the retries number to 0 in the prod1 CPS properties, so these tests fail faster.

**Comment by jadecarino** [comment]
Locally I set the socket timeout time in the HTTP Manager to 15 minutes, after this we did receive a response from the requests (in about 10-12 minutes). So unlike I originally thought the RSE API server is healthy, it's just taking an incredibly long time for the client to get a response back, hence the `Read timed out` exceptions when the socket timeout is set to 3-minutes.

I have sent information from my investigation to the Z Team on the OneTicket to see if they can look at the request now we know its being received and processed, and determine why it is taking 10+ minutes to send a response.
