### ISSUE TITLE
CLI - galasactl project create doesn't create a project that can be ran

### ISSUE THREAD

**Issue by Mark-J-Lawrence** [galasa-dev/projectmanagement#1981]
## Describe the bug
For some technical documentation I'm writing for the SDV Manager, I walk the reader through a simple Galasa project creation, to then add in SDV manager use later...however, it seems the walkthrough on the galasa.dev site isn't getting me to a point where I can successfully run a Galasa test.

## Steps to reproduce
1. Create a Galasa project using `galasactl project create --package com.ibm.cics.sdv.example --features ceda --force --obr --log - --gradle`
2. Enter the project dir and build it with `gradle clean build publishToMavenLocal`
3. Run the Galasa test with `galasactl runs submit local --log - --obr mvn:com.ibm.cics.sdv.example/com.ibm.cics.sdv.example.obr/0.0.1-SNAPSHOT/obr --class com.ibm.cics.sdv.example.ceda/com.ibm.cics.sdv.example.ceda.TestCeda`

## Expected behavior
As its purely code output by the helper, you'd expect it to be able to build and run.

## Additional context
It doesn't run, the trace seems to show it gathers the managers, then bombs out swiftly after. I think its a bit too soon before any of my CPS props could affect it?

```
2024/08/28 14:07:18 JVM output: (runid:L19) : 28/08/2024 14:07:18.882 TRACE main dev.galasa.framework.BundleManagement.loadBundle - Installing bundle com.ibm.cics.sdv.example.ceda
2024/08/28 14:07:18 JVM output: (runid:L19) : 28/08/2024 14:07:18.883 TRACE main dev.galasa.framework.BundleManagement.addResource - Resouce: com.ibm.cics.sdv.example.ceda/0.0.1.SNAPSHOT
2024/08/28 14:07:18 JVM output: (runid:L19) : 28/08/2024 14:07:18.897 TRACE main dev.galasa.framework.BundleManagement.addResource -   RequiredResource: dev.galasa.artifact.manager
2024/08/28 14:07:18 JVM output: (runid:L19) : 28/08/2024 14:07:18.897 TRACE main dev.galasa.framework.BundleManagement.addResource -   RequiredResource: org.assertj.core
2024/08/28 14:07:18 JVM output: (runid:L19) : 28/08/2024 14:07:18.897 TRACE main dev.galasa.framework.BundleManagement.addResource -   RequiredResource: dev.galasa.core.manager
2024/08/28 14:07:18 JVM output: (runid:L19) : 28/08/2024 14:07:18.897 TRACE main dev.galasa.framework.BundleManagement.addResource -   RequiredResource: org.apache.velocity.engine-core
2024/08/28 14:07:18 JVM output: (runid:L19) : 28/08/2024 14:07:18.897 TRACE main dev.galasa.framework.maven.repository.internal.GalasaMavenUrlHandlerService.fetchArtifact - Resolving maven artifact org.assertj:assertj-core:3.11.1:jar
2024/08/28 14:07:18 JVM output: (runid:L19) : 28/08/2024 14:07:18.897 TRACE main dev.galasa.framework.maven.repository.internal.GalasaMavenUrlHandlerService.fetchArtifact - Checking local repository file:////Users/marklawrence/.m2/repository
2024/08/28 14:07:18 JVM output: (runid:L19) : 28/08/2024 14:07:18.897 TRACE main dev.galasa.framework.maven.repository.internal.GalasaMavenUrlHandlerService.fetchArtifact - Looking for file /Users/marklawrence/.m2/repository/org/assertj/assertj-core/3.11.1/assertj-core-3.11.1.jar
2024/08/28 14:07:18 JVM output: (runid:L19) : 28/08/2024 14:07:18.897 TRACE main dev.galasa.framework.maven.repository.internal.GalasaMavenUrlHandlerService.fetchArtifact - Found in local repository at file:////Users/marklawrence/.m2/repository/org/assertj/assertj-core/3.11.1/assertj-core-3.11.1.jar
2024/08/28 14:07:18 JVM output: (runid:L19) : 28/08/2024 14:07:18.905 TRACE main dev.galasa.framework.maven.repository.internal.GalasaMavenUrlHandlerService.fetchArtifact - Resolving maven artifact com.ibm.cics.sdv.example:com.ibm.cics.sdv.example.ceda:0.0.1-SNAPSHOT:jar
2024/08/28 14:07:18 JVM output: (runid:L19) : 28/08/2024 14:07:18.905 TRACE main dev.galasa.framework.maven.repository.internal.GalasaMavenUrlHandlerService.fetchArtifact - Checking local repository file:////Users/marklawrence/.m2/repository
2024/08/28 14:07:18 JVM output: (runid:L19) : 28/08/2024 14:07:18.905 TRACE main dev.galasa.framework.maven.repository.internal.GalasaMavenUrlHandlerService.fetchArtifact - Looking for file /Users/marklawrence/.m2/repository/com/ibm/cics/sdv/example/com.ibm.cics.sdv.example.ceda/0.0.1-SNAPSHOT/com.ibm.cics.sdv.example.ceda-0.0.1-SNAPSHOT.jar
2024/08/28 14:07:18 JVM output: (runid:L19) : 28/08/2024 14:07:18.905 TRACE main dev.galasa.framework.maven.repository.internal.GalasaMavenUrlHandlerService.fetchArtifact - Found in local repository at file:////Users/marklawrence/.m2/repository/com/ibm/cics/sdv/example/com.ibm.cics.sdv.example.ceda/0.0.1-SNAPSHOT/com.ibm.cics.sdv.example.ceda-0.0.1-SNAPSHOT.jar
2024/08/28 14:07:18 JVM output: (runid:L19) : 28/08/2024 14:07:18.907 TRACE main dev.galasa.framework.maven.repository.internal.GalasaMavenUrlHandlerService.fetchArtifact - Resolving maven artifact dev.galasa:dev.galasa.core.manager:0.31.0:jar
2024/08/28 14:07:18 JVM output: (runid:L19) : 28/08/2024 14:07:18.907 TRACE main dev.galasa.framework.maven.repository.internal.GalasaMavenUrlHandlerService.fetchArtifact - Checking local repository file:////Users/marklawrence/.m2/repository
2024/08/28 14:07:18 JVM output: (runid:L19) : 28/08/2024 14:07:18.907 TRACE main dev.galasa.framework.maven.repository.internal.GalasaMavenUrlHandlerService.fetchArtifact - Looking for file /Users/marklawrence/.m2/repository/dev/galasa/dev.galasa.core.manager/0.31.0/dev.galasa.core.manager-0.31.0.jar
2024/08/28 14:07:18 JVM output: (runid:L19) : 28/08/2024 14:07:18.907 TRACE main dev.galasa.framework.maven.repository.internal.GalasaMavenUrlHandlerService.fetchArtifact - Found in local repository at file:////Users/marklawrence/.m2/repository/dev/galasa/dev.galasa.core.manager/0.31.0/dev.galasa.core.manager-0.31.0.jar
2024/08/28 14:07:18 JVM output: (runid:L19) : 28/08/2024 14:07:18.908 TRACE main dev.galasa.framework.maven.repository.internal.GalasaMavenUrlHandlerService.fetchArtifact - Resolving maven artifact dev.galasa:dev.galasa.artifact.manager:0.34.0:jar
2024/08/28 14:07:18 JVM output: (runid:L19) : 28/08/2024 14:07:18.909 TRACE main dev.galasa.framework.maven.repository.internal.GalasaMavenUrlHandlerService.fetchArtifact - Checking local repository file:////Users/marklawrence/.m2/repository
2024/08/28 14:07:18 JVM output: (runid:L19) : 28/08/2024 14:07:18.909 TRACE main dev.galasa.framework.maven.repository.internal.GalasaMavenUrlHandlerService.fetchArtifact - Looking for file /Users/marklawrence/.m2/repository/dev/galasa/dev.galasa.artifact.manager/0.34.0/dev.galasa.artifact.manager-0.34.0.jar
2024/08/28 14:07:18 JVM output: (runid:L19) : 28/08/2024 14:07:18.909 TRACE main dev.galasa.framework.maven.repository.internal.GalasaMavenUrlHandlerService.fetchArtifact - Found in local repository at file:////Users/marklawrence/.m2/repository/dev/galasa/dev.galasa.artifact.manager/0.34.0/dev.galasa.artifact.manager-0.34.0.jar
2024/08/28 14:07:18 JVM output: (runid:L19) : 28/08/2024 14:07:18.910 TRACE main dev.galasa.framework.maven.repository.internal.GalasaMavenUrlHandlerService.fetchArtifact - Resolving maven artifact org.apache.velocity:velocity-engine-core:2.3:jar
2024/08/28 14:07:18 JVM output: (runid:L19) : 28/08/2024 14:07:18.910 TRACE main dev.galasa.framework.maven.repository.internal.GalasaMavenUrlHandlerService.fetchArtifact - Checking local repository file:////Users/marklawrence/.m2/repository
2024/08/28 14:07:18 JVM output: (runid:L19) : 28/08/2024 14:07:18.910 TRACE main dev.galasa.framework.maven.repository.internal.GalasaMavenUrlHandlerService.fetchArtifact - Looking for file /Users/marklawrence/.m2/repository/org/apache/velocity/velocity-engine-core/2.3/velocity-engine-core-2.3.jar
2024/08/28 14:07:18 JVM output: (runid:L19) : 28/08/2024 14:07:18.911 TRACE main dev.galasa.framework.maven.repository.internal.GalasaMavenUrlHandlerService.fetchArtifact - Found in local repository at file:////Users/marklawrence/.m2/repository/org/apache/velocity/velocity-engine-core/2.3/velocity-engine-core-2.3.jar
2024/08/28 14:07:18 JVM output: (runid:L19) : 28/08/2024 14:07:18.926 ERROR main dev.galasa.framework.TestRunner.runTest - Unable to load the test bundle com.ibm.cics.sdv.example.ceda
dev.galasa.framework.spi.FrameworkException: Bundle 'com.ibm.cics.sdv.example.ceda' failed to install and activate
	at dev.galasa.framework.BundleManagement.loadBundle(BundleManagement.java:58) ~[-1724850438721:?]
	at dev.galasa.framework.TestRunner.runTest(TestRunner.java:235) [-1724850438721:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at dev.galasa.boot.felix.FelixFramework.runTest(FelixFramework.java:248) [galasa-boot-0.36.0.jar:?]
	at dev.galasa.boot.Launcher.launch(Launcher.java:172) [galasa-boot-0.36.0.jar:?]
	at dev.galasa.boot.Launcher.main(Launcher.java:122) [galasa-boot-0.36.0.jar:?]
Caused by: dev.galasa.framework.spi.FrameworkException: Bundle 'com.ibm.cics.sdv.example.ceda' failed to install and activate
	at dev.galasa.framework.BundleManagement.addResource(BundleManagement.java:180) ~[-1724850438721:?]
	at dev.galasa.framework.BundleManagement.loadBundle(BundleManagement.java:56) ~[-1724850438721:?]
	... 8 more
```

**Comment by techcobweb** [comment]
This is surprising as our CLI build process does something very similar for maven, and then for gradle, and that's working well.

However, that build process controls the contents of the home folder, and the ~/.m2/settings.xml, rather than what you are doing which picks up and uses whatever values you have there, and in your ~/.galasa or $GALASA_HOME folder.

When I pointed it at a different home folder, it worked for me.

When I removed my ~/.galasa, then re-created it fresh using `galasactl local init` (which sets up your home) then it worked.

**Comment by techcobweb** [comment]
Perhaps remove your ~/.galasa, then re-created it fresh using `galasactl local init`

**Comment by techcobweb** [comment]
```
>galasactl runs submit local --obr mvn:com.ibm.cics.sdv.example/com.ibm.cics.sdv.example.obr/0.0.1-SNAPSHOT/obr --class com.ibm.cics.sdv.example.ceda/com.ibm.cics.sdv.example.ceda.TestCeda 
submitted-time(UTC) name requestor status result test-name
2024-09-05 20:41:05 L2   mcobbett  queued Passed /com.ibm.cics.sdv.example.ceda/com.ibm.cics.sdv.example.ceda.TestCeda

Total:1 Passed:1
>
```

**Comment by techcobweb** [comment]
@Mark-J-Lawrence Comments on the above ?

**Comment by Mark-J-Lawrence** [comment]
@techcobweb I've just given what you suggested a try, it didn't work first time as I didn't delete the `~.m2` folder (only `~.galasa`), so gave it another go with it removed and it all kicked into life and everything worked.
I'm going to close this, I'm happy that it was on me to clean down my local maven repo & probably had a mish-mash of release versions & development versions over time.

Thank you for looking into it.
