### ISSUE TITLE
Bug: Unrecognised MF of -37

### ISSUE THREAD

**Issue by adamcoulthard** [galasa-dev/projectmanagement#2026]
## Describe the bug
We were running the test program ICC$RES1  supplied as a test CPP sample with CICS that uses the C Foundation classes and we received the following error from the 3270 data stream:

```
dev.galasa.zos3270.spi.DatastreamException: Unrecognised attribute in MF, '-37'
	at dev.galasa.zos3270.internal.datastream.OrderModifyField.<init>(OrderModifyField.java:67) ~[-1729382747409:?]
	at dev.galasa.zos3270.internal.comms.NetworkThread.processOrders(NetworkThread.java:899) ~[-1729382747409:?]
	at dev.galasa.zos3270.internal.comms.NetworkThread.process3270Datastream(NetworkThread.java:866) ~[-1729382747409:?]
	at dev.galasa.zos3270.internal.comms.NetworkThread.process3270Data(NetworkThread.java:853) ~[-1729382747409:?]
	at dev.galasa.zos3270.internal.comms.NetworkThread.processMessage(NetworkThread.java:219) ~[-1729382747409:?]
	at dev.galasa.zos3270.internal.comms.NetworkThread.run(NetworkThread.java:143) [-1729382747409:?]
```
I'm pretty sure this test used to work previously but I can't at the moment prove that at the moment.  I'm going to get a CICS dump and look at the data streams to see what is happening.

## Steps to reproduce
1. Create a test that compiles and runs the ICC$RES1 sample program in CICS.
2. Run the test and you will get the above MF error.

## Expected behavior
It should be able handle all field attributes.

**Comment by techcobweb** [comment]
@adamcoulthard can you pls send eamon or me the stream data itself so we can manually pick through it?  Need more information to look at this really.

**Comment by adamcoulthard** [comment]
@techcobweb do you need the stream from the CICS dump or is there a way to extract that from what galasa received?

**Comment by techcobweb** [comment]
@adamcoulthard not sure. The galas trace is where we should start. Can you attach one please ?

**Comment by adamcoulthard** [comment]
Interestingly this seems to have gone away now abit confused!  So I'm going to close this off at the moment....

**Comment by eamansour** [comment]
@Mark-J-Lawrence quick update on this:

I've delivered a change in https://github.com/galasa-dev/galasa/pull/360 that should stop the exception from being thrown and allow the manager to continue rendering the screen.

I was able to get the failing test running locally and tried it out again with the above changes, which managed to get the screen rendering for the test.

The change will be released in 0.43.0, but in the meantime, you can try it out from the main development build of Galasa. Let me know if you still run into the issue and I'll be more than happy to take another look at this!
