### ISSUE TITLE
OSGi loading of maven SPI fails when plugin and OBR at different levels

### ISSUE THREAD

**Issue by Michael-Baylis** [galasa-dev/projectmanagement#253]
Caused by: org.osgi.framework.BundleException: Bundle symbolic name and version are not unique: dev.galasa.framework.maven.repository.spi:0.7.0
at org.apache.felix.framework.BundleImpl.createRevision(BundleImpl.java:1337)
at org.apache.felix.framework.BundleImpl.(BundleImpl.java:113)
at org.apache.felix.framework.Felix.installBundle(Felix.java:3260)
at org.apache.felix.framework.BundleContextImpl.installBundle(BundleContextImpl.java:147)
at org.apache.felix.framework.BundleContextImpl.installBundle(BundleContextImpl.java:120)
at dev.galasa.framework.BundleManagement.addResource(BundleManagement.java:103)
... 9 more

**Comment by Michael-Baylis** [comment]
The maven.repository and .spi are loaded via boot and will be the same level as the plugin.   If a later version OBR is loaded then there is a clash due to an internal requirement that only 1 version of a bundle is loaded into the OSGi framework.

3 possibilities:-

1) Remove this restriction for bundles loaded via boot.
2) Remove the version qualifer for these bundles on the framework manifest.mf so it will use the version loaded by boot instead of trying to load a more up to date.

**Comment by Michael-Baylis** [comment]
The minimum version of the spi has been set to 0.3.0 so that mixing boot with current versions of framework should be ok.   the dependency version will only be updated if there is an actual change to the spi interface
