### ISSUE TITLE
ZosBatchJobImpl throws NPE if submitting jobs during Provision Discard step

### ISSUE THREAD

**Issue by Jimbo4794** [galasa-dev/projectmanagement#286]
Im trying to get my Beta manager to run a Job to clean up some resources used in the test by submitting a batch job. Results in throowing a trace like this:

```
java.lang.NullPointerException
        at dev.galasa.zosbatch.zosmf.manager.internal.ZosBatchJobImpl.storeArtifact(ZosBatchJobImpl.java:797)
        at dev.galasa.zosbatch.zosmf.manager.internal.ZosBatchJobImpl.<init>(ZosBatchJobImpl.java:117)
        at dev.galasa.zosbatch.zosmf.manager.internal.ZosBatchImpl.submitJob(ZosBatchImpl.java:68)
        at dev.galasa.zosbatch.zosmf.manager.internal.ZosBatchImpl.submitJob(ZosBatchImpl.java:55)
        at com.ibm.cics.galasa.beta.manager.internal.BetaInstallImpl.submitJob(BetaInstallImpl.java:237)
        at com.ibm.cics.galasa.beta.manager.internal.BetaInstallImpl.deleteLogStream(BetaInstallImpl.java:477)
        at com.ibm.cics.galasa.beta.manager.internal.BetaInstallImpl.cleanup(BetaInstallImpl.java:178)
        at com.ibm.cics.galasa.beta.manager.internal.BetaManagerImpl.provisionDiscard(BetaManagerImpl.java:121)
        at dev.galasa.framework.TestRunManagers.provisionDiscard(TestRunManagers.java:489)
        at dev.galasa.framework.TestRunner.discardEnvironment(TestRunner.java:454)
        at dev.galasa.framework.TestRunner.createEnvironment(TestRunner.java:443)
        at dev.galasa.framework.TestRunner.generateEnvironment(TestRunner.java:414)
        at dev.galasa.framework.TestRunner.runTest(TestRunner.java:336)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at dev.galasa.boot.felix.FelixFramework.runTest(FelixFramework.java:217)
        at dev.galasa.boot.Launcher.launch(Launcher.java:147)
        at dev.galasa.boot.Launcher.main(Launcher.java:104)
```

Its throwing this as it is trying to created a stored artifact using the Test Methods name, line 797 in the ZosBatchJobImpl.java

**Comment by Michael-Baylis** [comment]
absoutely need to be able to submit batch jobs during provisiondiscard

**Comment by DavidXRoberts** [comment]
@Jimbo4794 fix delivered. Please validate and close this issue if working OK. Ta

**Comment by DavidXRoberts** [comment]
Hang on with this one, I've realised I've missed something. And I think zOS File probably has the same issue

**Comment by Jimbo4794** [comment]
Testing your changes seem to work, but the "cleanup" jobs are not cleaned up themselves, leaving them in SDSF

**Comment by DavidXRoberts** [comment]
Clean up working now. Needed same for for File Manager too
