### ISSUE TITLE
Terminal TLS session on a basic socket 

### ISSUE THREAD

**Issue by ArthurCoucke** [galasa-dev/projectmanagement#347]
Connection fails with a TLS session on a basic socket. 

**TLS set to false** 
________________________________________________________________________________________________________________________________________
dev.galasa.zos3270.spi.NetworkException: Unable to connect to Telnet server
	at dev.galasa.zos3270.internal.comms.Network.connectClient(Network.java:112)
	at dev.galasa.zos3270.spi.Terminal.connect(Terminal.java:54)
	at dev.galasa.zos3270.internal.Zos3270ManagerImpl.provisionStart(Zos3270ManagerImpl.java:152)
	at dev.galasa.framework.TestRunManagers.provisionStart(TestRunManagers.java:472)
	at dev.galasa.framework.TestRunner.runEnvironment(TestRunner.java:468)
	at dev.galasa.framework.TestRunner.createEnvironment(TestRunner.java:441)
	at dev.galasa.framework.TestRunner.generateEnvironment(TestRunner.java:414)
	at dev.galasa.framework.TestRunner.runTest(TestRunner.java:336)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:90)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55)
	at java.lang.reflect.Method.invoke(Method.java:508)
	at dev.galasa.boot.felix.FelixFramework.runTest(FelixFramework.java:217)
	at dev.galasa.boot.Launcher.launch(Launcher.java:147)
	at dev.galasa.boot.Launcher.main(Launcher.java:104)
Caused by: dev.galasa.zos3270.spi.NetworkException: **Expected fffd28 but received fffd2e**
	at dev.galasa.zos3270.internal.comms.Network.expect(Network.java:310)
	at dev.galasa.zos3270.internal.comms.Network.negotiate(Network.java:170)
	at dev.galasa.zos3270.internal.comms.Network.connectClient(Network.java:103)
________________________________________________________________________________________________________________________________________

**TLS set to true**

07/07/2020 17:57:11.865 INFO  main dev.galasa.zos3270.internal.Zos3270ManagerImpl.provisionStart - Failed to connect zOS 3270 Terminal to #####
dev.galasa.zos3270.spi.NetworkException: Unable to connect to Telnet server
	at dev.galasa.zos3270.internal.comms.Network.connectClient(Network.java:112)
	at dev.galasa.zos3270.spi.Terminal.connect(Terminal.java:54)
	at dev.galasa.zos3270.internal.Zos3270ManagerImpl.provisionStart(Zos3270ManagerImpl.java:152)
	at dev.galasa.framework.TestRunManagers.provisionStart(TestRunManagers.java:472)
	at dev.galasa.framework.TestRunner.runEnvironment(TestRunner.java:468)
	at dev.galasa.framework.TestRunner.createEnvironment(TestRunner.java:441)
	at dev.galasa.framework.TestRunner.generateEnvironment(TestRunner.java:414)
	at dev.galasa.framework.TestRunner.runTest(TestRunner.java:336)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:90)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55)
	at java.lang.reflect.Method.invoke(Method.java:508)
	at dev.galasa.boot.felix.FelixFramework.runTest(FelixFramework.java:217)
	at dev.galasa.boot.Launcher.launch(Launcher.java:147)
	at dev.galasa.boot.Launcher.main(Launcher.java:104)
Caused by: javax.net.ssl.SSLException: Received fatal alert: internal_error
	at com.ibm.jsse2.k.a(k.java:32)
	at com.ibm.jsse2.k.a(k.java:21)
	at com.ibm.jsse2.av.b(av.java:802)
	at com.ibm.jsse2.av.a(av.java:673)
	at com.ibm.jsse2.av.i(av.java:647)
	at com.ibm.jsse2.av.a(av.java:231)
	at com.ibm.jsse2.av.startHandshake(av.java:175)
	at dev.galasa.zos3270.internal.comms.Network.createSocket(Network.java:143)
	at dev.galasa.zos3270.internal.comms.Network.connectClient(Network.java:96)
	... 14 more
________________________________________________________________________________________________________________________________________

**Comment by Michael-Baylis** [comment]
The port zos3270 is connected is a basic port without encryption,  however the first thing the server does is issue IAC DO TLS,  which zos3270 is supposed to start the TLS negotiation.   I knew I had to do this code sooner or later, but didn't have an example or drive to do it.   Now I have a requirement,  just need a server to test it on.

Hopefully will be able to work on this next week

**Comment by Michael-Baylis** [comment]
I have requested the ports, so hopefully will be able write the code very soon

**Comment by Michael-Baylis** [comment]
Finally,   got our network bods to create a working NEGTSECURE port.   Can start on the code now!

**Comment by ArthurCoucke** [comment]
Looking forward to it!

**Comment by Michael-Baylis** [comment]
The 3270 client in 0.11.0-SNAPSHOT can now cope with NEGTSECURE telnet ports.  so should be available in the 0.11.0 release 1st Octoberish.
