### ISSUE TITLE
Console manager is leaving consoles locked

### ISSUE THREAD

**Issue by Jimbo4794** [galasa-dev/projectmanagement#362]
I believe the console manager isnt releasing some sort of lock on consoles in use. In a job i am using mulitple commands, wihtout passing the console name, so it is defaulting to the user "GALASA". 

Intermittently it will fail on doing multiple calls, with error coming back with:

```
com.ibm.cics.galasa.beta.manager.BetaManagerException: Unable to issue command to MVLA
	at com.ibm.cics.galasa.beta.manager.internal.BetaInstallImpl.issueCommand(BetaInstallImpl.java:392)
	at com.ibm.cics.galasa.pipeline.beta.install.CICSBetaInstall.install(CICSBetaInstall.java:147)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at dev.galasa.framework.GenericMethodWrapper.invoke(GenericMethodWrapper.java:82)
	at dev.galasa.framework.TestMethodWrapper.invoke(TestMethodWrapper.java:56)
	at dev.galasa.framework.TestClassWrapper.runTestMethods(TestClassWrapper.java:182)
	at dev.galasa.framework.TestRunner.runTestClassWrapper(TestRunner.java:510)
	at dev.galasa.framework.TestRunner.runEnvironment(TestRunner.java:482)
	at dev.galasa.framework.TestRunner.createEnvironment(TestRunner.java:442)
	at dev.galasa.framework.TestRunner.generateEnvironment(TestRunner.java:415)
	at dev.galasa.framework.TestRunner.runTest(TestRunner.java:337)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at dev.galasa.boot.felix.FelixFramework.runTest(FelixFramework.java:220)
	at dev.galasa.boot.Launcher.launch(Launcher.java:152)
	at dev.galasa.boot.Launcher.main(Launcher.java:106)
Caused by: dev.galasa.zosconsole.ZosConsoleException: Console command "SETPROG APF,ADD,DSN=CICSBETA.BETA.CICS.SEYUAUTH,SMS" failed. Reason "Error happened in TSO/E address space, error description: IZUG899E: The request could not be completed because an error occurred. Error: \"java.lang.IllegalStateException: The backend application GALASA could not be started. An error was received: java.lang.IllegalStateException: Could not register backend application. The specified key GALASA is already in use by TSO address space entry GALASA-189-aacmaaab..\" "
	at dev.galasa.zosconsole.zosmf.manager.internal.ZosConsoleCommandImpl.issueCommand(ZosConsoleCommandImpl.java:95)
	at dev.galasa.zosconsole.zosmf.manager.internal.ZosConsoleImpl.issueCommand(ZosConsoleImpl.java:51)
	at dev.galasa.zosconsole.zosmf.manager.internal.ZosConsoleImpl.issueCommand(ZosConsoleImpl.java:37)
	at com.ibm.cics.galasa.beta.manager.internal.BetaInstallImpl.issueCommand(BetaInstallImpl.java:390)
```

There is a few runs still in the RAS on our galasa-prod if you want to see full runs:

1. J411
1. J403
1. J379

**Comment by Jimbo4794** [comment]
So not actually sure what is causing this but not 100% it is the actual galasa manager now. Just implemented a work around to use a different console name between commands and im still getting similar errors:

```
Caused by: dev.galasa.zosconsole.ZosConsoleException: Console command "SETPROG APF,ADD,DSN=CICSBETA.BETA.CICS.SDFHLIC,SMS" failed. Reason "Error happened in TSO/E address space, error description: IZUG899E: The request could not be completed because an error occurred. Error: \"java.lang.IllegalStateException: The backend application GALASA66 could not be started. An error was received: java.lang.IllegalArgumentException: Input message type 4 cannot be assigned because it is currently in use..\" "
```
Going to dig a little further

**Comment by Jimbo4794** [comment]
Can confirm that the console GALASA66 from my comment was not used by any other component of the test
