### ISSUE TITLE
Unsupported Command Code error using 3270 terminal.

### ISSUE THREAD

**Issue by cliftona-hursley** [galasa-dev/projectmanagement#374]
My test starts the CICS/Rexx interpreter running and the console log gives me:
Aug 06, 2020 11:53:35 AM dev.galasa.zos3270.internal.comms.NetworkThread run
SEVERE: Problem with Network Thread
dev.galasa.zos3270.spi.DatastreamException: Unsupported command code=126
	at dev.galasa.zos3270.internal.datastream.AbstractCommandCode.getCommandCode(AbstractCommandCode.java:54)
	at dev.galasa.zos3270.internal.comms.NetworkThread.process3270Data(NetworkThread.java:157)
	at dev.galasa.zos3270.internal.comms.NetworkThread.processMessage(NetworkThread.java:136)
	at dev.galasa.zos3270.internal.comms.NetworkThread.run(NetworkThread.java:74)

And the terminal gets dropped. I have a CICS dump triggered by CICS detecting the terminal being dropped if required.

**Comment by Michael-Baylis** [comment]
This should be working now.  I implemented EWA sometime ago
