### ISSUE TITLE
Eclipse Plugin not compatible with Eclipse version 4.15+

### ISSUE THREAD

**Issue by matthewchivers** [galasa-dev/projectmanagement#403]
When installing the Galasa plugin for Eclipse (following [these instructions](https://galasa.dev/docs/getting-started/installing)), the installation completes and Eclipse restarts as requested. However, Galasa then doesn't appear in the top toolbar (between 'Run' and 'Window') as described, nor does it appear in the listbox on the left hand side of the "Run Configurations" window (`Run => Run Configurations`). 
This issue occurs with Eclipse versions:

- 4.17 (2020-09)
- 4.16 (2020-06)
- 4.15 (2020-03)

When rolling back to Eclipse Version 4.14 the plugin installed correctly, with "Galasa" appearing in the toolbar and within "Run Configurations".

Java version installed: `1.8.0_251`

**Comment by matthewchivers** [comment]
Log from version 4.16: 
```
!SESSION 2020-09-21 14:12:16.236 -----------------------------------------------
eclipse.buildId=4.16.0.I20200604-0540
java.version=1.8.0_251
java.vendor=Oracle Corporation
BootLoader constants: OS=macosx, ARCH=x86_64, WS=cocoa, NL=en_GB
Framework arguments:  -product org.eclipse.epp.package.java.product -keyring /Users/matthewchivers/.eclipse_keyring
Command-line arguments:  -os macosx -ws cocoa -arch x86_64 -product org.eclipse.epp.package.java.product -keyring /Users/matthewchivers/.eclipse_keyring

!ENTRY dev.galasa.eclipse 4 0 2020-09-21 14:12:16.819
!MESSAGE FrameworkEvent ERROR
!STACK 0
org.osgi.framework.BundleException: Could not resolve module: dev.galasa.eclipse [445]
  Unresolved requirement: Import-Package: org.eclipse.pde.core.project
    -> Export-Package: org.eclipse.pde.core.project; bundle-symbolic-name="org.eclipse.pde.core"; bundle-version="3.14.0.v20200817-1143"; version="0.0.0"
       org.eclipse.pde.core [456]
         Unresolved requirement: Require-Capability: osgi.ee; filter:="(&(osgi.ee=JavaSE)(version=11))"

	at org.eclipse.osgi.container.Module.start(Module.java:463)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel$2.run(ModuleContainer.java:1845)
	at org.eclipse.osgi.internal.framework.EquinoxContainerAdaptor$1$1.execute(EquinoxContainerAdaptor.java:136)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1838)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1779)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1743)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1665)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:345)

!ENTRY dev.galasa.simbank.ui 4 0 2020-09-21 14:12:16.821
!MESSAGE FrameworkEvent ERROR
!STACK 0
org.osgi.framework.BundleException: Could not resolve module: dev.galasa.simbank.ui [448]
  Unresolved requirement: Import-Package: dev.galasa.eclipse
    -> Export-Package: dev.galasa.eclipse; bundle-symbolic-name="dev.galasa.eclipse"; bundle-version="0.10.0.202008040938"; version="0.0.0"
       dev.galasa.eclipse [445]
         Unresolved requirement: Import-Package: org.eclipse.pde.core.project
           -> Export-Package: org.eclipse.pde.core.project; bundle-symbolic-name="org.eclipse.pde.core"; bundle-version="3.14.0.v20200817-1143"; version="0.0.0"
              org.eclipse.pde.core [456]
                Unresolved requirement: Require-Capability: osgi.ee; filter:="(&(osgi.ee=JavaSE)(version=11))"

	at org.eclipse.osgi.container.Module.start(Module.java:463)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel$2.run(ModuleContainer.java:1845)
	at org.eclipse.osgi.internal.framework.EquinoxContainerAdaptor$1$1.execute(EquinoxContainerAdaptor.java:136)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1838)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1779)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1743)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1665)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:345)

!ENTRY dev.galasa.zos3270.ui 4 0 2020-09-21 14:12:16.821
!MESSAGE FrameworkEvent ERROR
!STACK 0
org.osgi.framework.BundleException: Could not resolve module: dev.galasa.zos3270.ui [450]
  Unresolved requirement: Import-Package: dev.galasa.eclipse.launcher
    -> Export-Package: dev.galasa.eclipse.launcher; bundle-symbolic-name="dev.galasa.eclipse"; bundle-version="0.10.0.202008040938"; version="0.0.0"
       dev.galasa.eclipse [445]
         Unresolved requirement: Import-Package: org.eclipse.pde.core.project
           -> Export-Package: org.eclipse.pde.core.project; bundle-symbolic-name="org.eclipse.pde.core"; bundle-version="3.14.0.v20200817-1143"; version="0.0.0"
              org.eclipse.pde.core [456]
                Unresolved requirement: Require-Capability: osgi.ee; filter:="(&(osgi.ee=JavaSE)(version=11))"
  Unresolved requirement: Import-Package: dev.galasa.eclipse.ui.run.storedartifacts
    -> Export-Package: dev.galasa.eclipse.ui.run.storedartifacts; bundle-symbolic-name="dev.galasa.eclipse"; bundle-version="0.10.0.202008040938"; version="0.0.0"
  Unresolved requirement: Import-Package: dev.galasa.eclipse.ui.run
    -> Export-Package: dev.galasa.eclipse.ui.run; bundle-symbolic-name="dev.galasa.eclipse"; bundle-version="0.10.0.202008040938"; version="0.0.0"
  Unresolved requirement: Import-Package: dev.galasa.eclipse.launcher.tabs
    -> Export-Package: dev.galasa.eclipse.launcher.tabs; bundle-symbolic-name="dev.galasa.eclipse"; bundle-version="0.10.0.202008040938"; version="0.0.0"
  Unresolved requirement: Import-Package: dev.galasa.eclipse
    -> Export-Package: dev.galasa.eclipse; bundle-symbolic-name="dev.galasa.eclipse"; bundle-version="0.10.0.202008040938"; version="0.0.0"
  Unresolved requirement: Import-Package: dev.galasa.eclipse.liveupdates
    -> Export-Package: dev.galasa.eclipse.liveupdates; bundle-symbolic-name="dev.galasa.eclipse"; bundle-version="0.10.0.202008040938"; version="0.0.0"

	at org.eclipse.osgi.container.Module.start(Module.java:463)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel$2.run(ModuleContainer.java:1845)
	at org.eclipse.osgi.internal.framework.EquinoxContainerAdaptor$1$1.execute(EquinoxContainerAdaptor.java:136)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1838)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1779)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1743)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1665)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:345)

!ENTRY org.eclipse.pde.core 4 0 2020-09-21 14:12:16.821
!MESSAGE FrameworkEvent ERROR
!STACK 0
org.osgi.framework.BundleException: Could not resolve module: org.eclipse.pde.core [456]
  Unresolved requirement: Require-Capability: osgi.ee; filter:="(&(osgi.ee=JavaSE)(version=11))"

	at org.eclipse.osgi.container.Module.start(Module.java:463)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel$2.run(ModuleContainer.java:1845)
	at org.eclipse.osgi.internal.framework.EquinoxContainerAdaptor$1$1.execute(EquinoxContainerAdaptor.java:136)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1838)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1779)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1743)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1665)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:345)

!ENTRY org.eclipse.jface 2 0 2020-09-21 14:12:27.173
!MESSAGE Keybinding conflicts occurred.  They may interfere with normal accelerator operation.
!SUBENTRY 1 org.eclipse.jface 2 0 2020-09-21 14:12:27.173
!MESSAGE A conflict occurred for COMMAND+SHIFT+T:
Binding(COMMAND+SHIFT+T,
	ParameterizedCommand(Command(org.eclipse.jdt.ui.navigate.open.type,Open Type,
		Open a type in a Java editor,
		Category(org.eclipse.ui.category.navigate,Navigate,null,true),
		org.eclipse.ui.internal.WorkbenchHandlerServiceHandler@3b362f1,
		,,true),null),
	org.eclipse.ui.defaultAcceleratorConfiguration,
	org.eclipse.ui.contexts.window,,,system)
Binding(COMMAND+SHIFT+T,
	ParameterizedCommand(Command(org.eclipse.lsp4e.symbolinworkspace,Go to Symbol in Workspace,
		,
		Category(org.eclipse.lsp4e.category,Language Servers,null,true),
		org.eclipse.ui.internal.WorkbenchHandlerServiceHandler@6451a288,
		,,true),null),
	org.eclipse.ui.defaultAcceleratorConfiguration,
	org.eclipse.ui.contexts.window,,,system)

**Comment by Michael-Baylis** [comment]
The Galasa plugin is now supported in all eclipse from Photon.

**Comment by matthewchivers** [comment]
@Michael-Baylis Just tested installing the plugin (from p2.galasa.dev) in eclipse 2020-06 and it did not install correctly. I'm getting the same symptoms as described above.

Eclipse "About" shows Galasa as installed, but all functionality / menu items are missing. There's no entry in the top menu bar, nor does it give any run configurations, nor the ability to create an "example" project (e.g. SimBank Manager/Tests)

This is using Big Sur 11.4 << Maybe OS Specific?

**Comment by hobbit1983** [comment]
OK - I have tried both eclipse for Java Developers 2020-06 and 2021-03, In both cases I installed the galasa plugin, installed the example project and ran SimBank, all the launchers, menu items and wizards seemed to be present and correct.  This was all on Mac OS Catalina.  I have a spare MacBook (aint I lucky) that might be running big Sur (if not I can upgrade it) and try and recreate there

**Comment by matthewchivers** [comment]
There are some other entries / errors present, but it's a long log.
Here's the stuff that mentions Galasa:
```
!ENTRY dev.galasa.eclipse 4 0 2021-06-06 13:06:17.455
!MESSAGE FrameworkEvent ERROR
!STACK 0
org.osgi.framework.BundleException: Could not resolve module: dev.galasa.eclipse [445]
  Unresolved requirement: Import-Package: org.eclipse.m2e.core.ui.internal
    -> Export-Package: org.eclipse.m2e.core.ui.internal; bundle-symbolic-name="org.eclipse.m2e.core.ui"; bundle-version="1.16.0.20200514-1409"; version="0.0.0"; x-internal:="true"
       org.eclipse.m2e.core.ui [246]
         Unresolved requirement: Require-Bundle: org.eclipse.m2e.model.edit; bundle-version="[1.16.0,1.17.0)"; visibility:="reexport"
           -> Bundle-SymbolicName: org.eclipse.m2e.model.edit; bundle-version="1.16.0.20200514-1409"; singleton:="true"
              org.eclipse.m2e.model.edit [261]
                Unresolved requirement: Require-Bundle: org.eclipse.wst.xml.core; visibility:="reexport"
                  -> Bundle-SymbolicName: org.eclipse.wst.xml.core; bundle-version="1.2.300.v202102110535"; singleton:="true"
                     org.eclipse.wst.xml.core [463]
                       Unresolved requirement: Require-Bundle: org.eclipse.jem.util; bundle-version="[2.1.200,3.0.0)"; resolution:="optional"
                       Unresolved requirement: Require-Bundle: org.eclipse.wst.common.emfworkbench.integration; bundle-version="[1.2.100,1.3.0)"; resolution:="optional"
                       Unresolved requirement: Require-Capability: osgi.ee; filter:="(&(osgi.ee=JavaSE)(version=11))"

	at org.eclipse.osgi.container.Module.start(Module.java:463)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel$2.run(ModuleContainer.java:1845)
	at org.eclipse.osgi.internal.framework.EquinoxContainerAdaptor$1$1.execute(EquinoxContainerAdaptor.java:136)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1838)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1779)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1743)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1665)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:345)

!ENTRY dev.galasa.simbank.ui 4 0 2021-06-06 13:06:17.458
!MESSAGE FrameworkEvent ERROR
!STACK 0
org.osgi.framework.BundleException: Could not resolve module: dev.galasa.simbank.ui [448]
  Unresolved requirement: Import-Package: org.eclipse.m2e.core.ui.internal
    -> Export-Package: org.eclipse.m2e.core.ui.internal; bundle-symbolic-name="org.eclipse.m2e.core.ui"; bundle-version="1.16.0.20200514-1409"; version="0.0.0"; x-internal:="true"
       org.eclipse.m2e.core.ui [246]
         Unresolved requirement: Require-Bundle: org.eclipse.m2e.model.edit; bundle-version="[1.16.0,1.17.0)"; visibility:="reexport"
           -> Bundle-SymbolicName: org.eclipse.m2e.model.edit; bundle-version="1.16.0.20200514-1409"; singleton:="true"
              org.eclipse.m2e.model.edit [261]
                Unresolved requirement: Require-Bundle: org.eclipse.wst.xml.core; visibility:="reexport"
                  -> Bundle-SymbolicName: org.eclipse.wst.xml.core; bundle-version="1.2.300.v202102110535"; singleton:="true"
                     org.eclipse.wst.xml.core [463]
                       Unresolved requirement: Require-Bundle: org.eclipse.jem.util; bundle-version="[2.1.200,3.0.0)"; resolution:="optional"
                       Unresolved requirement: Require-Bundle: org.eclipse.wst.common.emfworkbench.integration; bundle-version="[1.2.100,1.3.0)"; resolution:="optional"
                       Unresolved requirement: Require-Capability: osgi.ee; filter:="(&(osgi.ee=JavaSE)(version=11))"
  Unresolved requirement: Import-Package: dev.galasa.eclipse
    -> Export-Package: dev.galasa.eclipse; bundle-symbolic-name="dev.galasa.eclipse"; bundle-version="0.15.0.202105251034"; version="0.0.0"
       dev.galasa.eclipse [445]
         Unresolved requirement: Import-Package: org.eclipse.m2e.core.ui.internal
           -> Export-Package: org.eclipse.m2e.core.ui.internal; bundle-symbolic-name="org.eclipse.m2e.core.ui"; bundle-version="1.16.0.20200514-1409"; version="0.0.0"; x-internal:="true"

	at org.eclipse.osgi.container.Module.start(Module.java:463)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel$2.run(ModuleContainer.java:1845)
	at org.eclipse.osgi.internal.framework.EquinoxContainerAdaptor$1$1.execute(EquinoxContainerAdaptor.java:136)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1838)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1779)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1743)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1665)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:345)

!ENTRY dev.galasa.zos3270.ui 4 0 2021-06-06 13:06:17.460
!MESSAGE FrameworkEvent ERROR
!STACK 0
org.osgi.framework.BundleException: Could not resolve module: dev.galasa.zos3270.ui [450]
  Unresolved requirement: Import-Package: dev.galasa.eclipse
    -> Export-Package: dev.galasa.eclipse; bundle-symbolic-name="dev.galasa.eclipse"; bundle-version="0.15.0.202105251034"; version="0.0.0"
       dev.galasa.eclipse [445]
         Unresolved requirement: Import-Package: org.eclipse.m2e.core.ui.internal
           -> Export-Package: org.eclipse.m2e.core.ui.internal; bundle-symbolic-name="org.eclipse.m2e.core.ui"; bundle-version="1.16.0.20200514-1409"; version="0.0.0"; x-internal:="true"
              org.eclipse.m2e.core.ui [246]
                Unresolved requirement: Require-Bundle: org.eclipse.m2e.model.edit; bundle-version="[1.16.0,1.17.0)"; visibility:="reexport"
                  -> Bundle-SymbolicName: org.eclipse.m2e.model.edit; bundle-version="1.16.0.20200514-1409"; singleton:="true"
                     org.eclipse.m2e.model.edit [261]
                       Unresolved requirement: Require-Bundle: org.eclipse.wst.xml.core; visibility:="reexport"
                         -> Bundle-SymbolicName: org.eclipse.wst.xml.core; bundle-version="1.2.300.v202102110535"; singleton:="true"
                            org.eclipse.wst.xml.core [463]
                              Unresolved requirement: Require-Bundle: org.eclipse.jem.util; bundle-version="[2.1.200,3.0.0)"; resolution:="optional"
                              Unresolved requirement: Require-Bundle: org.eclipse.wst.common.emfworkbench.integration; bundle-version="[1.2.100,1.3.0)"; resolution:="optional"
                              Unresolved requirement: Require-Capability: osgi.ee; filter:="(&(osgi.ee=JavaSE)(version=11))"
  Unresolved requirement: Import-Package: dev.galasa.eclipse.launcher.tabs
    -> Export-Package: dev.galasa.eclipse.launcher.tabs; bundle-symbolic-name="dev.galasa.eclipse"; bundle-version="0.15.0.202105251034"; version="0.0.0"
  Unresolved requirement: Import-Package: dev.galasa.eclipse.ui.run.storedartifacts
    -> Export-Package: dev.galasa.eclipse.ui.run.storedartifacts; bundle-symbolic-name="dev.galasa.eclipse"; bundle-version="0.15.0.202105251034"; version="0.0.0"
  Unresolved requirement: Import-Package: dev.galasa.eclipse.liveupdates
    -> Export-Package: dev.galasa.eclipse.liveupdates; bundle-symbolic-name="dev.galasa.eclipse"; bundle-version="0.15.0.202105251034"; version="0.0.0"
  Unresolved requirement: Import-Package: dev.galasa.eclipse.launcher
    -> Export-Package: dev.galasa.eclipse.launcher; bundle-symbolic-name="dev.galasa.eclipse"; bundle-version="0.15.0.202105251034"; version="0.0.0"
  Unresolved requirement: Import-Package: dev.galasa.eclipse.ui.run
    -> Export-Package: dev.galasa.eclipse.ui.run; bundle-symbolic-name="dev.galasa.eclipse"; bundle-version="0.15.0.202105251034"; version="0.0.0"

	at org.eclipse.osgi.container.Module.start(Module.java:463)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel$2.run(ModuleContainer.java:1845)
	at org.eclipse.osgi.internal.framework.EquinoxContainerAdaptor$1$1.execute(EquinoxContainerAdaptor.java:136)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1838)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1779)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1743)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1665)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:345)
```

I'm running Big Sur v11.4:
```
$ uname -a
Darwin Matthews-MBP-2.localdomain 20.5.0 Darwin Kernel Version 20.5.0: Sat May  8 05:10:33 PDT 2021; root:xnu-7195.121.3~9/RELEASE_X86_64 x86_64
```

**Comment by hobbit1983** [comment]
So just had my sister install the latest eclipse for java developers and the Galasa plugin on her M1 Mac mini running big sur and it all worked!  In other words I've ascertained another thing it isn't but not helped with what the problem might be

**Comment by Michael-Baylis** [comment]
which flavour is being used of 2021-06?    java or jee?    Additional plugins are provided in the jee version.   I will test later to see what I get

**Comment by Michael-Baylis** [comment]
In @matthewchivers comment above in the log,  it is reporting that it eclipse is not running in Java 11

**Comment by matthewchivers** [comment]
I can confirm that this was fixed by telling Eclipse to use Java 11. Thanks @Michael-Baylis
