### ISSUE TITLE
3270 Manager doe snot seem to detect a keyboard unlock

### ISSUE THREAD

**Issue by cliftona-hursley** [galasa-dev/projectmanagement#424]
This is an issue with JAT using the Galasa 3270 manager.

Running a Rexx/CICS test, it invokes the supplied IVP exec "CICIVP1", confirms the expected responses are on the screen and then attempts to supply further information.

Stepping through the code, the script calls a method "waitInput()" which completes, the screen is checked for data but on attempting to send the response with method "sendText" the log shows:

14:38:18 TRACE [Method] com.ibm.jat.zos3270.internal.Zos3270TerminalImpl - Waiting 180000ms for the screen to be ready for input
14:38:23 DEBUG [Method] com.ibm.cics.test.rexxcics.Development_Rexx - Checking first set of items displayed on the screen
14:38:26 TRACE [Method] com.ibm.cics.test.rexxcics.Development_Rexx - Checking screen for '*** This is a test REXX program running under CICS-TS   ***'
14:38:26 TRACE [Method] com.ibm.jat.zos3270.internal.Zos3270TerminalImpl - Searching the screen for 1 instances of "*** This is a test REXX program running under CICS-TS   ***" with 0ms timeout
14:38:26 TRACE [Method] com.ibm.jat.zos3270.internal.Zos3270TerminalImpl - 1 instances of *** This is a test REXX program running under CICS-TS   *** found
14:38:28 TRACE [Method] com.ibm.cics.test.rexxcics.Development_Rexx - Checking screen for '*** It was loaded from CICUSER-CICIVP1   '
14:38:28 TRACE [Method] com.ibm.jat.zos3270.internal.Zos3270TerminalImpl - Searching the screen for 1 instances of "*** It was loaded from CICUSER-CICIVP1   " with 0ms timeout
14:38:28 TRACE [Method] com.ibm.jat.zos3270.internal.Zos3270TerminalImpl - 1 instances of *** It was loaded from CICUSER-CICIVP1    found
14:38:31 TRACE [Method] com.ibm.cics.test.rexxcics.Development_Rexx - Checking screen for 'What is your name?'
14:38:31 TRACE [Method] com.ibm.jat.zos3270.internal.Zos3270TerminalImpl - Searching the screen for 1 instances of "What is your name?" with 0ms timeout
14:38:31 TRACE [Method] com.ibm.jat.zos3270.internal.Zos3270TerminalImpl - 1 instances of What is your name? found
14:38:35 INFO [Method] com.ibm.cics.test.rexxcics.Development_Rexx - Supplying response to prompt for name
14:38:36 TRACE [Method] com.ibm.jat.zos3270.internal.Zos3270TerminalImpl - Waiting 180000ms for the screen to be ready for input
14:38:37 DEBUG [Method] com.ibm.jat.zos3270.internal.Zos3270TerminalImpl - Sending "Andy Clifton[enter]" to the terminal
14:46:40 INFO [main] com.ibm.jat.cics.internal.DumpManagement - Now scanning region: JATP3550 for system dumps
14:46:40 ERROR [main] com.ibm.cics.jatp.internal.framework.JATTestMethod - Ending dfca42bf-2309-48da-bb46-6177513fc3a8
---------**********************************************************************************
---------*** FAILED - Test Method 'com.ibm.cics.test.rexxcics.Development_Rexx#Rexx_IVP' type=TestMethod
---------**********************************************************************************
14:46:40 ERROR [main] com.ibm.cics.jatp.internal.framework.JATTestMethod - FAILED - Test Method 'com.ibm.cics.test.rexxcics.Development_Rexx#Rexx_IVP' type=TestMethod
com.ibm.cics.jatp.exceptions.TerminalException: Problem sending text 'Andy Clifton[enter]' to the screen
	at com.ibm.jat.zos3270.internal.Zos3270TerminalImpl.sendKeys(Zos3270TerminalImpl.java:431)
	at com.ibm.jat.zos3270.internal.Zos3270TerminalImpl.sendText(Zos3270TerminalImpl.java:417)
	at com.ibm.jat.zos3270.internal.Zos3270TerminalImpl.sendText(Zos3270TerminalImpl.java:398)
	at com.ibm.cics.test.rexxcics.RexxTests.Run_IVP(RexxTests.java:1030)
	at com.ibm.cics.test.rexxcics.Development_Rexx.Rexx_IVP(Development_Rexx.java:160)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:90)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55)
	at java.lang.reflect.Method.invoke(Method.java:508)
	at com.ibm.cics.jatp.internal.framework.JATTestMethod$1.run(JATTestMethod.java:267)
Caused by: com.ibm.jat.zos3270.internal.JatZos3270Exception: Unable to send text to the screen
	at com.ibm.jat.zos3270.internal.keys.HodText.action(HodText.java:25)
	at com.ibm.jat.zos3270.internal.Zos3270TerminalImpl.sendKeys(Zos3270TerminalImpl.java:428)
	... 9 more
Caused by: dev.galasa.zos3270.FieldNotFoundException: Unable to type where the cursor is pointing to - 1840
	at dev.galasa.zos3270.spi.Screen.type(Screen.java:1392)
	at dev.galasa.zos3270.spi.Screen.type(Screen.java:1377)
	at dev.galasa.zos3270.spi.Terminal.type(Terminal.java:194)
	at com.ibm.jat.zos3270.internal.keys.HodText.action(HodText.java:23)
	... 10 more

**Comment by cliftona-hursley** [comment]
Hi Will,
I think this is what you need.
If you run com.ibm.cics.test.rexxcics.Development_Rexx in the BSF JAT pipeline on Hursley Plex 2 using any release of CICS but setting rexx.prefix to CICSTEST.REXX in the properties file you'll hit the problem.

Cheers

**Comment by abigail-b** [comment]
Tracked on https://jazz104.hursley.ibm.com:9443/jazz/web/projects/CICS%20TS%20for%20zOS#action=com.ibm.team.workitem.viewWorkItem&id=167260

**Comment by cliftona-hursley** [comment]
Greetings, as far as I can see, it is still the same issue. I think this is what you want but if not, I am not sure how produce exactly what you need so we may need a couple of discussions :-),

I've just run a test on Hursley Plex 2 through the automation (Run R325522) and the trace shows:

10:24:25 ERROR [Engine run R325522] com.ibm.cics.jatp.internal.framework.JATTestMethod - Ending d3a921bc-3e6a-4ac3-8eec-924283fb2f01
---------**********************************************************************************
---------*** FAILED - Test Method 'com.ibm.cics.test.rexxcics.Runtime_Rexx#Rexx_IVP' type=TestMethod
---------**********************************************************************************
10:24:25 ERROR [Engine run R325522] com.ibm.cics.jatp.internal.framework.JATTestMethod - FAILED - Test Method 'com.ibm.cics.test.rexxcics.Runtime_Rexx#Rexx_IVP' type=TestMethod
com.ibm.cics.jatp.exceptions.TerminalException: Problem sending text 'Andy Clifton[enter]' to the screen
	at com.ibm.jat.zos3270.internal.Zos3270TerminalImpl.sendKeys(Zos3270TerminalImpl.java:431) ~[?:?]
	at com.ibm.jat.zos3270.internal.Zos3270TerminalImpl.sendText(Zos3270TerminalImpl.java:417) ~[?:?]
	at com.ibm.jat.zos3270.internal.Zos3270TerminalImpl.sendText(Zos3270TerminalImpl.java:398) ~[?:?]
	at com.ibm.cics.test.rexxcics.RexxTests.Run_IVP(RexxTests.java:1002) ~[?:?]
	at com.ibm.cics.test.rexxcics.Runtime_Rexx.Rexx_IVP(Runtime_Rexx.java:160) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at com.ibm.cics.jatp.internal.framework.JATTestMethod$1.run(JATTestMethod.java:268) ~[?:?]
Caused by: com.ibm.jat.zos3270.internal.JatZos3270Exception: Unable to send text to the screen
	at com.ibm.jat.zos3270.internal.keys.HodText.action(HodText.java:25) ~[?:?]
	at com.ibm.jat.zos3270.internal.Zos3270TerminalImpl.sendKeys(Zos3270TerminalImpl.java:428) ~[?:?]
	... 9 more
**Caused by: dev.galasa.zos3270.FieldNotFoundException: Unable to type where the cursor is pointing to** - 1840
	at dev.galasa.zos3270.spi.Screen.type(Screen.java:1444) ~[?:?]
	at dev.galasa.zos3270.spi.Screen.type(Screen.java:1429) ~[?:?]
	at dev.galasa.zos3270.spi.Terminal.type(Terminal.java:206) ~[?:?]
	at com.ibm.jat.zos3270.internal.keys.HodText.action(HodText.java:23) ~[?:?]
	at com.ibm.jat.zos3270.internal.Zos3270TerminalImpl.sendKeys(Zos3270TerminalImpl.java:428) ~[?:?]

**Comment by techcobweb** [comment]
Thanks for the extra info Andy. So long as we have the run ID we should be able to download everything we need. Although I don't have access to Tom's system yet...

**Comment by cliftona-hursley** [comment]
Been doing a bit more experimenting on this and am wondering if the problem is related to the way data is being sent to the screen. The task running updates the screen by sending text containing 3270 data stream commands to put text at a specific point on the screen and then place the cursor back to the unprotected input area rather than update the entire screen.

I've not looked at the data flows yet but what I am speculating is happening is that a stream is sent to the position to a specific point, protected the field, send some text and reposition the cursor to the input field. But there is no instruction to set the field unprotected because it already is unprotected. The 3270 manager is only seeing an instruction to protect the field and none to unprotect and does not realise the field is already unprotected.
