### ISSUE TITLE
Error injecting org.apache.maven.artifact.installer.DefaultArtifactInstaller

### ISSUE THREAD

**Issue by hobbit1983** [galasa-dev/projectmanagement#428]
User David Dai raised this issue on slack:

Building a empty own galasa project as per the documentation user is experiencing the following when trying to mvn install the project:
```
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO]
[INFO] com.example.tests.parent
[INFO] com.example.tests.manager
[INFO] com.example.tests.atests
[INFO] com.example.tests.obr
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building com.example.tests.parent 0.1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- galasa-maven-plugin:0.11.0:bundletestcat (build-testcatalog) @ com.example.tests.parent ---
[INFO] Skipping Bundle Test Catalog build, not a bundle project
[INFO]
[INFO] --- maven-install-plugin:2.4:install (default-install) @ com.example.tests.parent ---
[WARNING] Error injecting: org.apache.maven.artifact.installer.DefaultArtifactInstaller
com.google.inject.ProvisionException: Unable to provision, see the following errors:
1) Error injecting: private org.eclipse.aether.spi.log.Logger org.apache.maven.repository.internal.DefaultVersionRangeResolver.logger
  while locating org.apache.maven.repository.internal.DefaultVersionRangeResolver
  while locating java.lang.Object annotated with *
  at org.eclipse.sisu.wire.LocatorWiring
  while locating org.eclipse.aether.impl.VersionRangeResolver
    for parameter 1 at org.eclipse.aether.internal.impl.DefaultRepositorySystem.<init>(Unknown Source)
  while locating org.eclipse.aether.internal.impl.DefaultRepositorySystem
  while locating java.lang.Object annotated with *
  while locating org.apache.maven.artifact.installer.DefaultArtifactInstaller
Caused by: java.lang.IllegalArgumentException: Can not set org.eclipse.aether.spi.log.Logger field org.apache.maven.repository.internal.DefaultVersionRangeResolver.logger to org.eclipse.aether.internal.impl.slf4j.Slf4jLoggerFactory
    at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:167)
    at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:171)
    at sun.reflect.UnsafeObjectFieldAccessorImpl.set(UnsafeObjectFieldAccessorImpl.java:81)
    at java.lang.reflect.Field.set(Field.java:764)
    at org.eclipse.sisu.bean.BeanPropertyField.set(BeanPropertyField.java:72)
    at org.eclipse.sisu.plexus.ProvidedPropertyBinding.injectProperty(ProvidedPropertyBinding.java:48)
    at org.eclipse.sisu.bean.BeanInjector.injectMembers(BeanInjector.java:52)
    at com.google.inject.internal.MembersInjectorImpl.injectMembers(MembersInjectorImpl.java:140)
    at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:117)
    at com.google.inject.internal.ConstructorInjector.access$000(ConstructorInjector.java:32)
    at com.google.inject.internal.ConstructorInjector$1.call(ConstructorInjector.java:92)
    at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:115)
    at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.j
SNIP
```

User is running java 8 Eclipse (for Java) Oxygen and a maven 3.6.1 installation
<img width="527" alt="Screen Shot 2020-10-26 at 9 47 04 am" src="https://user-images.githubusercontent.com/23282299/97345772-67219000-1882-11eb-897f-bc6366d525cc.png">
[maven.log.txt](https://github.com/galasa-dev/projectmanagement/files/5447336/maven.log.txt)
[com.example.tests.parent.zip](https://github.com/galasa-dev/projectmanagement/files/5447337/com.example.tests.parent.zip)

**Comment by hobbit1983** [comment]
@Michael-Baylis This is the defect I spoke to you about this afternoon - could you take a look please?

**Comment by enver-haase** [comment]
Had the same error in another project. Upgrading Maven to 3.8.4 helped.
