### ISSUE TITLE
Galasa 3270 locking up during local runs

### ISSUE THREAD

**Issue by bigrichie3** [galasa-dev/projectmanagement#527]
It appears that galasa seems to be locking up during local runs

**Comment by hobbit1983** [comment]
Hi Richard.  do you have a run log from a failing run for us to take a look at?

**Comment by bigrichie3** [comment]
hey Will, sorry, yes I do. I had already sent it to Michael a few weeks ago. He requested a Java dump as well.  I will attach them both
[javadump-MAC.txt](https://github.com/galasa-dev/projectmanagement/files/5625861/javadump-MAC.txt)
[JAT_IPSecCertificateDiagnostics_2020-11-12-16.15.34 (1).zip](https://github.com/galasa-dev/projectmanagement/files/5625863/JAT_IPSecCertificateDiagnostics_2020-11-12-16.15.34.1.zip)

**Comment by hobbit1983** [comment]
Awesome. I'll catch up with Mike first then.

**Comment by bigrichie3** [comment]
I forgot to mention, I have also experienced issues with this on Windows, but it seems to happen fairly consistent on a MAC

**Comment by Michael-Baylis** [comment]
I believe I have updated the code to single thread the screen updates to eclipse,   would you please update the plugin and retry with the terminals unsuppressed.

**Comment by Michael-Baylis** [comment]
@bigrichie3 I have run multiple testing using multithreaded terminals and it all works perfectly.   I have lost track of what the current exceptions are.   Would you please paste the latest stacktraces in here.

**Comment by bigrichie3** [comment]
Exception in thread "Thread-9" java.lang.ArrayIndexOutOfBoundsException
	at java.io.Bits.putChar(Bits.java:100)
	at java.io.ObjectOutputStream$BlockDataOutputStream.writeChars(ObjectOutputStream.java:2078)
	at java.io.ObjectOutputStream.writeArray(ObjectOutputStream.java:1392)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1202)
	at java.io.ObjectOutputStream.writeArray(ObjectOutputStream.java:1416)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1202)
	at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1586)
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1547)
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1470)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1206)
	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:368)
	at com.ibm.jat.zosterminal.internal.resources.Zos3270TerminalImpl.sendToRT(Zos3270TerminalImpl.java:947)
	at com.ibm.jat.zosterminal.internal.resources.Zos3270TerminalImpl.sendScreen(Zos3270TerminalImpl.java:934)
	at com.ibm.jat.zosterminal.internal.resources.Zos3270TerminalImpl.access$11(Zos3270TerminalImpl.java:929)
	at com.ibm.jat.zosterminal.internal.resources.Zos3270TerminalImpl$ScreenListener.screenUpdated(Zos3270TerminalImpl.java:1013)
	at dev.galasa.zos3270.spi.Screen.processOrders(Screen.java:489)
	at dev.galasa.zos3270.spi.Screen.processInboundMessage(Screen.java:187)
	at dev.galasa.zos3270.internal.comms.NetworkThread.processMessage(NetworkThread.java:174)
	at dev.galasa.zos3270.internal.comms.NetworkThread.run(NetworkThread.java:132)

**Comment by bigrichie3** [comment]
4:29:18 INFO [pool-3-thread-2] com.ibm.jat.zosterminal.internal.resources.Zos3270TerminalImpl - POKVMY.MVS074.mvsConsole.B: Sending 'K' to the terminal
14:29:18 INFO [pool-3-thread-1] com.ibm.jat.zosterminal.internal.resources.Zos3270TerminalImpl - POKVMY.MVS149.mvsConsole.A: Sending 'K' to the terminal
com.ibm.jat.zosterminal.exceptions.TerminalException: Failed to send screen to queue
	at com.ibm.jat.zosterminal.internal.resources.Zos3270TerminalImpl.sendToRT(Zos3270TerminalImpl.java:961)
	at com.ibm.jat.zosterminal.internal.resources.Zos3270TerminalImpl.sendScreen(Zos3270TerminalImpl.java:934)
	at com.ibm.jat.zosterminal.internal.resources.Zos3270TerminalImpl.access$11(Zos3270TerminalImpl.java:929)
	at com.ibm.jat.zosterminal.internal.resources.Zos3270TerminalImpl$ScreenListener.screenUpdated(Zos3270TerminalImpl.java:1013)
	at com.ibm.jat.zosterminal.internal.resources.Zos3270TerminalImpl.sendText(Zos3270TerminalImpl.java:312)
	at com.ibm.jat.zosterminal.internal.resources.Zos3270TerminalImpl.sendText(Zos3270TerminalImpl.java:279)
	at com.ibm.jat.zosterminal.internal.resources.Zos3270TerminalImpl.sendTextWithEnter(Zos3270TerminalImpl.java:326)
	at com.ibm.jat.zosterminal.internal.resources.Zos3270TerminalImpl.sendTextWithEnter(Zos3270TerminalImpl.java:321)
	at com.ibm.jat.ensclient.EnsService.clearConsoleScreen(EnsService.java:465)
	at com.ibm.jat.ensclient.EnsService.isStarted(EnsService.java:379)
	at com.ibm.jat.ensclient.EnsService.stop(EnsService.java:327)
	at com.ibm.ens.ejat.environments.ConfigAssistTestEnvironment.stopService(ConfigAssistTestEnvironment.java:2677)
	at com.ibm.ens.ejat.environments.ConfigAssistTestEnvironment$8.run(ConfigAssistTestEnvironment.java:2649)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:267)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1143)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:618)
	at java.lang.Thread.run(Thread.java:785)
Caused by: com.ibm.cics.jatp.exceptions.OutputRepositoryException: java.lang.NullPointerException
	at com.ibm.cics.jatp.junit.internal.runner.LocalOutputRepository.updateScreen(LocalOutputRepository.java:316)
	at com.ibm.jat.zosterminal.internal.resources.Zos3270TerminalImpl.sendToRT(Zos3270TerminalImpl.java:959)
	... 17 more
Caused by: java.lang.NullPointerException
	at com.sun.xml.internal.bind.v2.runtime.Coordinator.popCoordinator(Coordinator.java:157)
	at com.sun.xml.internal.bind.v2.runtime.XMLSerializer.close(XMLSerializer.java:859)
	at com.sun.xml.internal.bind.v2.runtime.MarshallerImpl.write(MarshallerImpl.java:329)
	at com.sun.xml.internal.bind.v2.runtime.MarshallerImpl.marshal(MarshallerImpl.java:248)
	at javax.xml.bind.helpers.AbstractMarshallerImpl.marshal(AbstractMarshallerImpl.java:114)
	at com.ibm.cics.jatp.junit.internal.runner.LocalOutputRepository.updateScreen(LocalOutputRepository.java:314)
	... 18 more
i'm getting these messages fairly frequently when i'm running locally

**Comment by Michael-Baylis** [comment]
I have added diagnostic messages.   Please accept from DEV and rerun,  return the diagnostic messages and the stacktraces please

**Comment by Michael-Baylis** [comment]
I had discovered that the single threaded change I made I applied to the cics version of the terminal,   not the zos version.   I applied it correctly and the problem seems to have gone away.

Closing the issue.   If the problem returns, please comment here and I will reopen
