### ISSUE TITLE
BackupCPS fails with `ClosedByInterruptException` - intermittent.

### ISSUE THREAD

**Issue by matthewchivers** [galasa-dev/projectmanagement#570]
Currently occurs when backing up properties from a remote ecosystem. Suspect content (to be written) size is a factor - though avoiding the actual interrupt may be preferable.

Need to investigate and fix. Possibly to do with a local environment setup. Tracking here just in case.

Example output of failure in logs:
```
28/01/2021 09:52:41.387 ERROR d.g.f.BackupCPS - Failed to save CPS properties: 
java.nio.channels.ClosedByInterruptException
	at java.nio.channels.spi.AbstractInterruptibleChannel.end(AbstractInterruptibleChannel.java:202)
	at sun.nio.ch.FileChannelImpl.write(FileChannelImpl.java:216)
	at java.nio.channels.Channels.writeFullyImpl(Channels.java:78)
	at java.nio.channels.Channels.writeFully(Channels.java:101)
	at java.nio.channels.Channels.access$000(Channels.java:61)
	at java.nio.channels.Channels$1.write(Channels.java:174)
	at java.nio.file.Files.write(Files.java:3297)
	at dev.galasa.framework.BackupCPS.outputCPSProperties(BackupCPS.java:103)
	at dev.galasa.framework.BackupCPS.backup(BackupCPS.java:70)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at dev.galasa.boot.felix.FelixFramework.runBackupCPS(FelixFramework.java:483)
	at dev.galasa.boot.Launcher.launch(Launcher.java:181)
	at dev.galasa.boot.Launcher.main(Launcher.java:117)
28/01/2021 09:52:41.389 INFO  d.g.f.BackupCPS - Ending CPS Backup Service
28/01/2021 09:52:41.389 INFO  d.g.f.Framework - Shutting down the framework
28/01/2021 09:52:41.395 INFO  d.g.f.Framework - Framework shutdown
28/01/2021 09:52:41.396 DEBUG dev.galasa.boot.felix.FelixFramework.stopFramework - Stopping Felix framework
28/01/2021 09:52:41.400 INFO  d.g.f.Framework - Framework service deactivated
```

**Comment by matthewchivers** [comment]
This interrupt exception was being triggered by a `CompletableFuture` that was throwing a `ExecutionException`. This exception was being caught by a `multi-catch` which calls `Thread.currentThread().interrupt()`.

The `ExecutionException` (in this case) was being thrown due to database unavailability - which means the triggering of an interrupt was unnecessary.

I have been working on a fix to ensure that this won't happen in the future and will be pushing shortly.

**Comment by matthewchivers** [comment]
Turns out this was a bad VPN connection causing the IO unavailability.

Still ought to alter this so that connections are less fragile, but this specific issue (connection dropping and unavailable IO) has been solved.

**Comment by Michael-Baylis** [comment]
A more generic connection restart is required rather than something specific to etcd
