### ISSUE TITLE
Docker based Galasa installation fails

### ISSUE THREAD

**Issue by AnboAnbo** [galasa-dev/projectmanagement#583]
Note:
The ticket will be followed up in internal channel.

By following the installation guide - https://galasa.dev/docs/ecosystem/installing,    I am trying to install galasa on my linux server and hit following errors:

Inactive hide details for Docker Installation ErrorDocker Installation Error
Docker Installation Error
```
[shipeng@proto18 galasa]$ sudo docker run -it -v /var/run/docker.sock:/var/run/docker.sock -v `pwd`/config.yaml:/config.yaml docker.galasa.dev/galasa-docker-operator-amd64:0.9.0
Unable to find image 'docker.galasa.dev/galasa-docker-operator-amd64:0.9.0' locally
Trying to pull repository docker.galasa.dev/galasa-docker-operator-amd64 ...
0.9.0: Pulling from docker.galasa.dev/galasa-docker-operator-amd64
e9afc4f90ab0: Pull complete
989e6b19a265: Pull complete
af14b6c2f878: Pull complete
5573c4b30949: Pull complete
fb1a405f128d: Pull complete
197b0f525c26: Pull complete
f133ed18caca: Pull complete
92ae62811b77: Pull complete
b8178fe31c92: Pull complete
Digest: sha256:a88483e958de78025917a321f5b914a275603426d141b05877759edfe3006108
Status: Downloaded newer image for docker.galasa.dev/galasa-docker-operator-amd64:0.9.0
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Exception in thread "main" dev.galasa.docker.operator.DockerOperatorException: Unable to load configuration
at dev.galasa.docker.operator.DockerOperator.loadConfiguration(DockerOperator.java:121)
at dev.galasa.docker.operator.DockerOperator.run(DockerOperator.java:55)
at dev.galasa.docker.operator.DockerOperator.main(DockerOperator.java:158)
Caused by: mapping values are not allowed here
 in 'reader', line 6, column 26:
                engineVersion: 0.9.0
                             ^

at org.yaml.snakeyaml.scanner.ScannerImpl.fetchValue(ScannerImpl.java:872)
at org.yaml.snakeyaml.scanner.ScannerImpl.fetchMoreTokens(ScannerImpl.java:360)
at org.yaml.snakeyaml.scanner.ScannerImpl.checkToken(ScannerImpl.java:226)
at org.yaml.snakeyaml.parser.ParserImpl$ParseBlockMappingKey.produce(ParserImpl.java:557)
at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:157)
at org.yaml.snakeyaml.parser.ParserImpl.checkEvent(ParserImpl.java:147)
at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:227)
at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:154)
at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:249)
at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:240)
at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:228)
at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:154)
at org.yaml.snakeyaml.composer.Composer.composeDocument(Composer.java:122)
at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:105)
at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:140)
at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:524)
at org.yaml.snakeyaml.Yaml.loadAs(Yaml.java:518)
at dev.galasa.docker.operator.DockerOperator.loadConfiguration(DockerOperator.java:111)
... 2 more
Shutdown request received
[shipeng@proto18 galasa]$ ls
config.yaml
[shipeng@proto18 galasa]$ cat config.yaml
hostname: proto18.tuc.stglabs.ibm.com
galasaRegistry: docker.galasa.dev
version: 0.9.0
engineController:
      controllerVersion: 0.10.0
            engineVersion: 0.9.0

```

System Kernel Info
```
[shipeng@proto18 ~]$ uname -a
Linux proto18 3.10.0-1160.11.1.el7.x86_64 #1 SMP Mon Nov 30 13:05:31 EST 2020 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by matthewchivers** [comment]
Can you check the tabs before `engineVersion: 0.9.0` ?
Yaml is particularly fragile to incorrect tab spacing, and the `cat` of the config file at the end looks like you may have more whitespace than necessary (two spaces are recommended in [the guide](https://galasa.dev/docs/ecosystem/installing)).
```
hostname: proto18.tuc.stglabs.ibm.com
galasaRegistry: docker.galasa.dev
version: 0.9.0
engineController:
      controllerVersion: 0.10.0
            engineVersion: 0.9.0
```
Should be:
```
hostname: proto18.tuc.stglabs.ibm.com
galasaRegistry: docker.galasa.dev
version: 0.9.0
engineController:
    controllerVersion: 0.10.0
    engineVersion: 0.9.0
```

**Comment by Michael-Baylis** [comment]
There should be no tabs at all.    Yaml expects 2 spaces for indentation.   Anything else is subject to the interpreter being nice.

**Comment by AnboAnbo** [comment]
thank you, @matthewchivers 
fixing the indent solved the problem.
while I hit following errors complaining about 8080 occupied, please let me know I should open another ticket.

Is there a way to have this API(or bootstrap) port configurable?

thanks!

```
[root@proto18 galasa]# docker run -it -v /var/run/docker.sock:/var/run/docker.sock -v `pwd`/config.yaml:/config.yaml docker.galasa.dev/galasa-docker-operator-amd64:0.9.0
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Using the following configuration:-
!!dev.galasa.docker.operator.config.EcosystemConfiguration
api:
  extraBundles: dev.galasa.cps.etcd,dev.galasa.ras.couchdb
  image: galasa-boot-embedded-amd64
  port: 8080
cps:
  image: quay.io/coreos/etcd
  port: 2379
  version: v3.4.9
engineController:
  controllerImage: galasa-boot-embedded-amd64
  controllerVersion: 0.10.0
  engineImage: galasa-boot-embedded-amd64
  engineVersion: 0.9.0
  maxEngines: 2
galasaRegistry: docker.galasa.dev
hostname: proto18.tuc.stglabs.ibm.com
jenkins:
  image: jenkins/jenkins
  port: 8082
  version: '2.243'
metrics:
  image: galasa-boot-embedded-amd64
nexus:
  image: sonatype/nexus3
  port: 8081
  version: 3.24.0
ras:
  image: couchdb
  port: 5984
  version: 2.3.1
resourceManagement:
  image: galasa-boot-embedded-amd64
simplatform:
  databasePort: 2027
  image: galasa-boot-embedded-amd64
  telnetPort: 2023
  webservicePort: 2080
  zosmfPort: 2040
version: 0.9.0

CPS Volume is missing
CPS volume created
Pulling CPS image 'quay.io/coreos/etcd:v3.4.9'
Defining the CPS container
RAS Volume is missing
RAS volume created
Pulling CPS image 'couchdb:2.3.1'
Defining the RAS container
Testcatalog Volume is missing
Testcatalog volume created
Pulling CPS image 'docker.galasa.dev/galasa-boot-embedded-amd64:0.9.0'
Defining the API container
Defining the RESMON container
Defining the METRICS container
Pulling CPS image 'docker.galasa.dev/galasa-boot-embedded-amd64:0.10.0'
Defining the ENGINE container
Nexus volume is missing
Creating Nexus volume seeding container
Pulling image 'docker.galasa.dev/galasa-seed-amd64:0.9.0'
Starting Nexus volume seeding container
Deleteing Nexus volume seeding container
Nexus volume created
Pulling CPS image 'sonatype/nexus3:3.24.0'
Defining the Nexus container
Jenkins volume is missing
Creating Jenkins volume seeding container
Starting Jenkins volume seeding container
Deleteing Jenkins volume seeding container
Jenkins volume created
Pulling CPS image 'jenkins/jenkins:2.243'
Defining the Jenkins container
Defining the SIMPLATFORM container
CPS Container is down, requires start up
Starting CPS container
CPS container is up
Setting CPS property 'framework.credentials.store' with 'etcd:http://proto18.tuc.stglabs.ibm.com:2379'
Setting CPS property 'framework.dynamicstatus.store' with 'etcd:http://proto18.tuc.stglabs.ibm.com:2379'
RAS Container is down, requires start up
Starting RAS container
RAS container is up
Setting CPS property 'framework.resultarchive.store' with 'couchdb:http://proto18.tuc.stglabs.ibm.com:5984'
API Container is down, requires start up
Starting API container
Exception in thread "main" dev.galasa.docker.operator.DockerOperatorException: Problem starting API container
	at dev.galasa.docker.operator.model.Api.checkContainerRunning(Api.java:286)
	at dev.galasa.docker.operator.model.Api.checkResourceRunning(Api.java:198)
	at dev.galasa.docker.operator.model.Ecosystem.checkResourcesRunning(Ecosystem.java:76)
	at dev.galasa.docker.operator.DockerOperator.run(DockerOperator.java:61)
	at dev.galasa.docker.operator.DockerOperator.main(DockerOperator.java:158)
Caused by: dev.galasa.docker.operator.DockerOperatorException: Problem starting 'galasa_api' container
	at dev.galasa.docker.operator.model.AbstractContainerResource.startContainer(AbstractContainerResource.java:172)
	at dev.galasa.docker.operator.model.Api.checkContainerRunning(Api.java:284)
	... 4 more
Caused by: com.github.dockerjava.api.exception.InternalServerErrorException: Status 500: {"message":"driver failed programming external connectivity on endpoint galasa_api (85bc4cc4d26448ebcfe8a93940f4287968705bb6ce1548c65802be726b896a7d): Error starting userland proxy: listen tcp 0.0.0.0:8080: bind: address already in use"}

	at com.github.dockerjava.core.DefaultInvocationBuilder.execute(DefaultInvocationBuilder.java:247)
	at com.github.dockerjava.core.DefaultInvocationBuilder.post(DefaultInvocationBuilder.java:103)
	at com.github.dockerjava.core.exec.StartContainerCmdExec.execute(StartContainerCmdExec.java:31)
	at com.github.dockerjava.core.exec.StartContainerCmdExec.execute(StartContainerCmdExec.java:13)
	at com.github.dockerjava.core.exec.AbstrSyncDockerCmdExec.exec(AbstrSyncDockerCmdExec.java:21)
	at com.github.dockerjava.core.command.AbstrDockerCmd.exec(AbstrDockerCmd.java:35)
	at com.github.dockerjava.core.command.StartContainerCmdImpl.exec(StartContainerCmdImpl.java:43)
	at dev.galasa.docker.operator.model.AbstractContainerResource.startContainer(AbstractContainerResource.java:170)
	... 5 more
Shutdown request received
```

**Comment by Michael-Baylis** [comment]
Amend the config yaml to set the API port:-
api:
  port: 8080

**Comment by AnboAnbo** [comment]
hit the same error after setting to port to 9080
### Config.yaml
```
[root@proto18 galasa]# cat config.yaml
hostname: proto18.tuc.stglabs.ibm.com
galasaRegistry: docker.galasa.dev
version: 0.9.0
engineController:
    controllerVersion: 0.10.0
    engineVersion: 0.9.0
api:
  port: 9080
```

### Error 
```
[root@proto18 galasa]# docker run -it -v /var/run/docker.sock:/var/run/docker.sock -v `pwd`/config.yaml:/config.yaml docker.galasa.dev/galasa-docker-operator-amd64:0.9.0
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Using the following configuration:-
!!dev.galasa.docker.operator.config.EcosystemConfiguration
api:
  extraBundles: dev.galasa.cps.etcd,dev.galasa.ras.couchdb
  image: galasa-boot-embedded-amd64
  port: 9080
cps:
  image: quay.io/coreos/etcd
  port: 2379
  version: v3.4.9
engineController:
  controllerImage: galasa-boot-embedded-amd64
  controllerVersion: 0.10.0
  engineImage: galasa-boot-embedded-amd64
  engineVersion: 0.9.0
  maxEngines: 2
galasaRegistry: docker.galasa.dev
hostname: proto18.tuc.stglabs.ibm.com
jenkins:
  image: jenkins/jenkins
  port: 8082
  version: '2.243'
metrics:
  image: galasa-boot-embedded-amd64
nexus:
  image: sonatype/nexus3
  port: 8081
  version: 3.24.0
ras:
  image: couchdb
  port: 5984
  version: 2.3.1
resourceManagement:
  image: galasa-boot-embedded-amd64
simplatform:
  databasePort: 2027
  image: galasa-boot-embedded-amd64
  telnetPort: 2023
  webservicePort: 2080
  zosmfPort: 2040
version: 0.9.0

API Container is down, requires start up
Starting API container
Exception in thread "main" dev.galasa.docker.operator.DockerOperatorException: Problem starting API container
	at dev.galasa.docker.operator.model.Api.checkContainerRunning(Api.java:286)
	at dev.galasa.docker.operator.model.Api.checkResourceRunning(Api.java:198)
	at dev.galasa.docker.operator.model.Ecosystem.checkResourcesRunning(Ecosystem.java:76)
	at dev.galasa.docker.operator.DockerOperator.run(DockerOperator.java:61)
	at dev.galasa.docker.operator.DockerOperator.main(DockerOperator.java:158)
Caused by: dev.galasa.docker.operator.DockerOperatorException: Problem starting 'galasa_api' container
	at dev.galasa.docker.operator.model.AbstractContainerResource.startContainer(AbstractContainerResource.java:172)
	at dev.galasa.docker.operator.model.Api.checkContainerRunning(Api.java:284)
	... 4 more
Caused by: com.github.dockerjava.api.exception.InternalServerErrorException: Status 500: {"message":"driver failed programming external connectivity on endpoint galasa_api (c904fdba135657632ed1a1720ab1e05224e66036f54b587c22fa5718225c3b90): Error starting userland proxy: listen tcp 0.0.0.0:8080: bind: address already in use"}

	at com.github.dockerjava.core.DefaultInvocationBuilder.execute(DefaultInvocationBuilder.java:247)
	at com.github.dockerjava.core.DefaultInvocationBuilder.post(DefaultInvocationBuilder.java:103)
	at com.github.dockerjava.core.exec.StartContainerCmdExec.execute(StartContainerCmdExec.java:31)
	at com.github.dockerjava.core.exec.StartContainerCmdExec.execute(StartContainerCmdExec.java:13)
	at com.github.dockerjava.core.exec.AbstrSyncDockerCmdExec.exec(AbstrSyncDockerCmdExec.java:21)
	at com.github.dockerjava.core.command.AbstrDockerCmd.exec(AbstrDockerCmd.java:35)
	at com.github.dockerjava.core.command.StartContainerCmdImpl.exec(StartContainerCmdImpl.java:43)
	at dev.galasa.docker.operator.model.AbstractContainerResource.startContainer(AbstractContainerResource.java:170)
	... 5 more
Shutdown request received
```

**Comment by Michael-Baylis** [comment]
Will have a look

**Comment by AnboAnbo** [comment]
any update on this matter?
thx

**Comment by Michael-Baylis** [comment]
it is at the top of my list,  had a quick look yesterday and didn't understand why it wasn't working,  then realised you are using a very old version,  so need to check if the defect was in 9

**Comment by Michael-Baylis** [comment]
ok,  I have tested this left right and centre.
It should work.
For starters,  please try using 0.14.0.
Second,  when it fails, would you please do a docker inspect galasa_api.

**Comment by AnboAnbo** [comment]
while, in that installation guide - [https://galasa.dev/docs/ecosystem/installing](https://galasa.dev/docs/ecosystem/installing), there are 3 occurrence of "0.9.0", in the config.yaml & the docker run command. I changed all 3 to 0.14.0 and hoped my guess was right.

here it goes:
1. Error when run docker run
```
$ sudo docker run -it -v /var/run/docker.sock:/var/run/docker.sock -v `pwd`/config.yaml:/config.yaml docker.galasa.dev/galasa-docker-operator-amd64:0.14.0
Unable to find image 'docker.galasa.dev/galasa-docker-operator-amd64:0.14.0' locally
Trying to pull repository docker.galasa.dev/galasa-docker-operator-amd64 ...
0.14.0: Pulling from docker.galasa.dev/galasa-docker-operator-amd64
50e431f79093: Already exists
dd8c6d374ea5: Already exists
c85513200d84: Already exists
55769680e827: Already exists
e27ce2095ec2: Already exists
5943eea6cb7c: Already exists
3ed8ceae72a6: Already exists
af742cd23404: Pull complete
92c93f239a60: Pull complete
Digest: sha256:8e8a8d20f3846ccee252bccaad3f40fddf2e4384f1da400677bd7ac1610d9d00
Status: Downloaded newer image for docker.galasa.dev/galasa-docker-operator-amd64:0.14.0
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Using the following configuration:-
!!dev.galasa.docker.operator.config.EcosystemConfiguration
api:
  extraBundles: dev.galasa.cps.etcd,dev.galasa.ras.couchdb
  image: galasa-boot-embedded-amd64
  port: 9080
cps:
  image: quay.io/coreos/etcd
  port: 2379
  version: v3.4.9
engineController:
  controllerImage: galasa-boot-embedded-amd64
  controllerVersion: 0.10.0
  engineImage: galasa-boot-embedded-amd64
  engineVersion: 0.14.0
  maxEngines: 2
galasaRegistry: docker.galasa.dev
hostname: proto18.tuc.stglabs.ibm.com
jenkins:
  image: jenkins/jenkins
  port: 8082
  version: '2.243'
metrics:
  image: galasa-boot-embedded-amd64
  port: 9010
nexus:
  image: sonatype/nexus3
  port: 8081
  version: 3.24.0
ras:
  image: couchdb
  port: 5984
  version: 2.3.1
resourceManagement:
  image: galasa-boot-embedded-amd64
simplatform:
  databasePort: 2027
  image: galasa-boot-embedded-amd64
  telnetPort: 2023
  webservicePort: 2080
  zosmfPort: 2040
version: 0.14.0

Defining the API container
Defining the SIMPLATFORM container
API Container is down, requires start up
Starting API container
Failed to detect API up message, deleting container to force rebuild
Exception in thread "main" dev.galasa.docker.operator.DockerOperatorException: Problem waiting for API container started message
	at dev.galasa.docker.operator.model.Api.checkContainerRunning(Api.java:313)
	at dev.galasa.docker.operator.model.Api.checkResourceRunning(Api.java:198)
	at dev.galasa.docker.operator.model.Ecosystem.checkResourcesRunning(Ecosystem.java:76)
	at dev.galasa.docker.operator.DockerOperator.run(DockerOperator.java:61)
	at dev.galasa.docker.operator.DockerOperator.main(DockerOperator.java:158)
Caused by: dev.galasa.docker.operator.DockerOperatorException: Failed to detect 'API server has started' in time in container 'galasa_api'
	at dev.galasa.docker.operator.model.AbstractContainerResource.checkLog(AbstractContainerResource.java:205)
	at dev.galasa.docker.operator.model.Api.checkContainerRunning(Api.java:307)
	... 4 more
Shutdown request received
```

2. config.yaml
```
$ cat config.yaml
hostname: proto18.tuc.stglabs.ibm.com
galasaRegistry: docker.galasa.dev
version: 0.14.0
engineController:
    controllerVersion: 0.10.0
    engineVersion: 0.14.0
api:
  port: 9080
```

3. docker inspect galasa_api(tried after docker run with 0.14.0 and with 0.9.0)
```
$ sudo docker inspect galasa_api
[]
Error: No such object: galasa_api
```

4. systemctl status docker
```
$ systemctl status docker
● docker.service - Docker Application Container Engine
   Loaded: loaded (/usr/lib/systemd/system/docker.service; enabled; vendor preset: disabled)
   Active: active (running) since Mon 2021-02-15 12:00:05 MST; 1 day 20h ago
     Docs: http://docs.docker.com
 Main PID: 63028 (dockerd-current)
    Tasks: 70
   Memory: 669.1M
   CGroup: /system.slice/docker.service
           ├─31728 /usr/libexec/docker/docker-proxy-current -proto tcp -host-ip 0.0.0.0 -host-port 2379 -container-ip 172.17.0.3...
           ├─31736 /usr/bin/docker-containerd-shim-current 3345f843b41db6686bfa0d8bb5aa9e0389b24845e59b9270ca140e232e5e952b /var...
           ├─31883 /usr/libexec/docker/docker-proxy-current -proto tcp -host-ip 0.0.0.0 -host-port 5984 -container-ip 172.17.0.4...
           ├─31891 /usr/bin/docker-containerd-shim-current 8c423d54ecc57e5211b2fd4f07e99e5cefcc2485d5445424efb398e390943c45 /var...
           ├─63028 /usr/bin/dockerd-current --add-runtime docker-runc=/usr/libexec/docker/docker-runc-current --default-runtime=...
           └─63044 /usr/bin/docker-containerd-current -l unix:///var/run/docker/libcontainerd/docker-containerd.sock --metrics-i...

Feb 17 08:24:55 proto18.tuc.stglabs.ibm.com dockerd-current[63028]: {database_does_not_exist,[{mem3_shards,load_shards_from_...ocid
Feb 17 08:24:55 proto18.tuc.stglabs.ibm.com dockerd-current[63028]:
Feb 17 08:25:00 proto18.tuc.stglabs.ibm.com dockerd-current[63028]: [notice] 2021-02-17T15:25:00.758396Z nonode@nohost <0.330.0>...
Feb 17 08:25:00 proto18.tuc.stglabs.ibm.com dockerd-current[63028]: [error] 2021-02-17T15:25:00.758514Z nonode@nohost emulat...lue:
Feb 17 08:25:00 proto18.tuc.stglabs.ibm.com dockerd-current[63028]: {database_does_not_exist,[{mem3_shards,load_shards_from_...ocid
Feb 17 08:25:00 proto18.tuc.stglabs.ibm.com dockerd-current[63028]:
Feb 17 08:25:05 proto18.tuc.stglabs.ibm.com dockerd-current[63028]: [notice] 2021-02-17T15:25:05.760323Z nonode@nohost <0.330.0>...
Feb 17 08:25:05 proto18.tuc.stglabs.ibm.com dockerd-current[63028]: [error] 2021-02-17T15:25:05.760418Z nonode@nohost emulat...lue:
Feb 17 08:25:05 proto18.tuc.stglabs.ibm.com dockerd-current[63028]: {database_does_not_exist,[{mem3_shards,load_shards_from_...ocid
Feb 17 08:25:05 proto18.tuc.stglabs.ibm.com dockerd-current[63028]:
Hint: Some lines were ellipsized, use -l to show in full.
```
5.  syslog during docker run
```
Feb 17 08:21:45 proto18.tuc.stglabs.ibm.com dockerd-current[63028]: [notice] 2021-02-17T15:21:45.668476Z nonode@nohost <0.330.0> -------- chttpd_auth_cache changes listener died database_does_not_exist at mem3_shards:load_shards_from_db/6(line:395) <= mem3_shards:load_shards_from_disk/1(line:370) <= mem3_shards:load_shards_from_disk/2(line:399) <= mem3_shards:for_docid/3(line:86) <= fabric_doc_open:go/3(line:39) <= chttpd_auth_cache:ensure_auth_ddoc_exists/2(line:195) <= chttpd_auth_cache:listen_for_changes/1(line:142)
Feb 17 08:21:45 proto18.tuc.stglabs.ibm.com dockerd-current[63028]: [error] 2021-02-17T15:21:45.668583Z nonode@nohost emulator -------- Error in process <0.24013.0> with exit value:
Feb 17 08:21:45 proto18.tuc.stglabs.ibm.com dockerd-current[63028]: {database_does_not_exist,[{mem3_shards,load_shards_from_db,"_users",[{file,"src/mem3_shards.erl"},{line,395}]},{mem3_shards,load_shards_from_disk,1,[{file,"src/mem3_shards.erl"},{line,370}]},{mem3_shards,load_shards_from_disk,2,[{file,"src/mem3_shards.erl"},{line,399}]},{mem3_shards,for_docid,3,[{file,"src/mem3_shards.erl"},{line,86}]},{fabric_doc_open,go,3,[{file,"src/fabric_doc_open.erl"},{line,39}]},{chttpd_auth_cache,ensure_auth_ddoc_exists,2,[{file,"src/chttpd_auth_cache.erl"},{line,195}]},{chttpd_auth_cache,listen_for_changes,1,[{file,"src/chttpd_auth_cache.erl"},{line,142}]}]}
Feb 17 08:21:45 proto18.tuc.stglabs.ibm.com dockerd-current[63028]:
Feb 17 08:21:46 proto18.tuc.stglabs.ibm.com dockerd-current[63028]: [69B blob data]
Feb 17 08:21:46 proto18.tuc.stglabs.ibm.com oci-systemd-hook[37250]: systemdhook <debug>: 150dffb0b30c: Skipping as container command is java, not init or systemd
Feb 17 08:21:46 proto18.tuc.stglabs.ibm.com oci-umount[37251]: umounthook <debug>: 150dffb0b30c: only runs in prestart stage, ignoring
Feb 17 08:21:47 proto18.tuc.stglabs.ibm.com kernel: docker0: port 4(veth3559de8) entered disabled state
Feb 17 08:21:47 proto18.tuc.stglabs.ibm.com avahi-daemon[763]: Withdrawing address record for fe80::744a:edff:fe6a:3678 on veth3559de8.
Feb 17 08:21:47 proto18.tuc.stglabs.ibm.com kernel: docker0: port 4(veth3559de8) entered disabled state
Feb 17 08:21:47 proto18.tuc.stglabs.ibm.com avahi-daemon[763]: Withdrawing workstation service for veth918f5a2.
Feb 17 08:21:47 proto18.tuc.stglabs.ibm.com kernel: device veth3559de8 left promiscuous mode
Feb 17 08:21:47 proto18.tuc.stglabs.ibm.com kernel: docker0: port 4(veth3559de8) entered disabled state
Feb 17 08:21:47 proto18.tuc.stglabs.ibm.com avahi-daemon[763]: Withdrawing workstation service for veth3559de8.
Feb 17 08:21:47 proto18.tuc.stglabs.ibm.com libvirtd[1227]: 2021-02-17 15:21:47.154+0000: 1665: error : virNetDevSendEthtoolIoctl:3078 : ethtool ioctl error: No such device
Feb 17 08:21:47 proto18.tuc.stglabs.ibm.com libvirtd[1227]: 2021-02-17 15:21:47.169+0000: 1665: error : virNetDevSendEthtoolIoctl:3078 : ethtool ioctl error: No such device
Feb 17 08:21:47 proto18.tuc.stglabs.ibm.com libvirtd[1227]: 2021-02-17 15:21:47.185+0000: 1665: error : virNetDevSendEthtoolIoctl:3078 : ethtool ioctl error: No such device
Feb 17 08:21:47 proto18.tuc.stglabs.ibm.com libvirtd[1227]: 2021-02-17 15:21:47.203+0000: 1665: error : virNetDevSendEthtoolIoctl:3078 : ethtool ioctl error: No such device
Feb 17 08:21:47 proto18.tuc.stglabs.ibm.com dockerd-current[63028]: time="2021-02-17T08:21:47.203844517-07:00" level=warning msg="150dffb0b30cbd6dcb83bd77d784c109b92656a16c5b487adeb6b25971a8336e cleanup: failed to unmount secrets: invalid argument"
Feb 17 08:21:47 proto18.tuc.stglabs.ibm.com libvirtd[1227]: 2021-02-17 15:21:47.218+0000: 1665: error : virNetDevSendEthtoolIoctl:3078 : ethtool ioctl error: No such device
Feb 17 08:21:47 proto18.tuc.stglabs.ibm.com libvirtd[1227]: 2021-02-17 15:21:47.238+0000: 1665: error : virNetDevSendEthtoolIoctl:3078 : ethtool ioctl error: No such device
Feb 17 08:21:47 proto18.tuc.stglabs.ibm.com libvirtd[1227]: 2021-02-17 15:21:47.253+0000: 1665: error : virNetDevSendEthtoolIoctl:3078 : ethtool ioctl error: No such device
Feb 17 08:21:47 proto18.tuc.stglabs.ibm.com libvirtd[1227]: 2021-02-17 15:21:47.271+0000: 1665: error : virNetDevSendEthtoolIoctl:3078 : ethtool ioctl error: No such device
Feb 17 08:21:47 proto18.tuc.stglabs.ibm.com dockerd-current[63028]: [129B blob data]
Feb 17 08:21:47 proto18.tuc.stglabs.ibm.com dockerd-current[63028]: [84B blob data]
Feb 17 08:21:47 proto18.tuc.stglabs.ibm.com dockerd-current[63028]: [83B blob data]
Feb 17 08:21:47 proto18.tuc.stglabs.ibm.com dockerd-current[63028]: [95B blob data]
Feb 17 08:21:47 proto18.tuc.stglabs.ibm.com dockerd-current[63028]: [81B blob data]
Feb 17 08:21:47 proto18.tuc.stglabs.ibm.com dockerd-current[63028]: [83B blob data]
Feb 17 08:21:47 proto18.tuc.stglabs.ibm.com dockerd-current[63028]: [139B blob data]
Feb 17 08:21:47 proto18.tuc.stglabs.ibm.com dockerd-current[63028]: [115B blob data]
Feb 17 08:21:47 proto18.tuc.stglabs.ibm.com dockerd-current[63028]: [84B blob data]
Feb 17 08:21:47 proto18.tuc.stglabs.ibm.com dockerd-current[63028]: [19B blob data]
Feb 17 08:21:47 proto18.tuc.stglabs.ibm.com dockerd-current[63028]: [26B blob data]
Feb 17 08:21:47 proto18.tuc.stglabs.ibm.com oci-systemd-hook[37318]: systemdhook <debug>: 5f7d3b4fe8a8: Skipping as container command is java, not init or systemd
Feb 17 08:21:47 proto18.tuc.stglabs.ibm.com oci-umount[37319]: umounthook <debug>: 5f7d3b4fe8a8: only runs in prestart stage, ignoring
Feb 17 08:21:47 proto18.tuc.stglabs.ibm.com sudo[36490]: pam_unix(sudo:session): session closed for user root
Feb 17 08:21:47 proto18.tuc.stglabs.ibm.com kernel: docker0: port 1(veth75bd993) entered disabled state
Feb 17 08:21:47 proto18.tuc.stglabs.ibm.com avahi-daemon[763]: Withdrawing address record for fe80::80aa:9eff:fe6f:b976 on veth75bd993.
Feb 17 08:21:47 proto18.tuc.stglabs.ibm.com kernel: docker0: port 1(veth75bd993) entered disabled state
Feb 17 08:21:47 proto18.tuc.stglabs.ibm.com avahi-daemon[763]: Withdrawing workstation service for vethc0f4086.
Feb 17 08:21:47 proto18.tuc.stglabs.ibm.com kernel: device veth75bd993 left promiscuous mode
Feb 17 08:21:47 proto18.tuc.stglabs.ibm.com kernel: docker0: port 1(veth75bd993) entered disabled state
Feb 17 08:21:47 proto18.tuc.stglabs.ibm.com avahi-daemon[763]: Withdrawing workstation service for veth75bd993.
Feb 17 08:21:47 proto18.tuc.stglabs.ibm.com dockerd-current[63028]: time="2021-02-17T08:21:47.587962179-07:00" level=warning msg="5f7d3b4fe8a8ac503af1b76969c9c3683dae4b7a18488f4ff87e4560ef021d23 cleanup: failed to unmount secrets: invalid argument"
Feb 17 08:21:50 proto18.tuc.stglabs.ibm.com dockerd-current[63028]: [error] 2021-02-17T15:21:50.670660Z nonode@nohost emulator -------- Error in process <0.24110.0> with exit value:
Feb 17 08:21:50 proto18.tuc.stglabs.ibm.com dockerd-current[63028]: {database_does_not_exist,[{mem3_shards,load_shards_from_db,"_users",[{file,"src/mem3_shards.erl"},{line,395}]},{mem3_shards,load_shards_from_disk,1,[{file,"src/mem3_shards.erl"},{line,370}]},{mem3_shards,load_shards_from_disk,2,[{file,"src/mem3_shards.erl"},{line,399}]},{mem3_shards,for_docid,3,[{file,"src/mem3_shards.erl"},{line,86}]},{fabric_doc_open,go,3,[{file,"src/fabric_doc_open.erl"},{line,39}]},{chttpd_auth_cache,ensure_auth_ddoc_exists,2,[{file,"src/chttpd_auth_cache.erl"},{line,195}]},{chttpd_auth_cache,listen_for_changes,1,[{file,"src/chttpd_auth_cache.erl"},{line,142}]}]}
Feb 17 08:21:50 proto18.tuc.stglabs.ibm.com dockerd-current[63028]:
Feb 17 08:21:50 proto18.tuc.stglabs.ibm.com dockerd-current[63028]: [notice] 2021-02-17T15:21:50.670752Z nonode@nohost <0.330.0> -------- chttpd_auth_cache changes listener died database_does_not_exist at mem3_shards:load_shards_from_db/6(line:395) <= mem3_shards:load_shards_from_disk/1(line:370) <= mem3_shards:load_shards_from_disk/2(line:399) <= mem3_shards:for_docid/3(line:86) <= fabric_doc_open:go/3(line:39) <= chttpd_auth_cache:ensure_auth_ddoc_exists/2(line:195) <= chttpd_auth_cache:listen_for_changes/1(line:142)
```

**Comment by Michael-Baylis** [comment]
For some reason, completly missed the last update

**Comment by Michael-Baylis** [comment]
@anboanbo I am actually now free to look at this,  what is the current status.  sorry it took so long to get to it again.

**Comment by hobbit1983** [comment]
Closed due to inactivity
