### ISSUE TITLE
Getting exception when trying to bringup galasa ecosystem with 0.15.0-SNAPSHOT

### ISSUE THREAD

**Issue by ArpanaKulenur** [galasa-dev/projectmanagement#607]
docker run -it -v /var/run/docker.sock:/var/run/docker.sock -v /galasa/config.yaml:/config.yaml docker.galasa.dev/galasa-docker-operator-amd64:0.15.0-SNAPSHOT
......
......
version: 0.15.0-SNAPSHOT
Nexus volume is missing
Creating Nexus volume seeding container
Pulling image 'docker.galasa.dev/galasa-seed-amd64:0.15.0-SNAPSHOT'
Exception in thread "main" dev.galasa.docker.operator.DockerOperatorException: Problem creating the Nexus volume
	at dev.galasa.docker.operator.model.NexusVolume.checkResourceDefined(NexusVolume.java:104)
	at dev.galasa.docker.operator.model.Ecosystem.checkResourceDefined(Ecosystem.java:70)
	at dev.galasa.docker.operator.DockerOperator.run(DockerOperator.java:59)
	at dev.galasa.docker.operator.DockerOperator.main(DockerOperator.java:158)
Caused by: dev.galasa.docker.operator.DockerOperatorException: Problem pulling 'docker.galasa.dev/galasa-seed-amd64:0.15.0-SNAPSHOT' image
	at dev.galasa.docker.operator.model.AbstractResource.getImageId(AbstractResource.java:76)
	at dev.galasa.docker.operator.model.NexusVolume.checkResourceDefined(NexusVolume.java:56)
	... 3 more
Caused by: com.github.dockerjava.api.exception.NotFoundException: Status 404: {"message":"manifest for docker.galasa.dev/galasa-seed-amd64:0.15.0-SNAPSHOT not found: manifest unknown: manifest unknown"}
	at com.github.dockerjava.core.DefaultInvocationBuilder.execute(DefaultInvocationBuilder.java:241)
	at com.github.dockerjava.core.DefaultInvocationBuilder.lambda$executeAndStream$1(DefaultInvocationBuilder.java:269)
	at java.lang.Thread.run(Thread.java:748)
Shutdown request received

**Comment by Michael-Baylis** [comment]
Sorry,   pushed the image up, so should be available now.
