### ISSUE TITLE
OBR Docker Build missing jars (not pulling from OBR).

### ISSUE THREAD

**Issue by matthewchivers** [galasa-dev/projectmanagement#608]
When creating the obr docker image (part of [@galasa-dev/build](https://github.com/galasa-dev/build)), it copies in jars that have been collected based on information in the uber obr.

In the event that a jar isn't included in the build output, it also can't be copied to the docker image. But no error is ever thrown during this process if a jar is missing (present on the obr, but not in the build output / resulting image).

```
02/03/2021 12:08:14.439 TRACE dev.galasa.boot.felix.FelixFramework.loadBundle - Installing bundle dev.galasa.ras.couchdb
02/03/2021 12:08:14.440 TRACE dev.galasa.boot.felix.FelixFramework.addResource - Resouce: dev.galasa.ras.couchdb/0.15.0.202103020929
02/03/2021 12:08:14.445 ERROR dev.galasa.boot.felix.FelixFramework.addResource - Unable to resolve dev.galasa.ras.couchdb/0.15.0.202103020929
02/03/2021 12:08:14.445 ERROR dev.galasa.boot.felix.FelixFramework.addResource - Unsatisfied requirement: package:(&(package=org.apache.http.client.utils)(version>=4.5.0)(!(version>=5.0.0)))
02/03/2021 12:08:14.445 ERROR dev.galasa.boot.felix.FelixFramework.addResource - Unsatisfied requirement: package:(&(package=org.osgi.service.cm)(version>=1.3.0)(!(version>=2.0.0)))
02/03/2021 12:08:14.445 ERROR dev.galasa.boot.felix.FelixFramework.addResource - Unsatisfied requirement: package:(&(package=org.apache.http.client.methods)(version>=4.5.0)(!(version>=5.0.0)))
02/03/2021 12:08:14.445 ERROR dev.galasa.boot.felix.FelixFramework.addResource - Unsatisfied requirement: package:(&(package=org.apache.http.impl.client)(version>=4.5.0)(!(version>=5.0.0)))
02/03/2021 12:08:14.445 ERROR dev.galasa.boot.Launcher.launch - Unable to run test class
dev.galasa.boot.LauncherException: Unable to create and initialize Felix framework
	at dev.galasa.boot.Launcher.buildFramework(Launcher.java:204)
	at dev.galasa.boot.Launcher.launch(Launcher.java:147)
	at dev.galasa.boot.Launcher.main(Launcher.java:117)
Caused by: dev.galasa.boot.LauncherException: Unable to install bundle "dev.galasa.ras.couchdb" from OBR repository
	at dev.galasa.boot.felix.FelixFramework.loadBundle(FelixFramework.java:805)
	at dev.galasa.boot.felix.FelixFramework.buildFramework(FelixFramework.java:126)
	at dev.galasa.boot.Launcher.buildFramework(Launcher.java:201)
	... 2 more
Caused by: dev.galasa.boot.LauncherException: Unable to resolve bundle dev.galasa.ras.couchdb
	at dev.galasa.boot.felix.FelixFramework.addResource(FelixFramework.java:886)
	at dev.galasa.boot.felix.FelixFramework.loadBundle(FelixFramework.java:803)
	... 4 more
```

**Comment by ApurvaS28** [comment]
The SimbankTestIVT  class aint working because of this .

**Comment by techcobweb** [comment]
stale
