### ISSUE TITLE
Docker resource management is NPEing

### ISSUE THREAD

**Issue by Michael-Baylis** [galasa-dev/projectmanagement#665]
15/04/2021 15:14:44.570 ERROR pool-6-thread-4 dev.galasa.docker.internal.DockerVolumeResourceMonitor.run - Volume monitor failed: 
java.lang.NullPointerException
	at dev.galasa.docker.internal.DockerVolumeResourceMonitor.updateDockerEngines(DockerVolumeResourceMonitor.java:155)
	at dev.galasa.docker.internal.DockerVolumeResourceMonitor.run(DockerVolumeResourceMonitor.java:55)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by Michael-Baylis** [comment]
@Jimbo4794 need to get this sorted with you return from holiday please

**Comment by Jimbo4794** [comment]
PR merged, null check in place
