### ISSUE TITLE
Issue with retrieveJar failing to retrieve Jar with no version or differing seperator

### ISSUE THREAD

**Issue by james-ashman** [galasa-dev/projectmanagement#671]
In dev.galasa.artifact.manager BundleResourcesImpl.java the method 'retrieveJar' successfully retrieves a jar with the naming convention of: jarname_*versionNumber*.jar however fails to retrieve the jar if the seperator is a hyphen such as in jarname-*versionNumber*.jar or when no version number is given such as in jarname.jar.

**Comment by Michael-Baylis** [comment]
How does it fail?   is there a stacktrace or what?

**Comment by james-ashman** [comment]
Here is the trace for the test I wrote attempting to retrieve a jar file with no attached version:

`dev.galasa.artifact.TestBundleResourceException: No jar found with symbolicName=HelloGalasa and version=
	at dev.galasa.artifact.internal.BundleResourcesImpl.retrieveJar(BundleResourcesImpl.java:210)
	at dev.galasa.artifact.manager.ivt.ArtifactManagerIVT.retrieveJarTestNoVersion(ArtifactManagerIVT.java:220)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at dev.galasa.framework.GenericMethodWrapper.invoke(GenericMethodWrapper.java:82)
	at dev.galasa.framework.TestMethodWrapper.invoke(TestMethodWrapper.java:61)
	at dev.galasa.framework.TestClassWrapper.runTestMethods(TestClassWrapper.java:202)
	at dev.galasa.framework.TestRunner.runTestClassWrapper(TestRunner.java:530)
	at dev.galasa.framework.TestRunner.runEnvironment(TestRunner.java:502)
	at dev.galasa.framework.TestRunner.createEnvironment(TestRunner.java:462)
	at dev.galasa.framework.TestRunner.generateEnvironment(TestRunner.java:435)
	at dev.galasa.framework.TestRunner.runTest(TestRunner.java:356)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at dev.galasa.boot.felix.FelixFramework.runTest(FelixFramework.java:220)
	at dev.galasa.boot.Launcher.launch(Launcher.java:163)
	at dev.galasa.boot.Launcher.main(Launcher.java:117)`

**Comment by james-ashman** [comment]
I believe I have a fix for this problem, I will make a pull request soon with the changes
