### ISSUE TITLE
NPE is Selenium resource management

### ISSUE THREAD

**Issue by Michael-Baylis** [galasa-dev/projectmanagement#685]
04/05/2021 06:56:43.860 ERROR pool-6-thread-2 dev.galasa.selenium.internal.SeleniumGridSessionMonitor.checkForStaleSessions - Probelm running the selenium slot monitor
java.lang.NullPointerException
	at java.net.URI$Parser.parse(URI.java:3042)
	at java.net.URI.<init>(URI.java:588)
	at dev.galasa.selenium.internal.SeleniumGridSessionMonitor.checkForStaleSessions(SeleniumGridSessionMonitor.java:87)
	at dev.galasa.selenium.internal.SeleniumGridSessionMonitor.run(SeleniumGridSessionMonitor.java:77)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

Need to sort this after your holiday please

**Comment by Jimbo4794** [comment]
PR merged, null check in place
