### ISSUE TITLE
Test engine continues after a interrupted exception is hit, leaving Jenkins job running indefinitely

### ISSUE THREAD

**Issue by Tom-Slattery** [galasa-dev/projectmanagement#707]
For example, run ID j17263 hits an interrupted exception:

`20/05/2021 14:42:09.258 ERROR c.i.c.c.b.m.i.HBankManagerImpl - Terminal signoff failed
dev.galasa.zos3270.TextNotFoundException: Unable to find a field containing 'Bank of Hursley Park Main Menu'
	at dev.galasa.zos3270.spi.Screen.waitForTextInField(Screen.java:945)
	at dev.galasa.zos3270.spi.Screen.waitForTextInField(Screen.java:938)
	at dev.galasa.zos3270.spi.Terminal.waitForTextInField(Terminal.java:211)
	at com.ibm.cics.cip.bank.manager.internal.HBankTerminalImpl.goToMainMenu(HBankTerminalImpl.java:125)
	at com.ibm.cics.cip.bank.manager.internal.HBankTerminalImpl.signOff(HBankTerminalImpl.java:80)
	at com.ibm.cics.cip.bank.manager.internal.HBankManagerImpl.provisionDiscard(HBankManagerImpl.java:346)
	at dev.galasa.framework.TestRunManagers.provisionDiscard(TestRunManagers.java:501)
	at dev.galasa.framework.TestRunner.discardEnvironment(TestRunner.java:481)
	at dev.galasa.framework.TestRunner.createEnvironment(TestRunner.java:470)
	at dev.galasa.framework.TestRunner.generateEnvironment(TestRunner.java:438)
	at dev.galasa.framework.TestRunner.runTest(TestRunner.java:356)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at dev.galasa.boot.felix.FelixFramework.runTest(FelixFramework.java:219)
	at dev.galasa.boot.Launcher.launch(Launcher.java:163)
	at dev.galasa.boot.Launcher.main(Launcher.java:117)
20/05/2021 14:42:09.317 ERROR dev.galasa.boot.Launcher.launch - Unable to run test class
dev.galasa.boot.LauncherException: dev.galasa.framework.TestRunException: Failed to update status
	at dev.galasa.boot.felix.FelixFramework.runTest(FelixFramework.java:221)
	at dev.galasa.boot.Launcher.launch(Launcher.java:163)
	at dev.galasa.boot.Launcher.main(Launcher.java:117)
Caused by: dev.galasa.framework.TestRunException: Failed to update status
	at dev.galasa.framework.TestRunner.updateStatus(TestRunner.java:595)
	at dev.galasa.framework.TestRunner.runTest(TestRunner.java:363)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at dev.galasa.boot.felix.FelixFramework.runTest(FelixFramework.java:219)
	... 2 more
Caused by: dev.galasa.framework.spi.DynamicStatusStoreException: Could not put key-value
	at dev.galasa.cps.etcd.internal.Etcd3DynamicStatusStore.put(Etcd3DynamicStatusStore.java:101)
	at dev.galasa.framework.internal.dss.FrameworkDynamicStoreKeyAccess.put(FrameworkDynamicStoreKeyAccess.java:60)
	at dev.galasa.framework.TestRunner.updateStatus(TestRunner.java:590)
	... 8 more
Caused by: java.lang.InterruptedException
	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:347)
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1908)
	at dev.galasa.cps.etcd.internal.Etcd3DynamicStatusStore.put(Etcd3DynamicStatusStore.java:98)
	... 10 more
20/05/2021 14:42:09.318 DEBUG dev.galasa.boot.felix.FelixFramework.stopFramework - Stopping Felix framework
Exception in thread "main" java.lang.InterruptedException
	at java.lang.Object.wait(Native Method)
	at org.apache.felix.framework.util.ThreadGate.await(ThreadGate.java:81)
	at org.apache.felix.framework.Felix.waitForStop(Felix.java:1222)
	at dev.galasa.boot.felix.FelixFramework.stopFramework(FelixFramework.java:740)
	at dev.galasa.boot.Launcher.launch(Launcher.java:191)
	at dev.galasa.boot.Launcher.main(Launcher.java:117)
20/05/2021 14:42:09.338 INFO  d.g.f.Framework - Framework service deactivated`

I cancelled my Jenkins job manually after noticing it had taken about 30 minutes to run.

**Comment by hobbit1983** [comment]
so the TextNotFoundException was thrown, was that caught within the test class explicitly - could you paste a snippet of you code that was looking for the String on the screen when the TNFE was thrown

**Comment by hobbit1983** [comment]
Closing due to inactivity
