### ISSUE TITLE
NPE in k8s controller causing runs to get stuck in allocated

### ISSUE THREAD

**Issue by Michael-Baylis** [galasa-dev/projectmanagement#709]
22/05/2021 08:51:29.858 ERROR pool-6-thread-1 dev.galasa.framework.k8s.controller.RunPoll.startPod - Failed to start new engine
java.lang.NullPointerException
	at dev.galasa.framework.k8s.controller.RunPoll.startPod(RunPoll.java:279)
	at dev.galasa.framework.k8s.controller.RunPoll.run(RunPoll.java:120)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by Michael-Baylis** [comment]
fixed it
