### ISSUE TITLE
zosBatchManager NPE when retrieving a job that has no steps

### ISSUE THREAD

**Issue by hobbit1983** [galasa-dev/projectmanagement#711]
submitting the following job:
```
//DONOWT  JOB 19842411,,CLASS=M,MSGCLASS=H,         
//  NOTIFY=&SYSUID,                                 
//  MSGLEVEL=(1,1)                                  
//COBOL  EXEC PGM=IEFBR14                           
/*                                                  
``` 
which fails with a JCL Error and thus produces no steps.  if I try to wait for a retrieve the job then I get the following exception

```
java.lang.NullPointerException
	at dev.galasa.zosbatch.zosmf.manager.internal.ZosmfZosBatchJobImpl.saveOutputToResultsArchive(ZosmfZosBatchJobImpl.java:344)
	at dev.galasa.zos.manager.ivt.ZosManagerBatchIVT.submitBasicJCLTest(ZosManagerBatchIVT.java:70)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at dev.galasa.framework.GenericMethodWrapper.invoke(GenericMethodWrapper.java:82)
	at dev.galasa.framework.TestMethodWrapper.invoke(TestMethodWrapper.java:61)
	at dev.galasa.framework.TestClassWrapper.runTestMethods(TestClassWrapper.java:202)
	at dev.galasa.framework.TestRunner.runTestClassWrapper(TestRunner.java:536)
	at dev.galasa.framework.TestRunner.runEnvironment(TestRunner.java:508)
	at dev.galasa.framework.TestRunner.createEnvironment(TestRunner.java:468)
	at dev.galasa.framework.TestRunner.generateEnvironment(TestRunner.java:438)
	at dev.galasa.framework.TestRunner.runTest(TestRunner.java:356)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at dev.galasa.boot.felix.FelixFramework.runTest(FelixFramework.java:219)
	at dev.galasa.boot.Launcher.launch(Launcher.java:163)
	at dev.galasa.boot.Launcher.main(Launcher.java:117)
```

**Comment by DavidXRoberts** [comment]
@hobbit1983 I can't reproduce this. Can you supply a code snippet please?

**Comment by hobbit1983** [comment]
wel well, aint that haunted.  uncommented the test that fails and it now passes.
I think an associated problem is if I ask for the spool file for a DDcard that doesn't exist then I get a null, which is perhaps expected behaviour.  if it is then I should close this

**Comment by DavidXRoberts** [comment]
OK, cool.
As for non existent spool file, I think null is better than Exception because then if you are expecting it to be created in say another step, you could loop:
`while (job.getSpoolFile("DDNAME") == null)`

**Comment by hobbit1983** [comment]
I agree will close

**Comment by hobbit1983** [comment]
Re-opening as this was re-found in the integration tests with the following:
The JCL submitted was:
```
//GALPDNOM JOB ,
//         CLASS=A,
//         MSGCLASS=A,
//         MSGLEVEL=(1,1)
/*JOBPARM SYSAFF=MV2D
//DONOWT  JOB 19842411,,CLASS=M,MSGCLASS=H,         
//  NOTIFY=&SYSUID,                                 
//  MSGLEVEL=(1,1)                                  
//COBOL  EXEC PGM=IEFBR14                           
/*                          
```

```
The resulting stack trace:
java.lang.NullPointerException
	at dev.galasa.zosbatch.zosmf.manager.internal.ZosmfZosBatchJobImpl.getSpoolFile(ZosmfZosBatchJobImpl.java:322)
	at dev.galasa.zos.manager.ivt.ZosManagerBatchIVT.submitJCLNoSteps(ZosManagerBatchIVT.java:93)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at dev.galasa.framework.GenericMethodWrapper.invoke(GenericMethodWrapper.java:82)
	at dev.galasa.framework.TestMethodWrapper.invoke(TestMethodWrapper.java:61)
	at dev.galasa.framework.TestClassWrapper.runTestMethods(TestClassWrapper.java:202)
	at dev.galasa.framework.TestRunner.runTestClassWrapper(TestRunner.java:536)
	at dev.galasa.framework.TestRunner.runEnvironment(TestRunner.java:508)
	at dev.galasa.framework.TestRunner.createEnvironment(TestRunner.java:468)
	at dev.galasa.framework.TestRunner.generateEnvironment(TestRunner.java:438)
	at dev.galasa.framework.TestRunner.runTest(TestRunner.java:356)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at dev.galasa.boot.felix.FelixFramework.runTest(FelixFramework.java:219)
	at dev.galasa.boot.Launcher.launch(Launcher.java:163)
	at dev.galasa.boot.Launcher.main(Launcher.java:117)
```

So it's looking for the job - but it's not going to find it as it's a bad job and NPEs in response.  Sorry but @DavidXRoberts can you take another look please

**Comment by DavidXRoberts** [comment]
@hobbit1983 Just delivered a PR that will hopefully fix your NPE. Let me know how it goes,

**Comment by hobbit1983** [comment]
Thanks will have a look tomorrow

**Comment by hobbit1983** [comment]
Yup this works fine now.  However we return Integer.MIN_VALUE as the return code.  Not a problem but -1 might be a better choice, but will check with the java doc
