### ISSUE TITLE
NPE on ECO running 0.15.0 using Selenium mgr and docker

### ISSUE THREAD

**Issue by hbunchgithub** [galasa-dev/projectmanagement#722]
Henry Bunch  18 hours ago
Eco CPS property selenium.driver.type set to docker:
# etcdctl get --prefix selenium.
selenium.default.driver
CHROME
selenium.driver.max.slots
1
selenium.driver.type
docker
but throws exception on K8
27/05/2021 17:14:03.712 WARN  d.g.k.i.p.KubernetesClusters - Invalid property, using default K8S
java.lang.NullPointerException
Followed by an exception on SeleniumManagerImpl
27/05/2021 17:14:03.722 INFO  d.g.d.i.DockerManagerImpl - Registering docker registries
27/05/2021 17:14:03.747 INFO  d.g.d.i.DockerManagerImpl - Finding all docker related annotations
27/05/2021 17:14:03.760 INFO  d.g.f.TestRunner - Provision Generate failed
dev.galasa.framework.spi.FrameworkException: Problem in provision generate for manager dev.galasa.selenium.internal.SeleniumManagerImpl
	at dev.galasa.framework.TestRunManagers.provisionGenerate(TestRunManagers.java:465)
	at dev.galasa.framework.TestRunner.generateEnvironment(TestRunner.java:423)
	at dev.galasa.framework.TestRunner.runTest(TestRunner.java:356)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at dev.galasa.boot.felix.FelixFramework.runTest(FelixFramework.java:219)
	at dev.galasa.boot.Launcher.launch(Launcher.java:163)
	at dev.galasa.boot.Launcher.main(Launcher.java:117)
Caused by: dev.galasa.ManagerException: Problem generating Test Class fields
	at dev.galasa.framework.spi.AbstractManager.generateAnnotatedFields(AbstractManager.java:186)
	at dev.galasa.selenium.internal.SeleniumManagerImpl.provisionGenerate(SeleniumManagerImpl.java:140)
	at dev.galasa.framework.TestRunManagers.provisionGenerate(TestRunManagers.java:460)
	... 9 more
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at dev.galasa.framework.spi.AbstractManager.generateAnnotatedFields(AbstractManager.java:177)
	... 11 more
Caused by: java.lang.NullPointerException
	at io.etcd.jetcd.ByteSequence.from(ByteSequence.java:91)
	at dev.galasa.cps.etcd.internal.Etcd3DynamicStatusStore.performActionsSwapIf(Etcd3DynamicStatusStore.java:554)
	at dev.galasa.cps.etcd.internal.Etcd3DynamicStatusStore.performActions(Etcd3DynamicStatusStore.java:481)
	at dev.galasa.framework.internal.dss.FrameworkDynamicStoreKeyAccess.performActions(FrameworkDynamicStoreKeyAccess.java:265)
	at dev.galasa.selenium.internal.SeleniumEnvironment.allocateSlot(SeleniumEnvironment.java:157)
	at dev.galasa.selenium.internal.SeleniumEnvironment.allocateDriver(SeleniumEnvironment.java:71)
	at dev.galasa.selenium.internal.SeleniumManagerImpl.generateSeleniumManager(SeleniumManagerImpl.java:156)
	... 16 more
27/05/2021 17:14:03.967 INFO  d.g.r.c.i.CouchdbRasWriteByteChannel - Stored artifact /framework/cps_record.properties, length=0, contentType=plain/text
27/05/2021 17:14:03.993 INFO  d.g.r.c.i.CouchdbRasWriteByteChannel - Stored artifact /framework/cps_record.properties, length=1157, contentType=plain/text
27/05/2021 17:14:03.994 INFO  d.g.f.Framework - Shutting down the framework
CPS store docker props:
# etcdctl get --prefix docker.
docker.default.engines
PRIMARY
docker.engine.PRIMARY.hostname
localhost
docker.engine.PRIMARY.port
2376

James Davies:palm_tree:  17 hours ago
This looks like the etcd/cps bundle that handles the property checking in the ecosystem doesnt support checking for a non-existsing value with passing it a null the same way a local one does. @Michael Baylis does the performaction of a DSS swap suppose to support passing a null for a non-existing property, or is this something i have leveraged that the fpf just deals with?
New

Michael Baylis  3 hours ago
Will have to have a look a bit later.  Please raise issue

Michael Baylis  3 hours ago
and assign to me

Michael Baylis  3 hours ago
otherwise I will forget

**Comment by Michael-Baylis** [comment]
@Jimbo4794 you have corrected this,  haven't you

**Comment by Jimbo4794** [comment]
Yes, sorry should of closed
