### ISSUE TITLE
POM error Missing artifact dev.galasa:dev.galasa.zos3270.common:jar:0.15.0

### ISSUE THREAD

**Issue by hbunchgithub** [galasa-dev/projectmanagement#724]
No side effects seen but error on pom related to dev.galasa:dev.galasa.zos3270.common.jar
Multiple annotations found at this line:
	- Missing artifact dev.galasa:dev.galasa.zos3270.common:jar:0.15.0
	- Could not transfer artifact dev.galasa:dev.galasa.zos3270.common:jar:0.15.0 from/to central (https://repo.maven.apache.org/maven2): C:\Users\HenryBunch\.m2\repository\dev\galasa\dev.galasa.zos3270.common\0.15.0\aether-
	 da9f4122-42c4-4d7f-8b2a-394f6b095df0-dev.galasa.zos3270.common-0.15.0.jar-in-progress (The system cannot find the file specified.) org.eclipse.aether.transfer.ArtifactTransferException: Could not transfer artifact dev.galasa:dev.galasa.zos3270.common:jar:0.15.0 from/to
	 central (https://repo.maven.apache.org/maven2): C:\Users\HenryBunch\.m2\repository\dev\galasa\dev.galasa.zos3270.common\0.15.0\aether-da9f4122-42c4-4d7f-8b2a-394f6b095df0-dev.galasa.zos3270.common-0.15.0.jar-in-progress (The system cannot find the file
	 specified.) at io.takari.aether.connector.AetherRepositoryConnector$2.wrap(AetherRepositoryConnector.java:904) at io.takari.aether.connector.AetherRepositoryConnector$2.wrap(AetherRepositoryConnector.java:1) at
	 io.takari.aether.connector.AetherRepositoryConnector$GetTask.flush(AetherRepositoryConnector.java:678) at io.takari.aether.connector.AetherRepositoryConnector.get(AetherRepositoryConnector.java:310) at
	 org.eclipse.aether.internal.impl.DefaultArtifactResolver.performDownloads(DefaultArtifactResolver.java:498) at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:399) at
	 org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:224) at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:338) at
	 org.apache.maven.project.DefaultProjectDependenciesResolver.resolve(DefaultProjectDependenciesResolver.java:202) at org.apache.maven.project.DefaultProjectBuilder.resolveDependencies(DefaultProjectBuilder.java:212) at
	 org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBuilder.java:185) at org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBuilder.java:116) at org.eclipse.m2e.core.internal.embedder.MavenImpl.readMavenProject(MavenImpl.java:636) at
	 org.eclipse.m2e.core.internal.project.registry.DefaultMavenDependencyResolver.resolveProjectDependencies(DefaultMavenDependencyResolver.java:63) at org.eclipse.m2e.core.internal.project.registry.ProjectRegistryManager.refreshPhase2(ProjectRegistryManager.java:530) at
	 org.eclipse.m2e.core.internal.project.registry.ProjectRegistryManager$3.call(ProjectRegistryManager.java:492) at org.eclipse.m2e.core.internal.project.registry.ProjectRegistryManager$3.call(ProjectRegistryManager.java:1) at
	 org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:177) at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:151) at
	 org.eclipse.m2e.core.internal.project.registry.ProjectRegistryManager.refresh(ProjectRegistryManager.java:496) at org.eclipse.m2e.core.internal.project.registry.ProjectRegistryManager.refresh(ProjectRegistryManager.java:351) at
	 org.eclipse.m2e.core.internal.project.registry.ProjectRegistryManager.refresh(ProjectRegistryManager.java:298) at org.eclipse.m2e.core.internal.builder.MavenBuilder$BuildMethod.getProjectFacade(MavenBuilder.java:154) at
	 org.eclipse.m2e.core.internal.builder.MavenBuilder$BuildMethod$1.call(MavenBuilder.java:89) at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:177) at
	 org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:151) at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:99) at
	 org.eclipse.m2e.core.internal.builder.MavenBuilder$BuildMethod.execute(MavenBuilder.java:86) at org.eclipse.m2e.core.internal.builder.MavenBuilder.build(MavenBuilder.java:200) at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:795) at
	 org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42) at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:216) at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:259) at
	 org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:312) at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42) at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:315) at
	 org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:367) at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:388) at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:142) at
	 org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:232) at org.eclipse.core.internal.jobs.Worker.run(Worker.java:60) Caused by: java.io.FileNotFoundException: C:\Users\HenryBunch\.m2\repository\dev\galasa\dev.galasa.zos3270.common\0.15.0\aether-
	 da9f4122-42c4-4d7f-8b2a-394f6b095df0-dev.galasa.zos3270.common-0.15.0.jar-in-progress (The system cannot find the file specified.) at java.io.FileInputStream.open0(Native Method) at java.io.FileInputStream.open(FileInputStream.java:212) at
	 java.io.FileInputStream.<init>(FileInputStream.java:152) at org.eclipse.aether.internal.impl.DefaultFileProcessor.copy(DefaultFileProcessor.java:162) at org.eclipse.aether.internal.impl.DefaultFileProcessor.copy(DefaultFileProcessor.java:150) at
	 org.eclipse.aether.internal.impl.DefaultFileProcessor.move(DefaultFileProcessor.java:251) at io.takari.aether.connector.AetherRepositoryConnector$GetTask.rename(AetherRepositoryConnector.java:682) at
	 io.takari.aether.connector.AetherRepositoryConnector$GetTask.run(AetherRepositoryConnector.java:466) at io.takari.aether.connector.AetherRepositoryConnector.get(AetherRepositoryConnector.java:304) ... 37 more
6 replies

I see the files in the Maven Dependencies list
image.png 
image.png

Michael Baylis  4 minutes ago
issue please Henry.

**Comment by hbunchgithub** [comment]
@Michael-Baylis   Any update on this bug?

**Comment by Michael-Baylis** [comment]
Will ensure it is in 17,   but at the moment I am not sure what the problem is

**Comment by matthewchivers** [comment]
Mike is probably best place to respond to this, but just in case:
My limited research tells me this is caused either by a proxy problem, network issue, or the existence of a .lastUpdate file for the dependency. 

A few checks you can do:
1. If using eclipse, please try right-clicking the project, selecting `Maven` =>  `Update Project`, then ensure `Force Update of Snapshots/Releases` is ticked, and finally click on `OK`. If not fixed immediately, restart eclipse. 
2. Ensure proxy settings (if you use one) are correct in your `settings.xml` inside your `.m2` folder.
3. Remove the `.lastUpdated` files from the affected dependencies (looks like dev.galasa.zos3270.common) in your `.m2/repository`. They are typically located in a hierarchy similar to: `~/.m2/repository/dev/galasa/dev.galasa.zos3270.common/0.15.0/dev.galasa.zos3270.common-0.15.0.jar.lastUpdated`

**Comment by Michael-Baylis** [comment]
think it is much more subtle than the above.  just need time to have a look
