### ISSUE TITLE
Unable to create and initialize Felix framework - Unable to cache bundle

### ISSUE THREAD

**Issue by AkosHosszu** [galasa-dev/projectmanagement#762]
I'm trying to start a debug and getting some error messages in vscode:
```
29/06/2021 17:32:31.183 DEBUG dev.galasa.boot.felix.FelixFramework.buildFramework - Installing required OSGi bundles
29/06/2021 17:32:31.200 ERROR dev.galasa.boot.Launcher.launch - Unable to run test class
dev.galasa.boot.LauncherException: Unable to create and initialize Felix framework
at dev.galasa.boot.Launcher.buildFramework(Launcher.java:187)
at dev.galasa.boot.Launcher.launch(Launcher.java:136)
at dev.galasa.boot.Launcher.main(Launcher.java:106)
Caused by: dev.galasa.boot.LauncherException: Unable to initialise the Felix framework
at dev.galasa.boot.felix.FelixFramework.buildFramework(FelixFramework.java:131)
at dev.galasa.boot.Launcher.buildFramework(Launcher.java:184)
... 2 more
Caused by: org.osgi.framework.BundleException: Unable to cache bundle: jar:file:/C:/Users/H8839B740/.vscode/extensions/galasa.galasa-plugin-0.13.0/lib/galasa-boot.jar!/bundle/org.apache.felix.scr.jar
at org.apache.felix.framework.Felix.installBundle(Felix.java:3231)
at org.apache.felix.framework.BundleContextImpl.installBundle(BundleContextImpl.java:147)
at org.apache.felix.framework.BundleContextImpl.installBundle(BundleContextImpl.java:120)
at dev.galasa.boot.felix.FelixFramework.installBundle(FelixFramework.java:824)
at dev.galasa.boot.felix.FelixFramework.buildFramework(FelixFramework.java:94)
... 3 more
Caused by: java.net.MalformedURLException: Unknown protocol: jar
at java.base/java.net.URL.<init>(URL.java:706)
at org.apache.felix.framework.util.SecureAction.createURL(SecureAction.java:256)
at org.apache.felix.framework.cache.JarRevision.initialize(JarRevision.java:148)
at org.apache.felix.framework.cache.JarRevision.<init>(JarRevision.java:76)
at org.apache.felix.framework.cache.BundleArchive.createRevisionFromLocation(BundleArchive.java:799)
at org.apache.felix.framework.cache.BundleArchive.reviseInternal(BundleArchive.java:480)
at org.apache.felix.framework.cache.BundleArchive.<init>(BundleArchive.java:148)
at org.apache.felix.framework.cache.BundleCache.create(BundleCache.java:462)
at org.apache.felix.framework.Felix.installBundle(Felix.java:3227)
... 7 more
```

**Comment by hobbit1983** [comment]
@Jimbo4794 can you triage please

**Comment by hobbit1983** [comment]
closed due to inactivity - please re-open if needed
