### ISSUE TITLE
Attempt to stop and already stopped container results in a NPE

### ISSUE THREAD

**Issue by Michael-Baylis** [galasa-dev/projectmanagement#91]
java.lang.NullPointerException
	at dev.galasa.docker.internal.DockerContainerImpl.isRunning(DockerContainerImpl.java:400)
	at dev.galasa.docker.internal.DockerContainerImpl.stopDockerContainer(DockerContainerImpl.java:210)
	at dev.galasa.docker.internal.DockerContainerImpl.stop(DockerContainerImpl.java:199)
	at dev.galasa.docker.manager.ivt.DockerManagerIVT.startAndStopContainer(DockerManagerIVT.java:81)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at dev.galasa.framework.GenericMethodWrapper.invoke(GenericMethodWrapper.java:80)
	at dev.galasa.framework.TestMethodWrapper.invoke(TestMethodWrapper.java:55)
	at dev.galasa.framework.TestClassWrapper.runTestMethods(TestClassWrapper.java:175)
	at dev.galasa.framework.TestRunner.runTest(TestRunner.java:313)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at dev.galasa.boot.felix.FelixFramework.runTest(FelixFramework.java:217)
	at dev.galasa.boot.Launcher.launch(Launcher.java:140)
	at dev.galasa.boot.Launcher.main(Launcher.java:101)

**Comment by Jimbo4794** [comment]
![image.png](https://images.zenhubusercontent.com/5dde88195d4d9e0001e18c6f/f428e721-9f1b-43f2-acda-3ad98d99aba6)

**Comment by Jimbo4794** [comment]
How did you go about producing that?

**Comment by Michael-Baylis** [comment]
put start=false on the annotation

**Comment by Jimbo4794** [comment]
replicated and fixed, thanks.

**Comment by Michael-Baylis** [comment]
Thats better.
