### ISSUE TITLE
Error During execution of SimBankIVT

### ISSUE THREAD

**Issue by ApurvaS28** [galasa-dev/projectmanagement#919]
This is the message displayed on the console:-------------------------------------- 

1/11/2021 18:22:44.112 ERROR dev.galasa.boot.Launcher.launch - Unable to run test class
dev.galasa.boot.LauncherException: Unable to create and initialize Felix framework
	at dev.galasa.boot.Launcher.buildFramework(Launcher.java:204)
	at dev.galasa.boot.Launcher.launch(Launcher.java:147)
	at dev.galasa.boot.Launcher.main(Launcher.java:117)
Caused by: dev.galasa.boot.LauncherException: Unable to load repository mvn:dev.galasa/dev.galasa.uber.obr/LATEST/obr
	at dev.galasa.boot.felix.FelixFramework.loadBundleRepositories(FelixFramework.java:770)
	at dev.galasa.boot.felix.FelixFramework.buildFramework(FelixFramework.java:109)
	at dev.galasa.boot.Launcher.buildFramework(Launcher.java:201)
	... 2 more
Caused by: java.net.MalformedURLException: unknown protocol: mvn
	at java.base/java.net.URL.<init>(URL.java:681)
	at java.base/java.net.URL.<init>(URL.java:569)
	at java.base/java.net.URL.<init>(URL.java:516)
	at org.apache.felix.bundlerepository.impl.RepositoryAdminImpl.addRepository(RepositoryAdminImpl.java:94)
	at dev.galasa.boot.felix.FelixFramework.loadBundleRepositories(FelixFramework.java:768)
	... 4 more
21/11/2021 18:22:44.113 DEBUG dev.galasa.boot.felix.FelixFramework.stopFramework - Stopping Felix framework
21/11/2021 18:22:44.137 DEBUG dev.galasa.boot.felix.FelixFramework.stopFramework - Felix framework stopped
21/11/2021 18:22:44.138 ERROR dev.galasa.boot.Launcher.main - Exiting launcher due to exception
dev.galasa.boot.LauncherException: Unable to create and initialize Felix framework
	at dev.galasa.boot.Launcher.buildFramework(Launcher.java:204)
	at dev.galasa.boot.Launcher.launch(Launcher.java:147)
	at dev.galasa.boot.Launcher.main(Launcher.java:117)
Caused by: dev.galasa.boot.LauncherException: Unable to load repository mvn:dev.galasa/dev.galasa.uber.obr/LATEST/obr
	at dev.galasa.boot.felix.FelixFramework.loadBundleRepositories(FelixFramework.java:770)
	at dev.galasa.boot.felix.FelixFramework.buildFramework(FelixFramework.java:109)
	at dev.galasa.boot.Launcher.buildFramework(Launcher.java:201)
	... 2 more
Caused by: java.net.MalformedURLException: unknown protocol: mvn
	at java.base/java.net.URL.<init>(URL.java:681)
	at java.base/java.net.URL.<init>(URL.java:569)
	at java.base/java.net.URL.<init>(URL.java:516)
	at org.apache.felix.bundlerepository.impl.RepositoryAdminImpl.addRepository(RepositoryAdminImpl.java:94)
	at dev.galasa.boot.felix.FelixFramework.loadBundleRepositories(FelixFramework.java:768)
	... 4 more

How can i resolve this?

**Comment by hobbit1983** [comment]
Hey. Thanks for raising an issue. Can I ask 2 questions. 
Are you running from the external open source artefacts or have you downloaded the archive zip?  

If you could show me the content of your galasa preferences in eclipse. I can take a quick look today but will ensure the dev team see it tomorrow

**Comment by ApurvaS28** [comment]
![image](https://user-images.githubusercontent.com/94789018/142764766-3f4b5e63-82d2-42ea-992b-8dad76b0cd9c.png)
Here i am Attaching the Galasa preferences screenshot. 

For running the class i have just followed the steps mentioned in the galasa docs.

**Comment by ReeceWilliams1105** [comment]
Hiya, I'm going to take a look at this issue now.

**Comment by ReeceWilliams1105** [comment]
Hi @ApurvaS28, Could I just ask if you are trying to run the tests using the gradle or maven methods on the docs? Also do you mind showing me the version of maven you are running?

**Comment by ApurvaS28** [comment]
I am have been using maven methods .
![image](https://user-images.githubusercontent.com/94789018/142845964-da19e12b-886f-47de-acf1-afe667fbb1ec.png)

**Comment by ReeceWilliams1105** [comment]
Hi @ApurvaS28, I've managed to recreate this issue and after some investigation I've managed to narrow this issue down to version 17 of java. I would recommend using JDK version 11 or 8 for use with Galasa at this time. I will keep this issue open so that in the future the issue can be fixed.

**Comment by ReeceWilliams1105** [comment]
Below is the full stack track of the error for future reference:
--------------------------------------------------------------------
23/11/2021 12:17:00.950 DEBUG dev.galasa.boot.Launcher.processCommandLine - Supplied command line arguments: --bootstrap file:///Users/reecewilliams/.galasa/bootstrap.properties --overrides file:///var/folders/_0/kf6t2v_913s50hzchbv6ln1c0000gn/T/galasa_eclipse_cache_662477892964121141/galasaoverrides15372393958336714253.properties --localmaven file:/Users/reecewilliams/.m2/repository/ --remotemaven https://repo.maven.apache.org/maven2/ --obr file:/Users/reecewilliams/TestEclipseWorkspace/.metadata/.plugins/dev.galasa.eclipse/workspace.obr --obr mvn:dev.galasa/dev.galasa.uber.obr/LATEST/obr --test dev.galasa.simbank.tests/dev.galasa.simbank.tests.SimBankIVT 
23/11/2021 12:17:00.972 DEBUG dev.galasa.boot.Launcher.launch - OBR Repository Files: [file:/Users/reecewilliams/TestEclipseWorkspace/.metadata/.plugins/dev.galasa.eclipse/workspace.obr, mvn:dev.galasa/dev.galasa.uber.obr/LATEST/obr]
23/11/2021 12:17:00.972 DEBUG dev.galasa.boot.Launcher.launch - Launching Framework...
23/11/2021 12:17:00.972 DEBUG dev.galasa.boot.Launcher.buildFramework - Launching Framework...
23/11/2021 12:17:00.972 DEBUG dev.galasa.boot.felix.FelixFramework.buildFramework - Building Felix Framework...
java.lang.NoSuchMethodException: sun.misc.Unsafe.defineAnonymousClass(java.lang.Class,[B,[Ljava.lang.Object;)
	at java.base/java.lang.Class.getMethod(Class.java:2227)
	at org.apache.felix.framework.util.SecureAction.getAccessor(SecureAction.java:1134)
	at org.apache.felix.framework.util.SecureAction.<clinit>(SecureAction.java:86)
	at org.apache.felix.framework.Felix.<clinit>(Felix.java:114)
	at org.apache.felix.framework.FrameworkFactory.newFramework(FrameworkFactory.java:30)
	at dev.galasa.boot.felix.FelixFramework.buildFramework(FelixFramework.java:87)
	at dev.galasa.boot.Launcher.buildFramework(Launcher.java:201)
	at dev.galasa.boot.Launcher.launch(Launcher.java:147)
	at dev.galasa.boot.Launcher.main(Launcher.java:117)
java.lang.NoSuchMethodException: sun.misc.Unsafe.defineAnonymousClass(java.lang.Class,[B,[Ljava.lang.Object;)
	at java.base/java.lang.Class.getMethod(Class.java:2227)
	at org.apache.felix.framework.util.SecureAction.getAccessor(SecureAction.java:1134)
	at org.apache.felix.framework.util.SecureAction.setAccesssible(SecureAction.java:998)
	at org.apache.felix.framework.ext.ClassPathExtenderFactory$DefaultClassLoaderExtender.<clinit>(ClassPathExtenderFactory.java:55)
	at org.apache.felix.framework.ExtensionManager.<clinit>(ExtensionManager.java:152)
	at org.apache.felix.framework.Felix.initializeFrameworkProperties(Felix.java:4881)
	at org.apache.felix.framework.Felix.<init>(Felix.java:405)
	at org.apache.felix.framework.Felix.<init>(Felix.java:355)
	at org.apache.felix.framework.FrameworkFactory.newFramework(FrameworkFactory.java:30)
	at dev.galasa.boot.felix.FelixFramework.buildFramework(FelixFramework.java:87)
	at dev.galasa.boot.Launcher.buildFramework(Launcher.java:201)
	at dev.galasa.boot.Launcher.launch(Launcher.java:147)
	at dev.galasa.boot.Launcher.main(Launcher.java:117)
23/11/2021 12:17:01.083 DEBUG dev.galasa.boot.felix.FelixFramework.buildFramework - Initializing Felix Framework
java.lang.ExceptionInInitializerError
	at org.apache.felix.framework.URLHandlers.<clinit>(URLHandlers.java:119)
	at org.apache.felix.framework.URLHandlersActivator.start(URLHandlersActivator.java:69)
	at org.apache.felix.framework.util.SecureAction.startActivator(SecureAction.java:825)
	at org.apache.felix.framework.Felix$SystemBundleActivator.start(Felix.java:5173)
	at org.apache.felix.framework.util.SecureAction.startActivator(SecureAction.java:825)
	at org.apache.felix.framework.Felix.init(Felix.java:899)
	at org.apache.felix.framework.Felix.init(Felix.java:648)
	at dev.galasa.boot.felix.FelixFramework.buildFramework(FelixFramework.java:89)
	at dev.galasa.boot.Launcher.buildFramework(Launcher.java:201)
	at dev.galasa.boot.Launcher.launch(Launcher.java:147)
	at dev.galasa.boot.Launcher.main(Launcher.java:117)
Caused by: java.lang.RuntimeException: Unable to make protected boolean java.net.URLStreamHandler.equals(java.net.URL,java.net.URL) accessible: module java.base does not "opens java.net" to unnamed module @5b87ed94
	at org.apache.felix.framework.URLHandlersStreamHandlerProxy.<clinit>(URLHandlersStreamHandlerProxy.java:103)
	... 11 more
Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make protected boolean java.net.URLStreamHandler.equals(java.net.URL,java.net.URL) accessible: module java.base does not "opens java.net" to unnamed module @5b87ed94
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:354)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
	at java.base/java.lang.reflect.Method.checkCanSetAccessible(Method.java:199)
	at java.base/java.lang.reflect.AccessibleObject.setAccessible(AccessibleObject.java:130)
	at org.apache.felix.framework.util.SecureAction.lambda$getAccessor$0(SecureAction.java:1145)
	at org.apache.felix.framework.util.SecureAction.setAccesssible(SecureAction.java:998)
	at org.apache.felix.framework.URLHandlersStreamHandlerProxy.<clinit>(URLHandlersStreamHandlerProxy.java:78)
	... 11 more
23/11/2021 12:17:01.158 DEBUG dev.galasa.boot.felix.FelixFramework.buildFramework - Starting Felix Framework
23/11/2021 12:17:01.159 DEBUG dev.galasa.boot.felix.FelixFramework.buildFramework - Felix Framework started
23/11/2021 12:17:01.160 DEBUG dev.galasa.boot.felix.FelixFramework.buildFramework - Installing required OSGi bundles
23/11/2021 12:17:01.160 TRACE dev.galasa.boot.felix.FelixFramework.isJar - isJar resource URL protocol: jar
23/11/2021 12:17:01.161 TRACE dev.galasa.boot.felix.FelixFramework.installBundle - bundleLocation: jar:file:/Users/reecewilliams/.p2/pool/plugins/dev.galasa.eclipse_0.18.0.202109090856/lib/galasa-boot.jar!/bundle/org.apache.felix.scr.jar
23/11/2021 12:17:01.203 TRACE dev.galasa.boot.felix.FelixFramework.printBundles - Bundle status:
    0|Active     |     |org.apache.felix.framework (7.0.0)
    1|Active     |     |org.apache.felix.scr (2.1.14)
23/11/2021 12:17:01.203 TRACE dev.galasa.boot.felix.FelixFramework.isJar - isJar resource URL protocol: jar
23/11/2021 12:17:01.204 TRACE dev.galasa.boot.felix.FelixFramework.installBundle - bundleLocation: jar:file:/Users/reecewilliams/.p2/pool/plugins/dev.galasa.eclipse_0.18.0.202109090856/lib/galasa-boot.jar!/bundle/dev.galasa.framework.log4j2.bridge.jar
23/11/2021 12:17:01.223 TRACE dev.galasa.boot.felix.FelixFramework.printBundles - Bundle status:
    0|Active     |     |org.apache.felix.framework (7.0.0)
    1|Active     |     |org.apache.felix.scr (2.1.14)
    2|Installed  |     |dev.galasa.framework.log4j2.bridge (0.16.0-018b741bb34ad7dbd33ac105ca88367154a38678)
23/11/2021 12:17:01.223 TRACE dev.galasa.boot.felix.FelixFramework.isJar - isJar resource URL protocol: jar
23/11/2021 12:17:01.223 TRACE dev.galasa.boot.felix.FelixFramework.installBundle - bundleLocation: jar:file:/Users/reecewilliams/.p2/pool/plugins/dev.galasa.eclipse_0.18.0.202109090856/lib/galasa-boot.jar!/bundle/log4j-api.jar
23/11/2021 12:17:01.256 TRACE dev.galasa.boot.felix.FelixFramework.printBundles - Bundle status:
    0|Active     |     |org.apache.felix.framework (7.0.0)
    1|Active     |     |org.apache.felix.scr (2.1.14)
    2|Installed  |     |dev.galasa.framework.log4j2.bridge (0.16.0-018b741bb34ad7dbd33ac105ca88367154a38678)
    3|Active     |     |org.apache.logging.log4j.api (2.14.1)
23/11/2021 12:17:01.257 TRACE dev.galasa.boot.felix.FelixFramework.isJar - isJar resource URL protocol: jar
23/11/2021 12:17:01.257 TRACE dev.galasa.boot.felix.FelixFramework.installBundle - bundleLocation: jar:file:/Users/reecewilliams/.p2/pool/plugins/dev.galasa.eclipse_0.18.0.202109090856/lib/galasa-boot.jar!/bundle/log4j-core.jar
23/11/2021 12:17:01.338 TRACE dev.galasa.boot.felix.FelixFramework.printBundles - Bundle status:
    0|Active     |     |org.apache.felix.framework (7.0.0)
    1|Active     |     |org.apache.felix.scr (2.1.14)
    2|Resolved   |     |dev.galasa.framework.log4j2.bridge (0.16.0-018b741bb34ad7dbd33ac105ca88367154a38678)
    3|Active     |     |org.apache.logging.log4j.api (2.14.1)
    4|Active     |     |org.apache.logging.log4j.core (2.14.1)
23/11/2021 12:17:01.338 TRACE dev.galasa.boot.felix.FelixFramework.isJar - isJar resource URL protocol: jar
23/11/2021 12:17:01.339 TRACE dev.galasa.boot.felix.FelixFramework.installBundle - bundleLocation: jar:file:/Users/reecewilliams/.p2/pool/plugins/dev.galasa.eclipse_0.18.0.202109090856/lib/galasa-boot.jar!/bundle/dev.galasa.framework.maven.repository.spi.jar
23/11/2021 12:17:01.344 TRACE dev.galasa.boot.felix.FelixFramework.printBundles - Bundle status:
    0|Active     |     |org.apache.felix.framework (7.0.0)
    1|Active     |     |org.apache.felix.scr (2.1.14)
    2|Resolved   |     |dev.galasa.framework.log4j2.bridge (0.16.0-018b741bb34ad7dbd33ac105ca88367154a38678)
    3|Active     |     |org.apache.logging.log4j.api (2.14.1)
    4|Active     |     |org.apache.logging.log4j.core (2.14.1)
    5|Active     |     |dev.galasa.framework.maven.repository.spi (0.18.0-93bcaf2103ffc72b27f0a46c3379998369254cfd)
23/11/2021 12:17:01.344 TRACE dev.galasa.boot.felix.FelixFramework.isJar - isJar resource URL protocol: jar
23/11/2021 12:17:01.345 TRACE dev.galasa.boot.felix.FelixFramework.installBundle - bundleLocation: jar:file:/Users/reecewilliams/.p2/pool/plugins/dev.galasa.eclipse_0.18.0.202109090856/lib/galasa-boot.jar!/bundle/dev.galasa.framework.maven.repository.jar
23/11/2021 12:17:01.376 TRACE dev.galasa.boot.felix.FelixFramework.printBundles - Bundle status:
    0|Active     |     |org.apache.felix.framework (7.0.0)
    1|Active     |     |org.apache.felix.scr (2.1.14)
    2|Resolved   |     |dev.galasa.framework.log4j2.bridge (0.16.0-018b741bb34ad7dbd33ac105ca88367154a38678)
    3|Active     |     |org.apache.logging.log4j.api (2.14.1)
    4|Active     |     |org.apache.logging.log4j.core (2.14.1)
    5|Active     |     |dev.galasa.framework.maven.repository.spi (0.18.0-93bcaf2103ffc72b27f0a46c3379998369254cfd)
    6|Active     |     |dev.galasa.framework.maven.repository (0.18.0-93bcaf2103ffc72b27f0a46c3379998369254cfd)
23/11/2021 12:17:01.380 TRACE dev.galasa.boot.felix.FelixFramework.isJar - isJar resource URL protocol: jar
23/11/2021 12:17:01.380 TRACE dev.galasa.boot.felix.FelixFramework.installBundle - bundleLocation: jar:file:/Users/reecewilliams/.p2/pool/plugins/dev.galasa.eclipse_0.18.0.202109090856/lib/galasa-boot.jar!/bundle/org.apache.felix.bundlerepository.jar
23/11/2021 12:17:01.424 TRACE dev.galasa.boot.felix.FelixFramework.printBundles - Bundle status:
    0|Active     |     |org.apache.felix.framework (7.0.0)
    1|Active     |     |org.apache.felix.scr (2.1.14)
    2|Resolved   |     |dev.galasa.framework.log4j2.bridge (0.16.0-018b741bb34ad7dbd33ac105ca88367154a38678)
    3|Active     |     |org.apache.logging.log4j.api (2.14.1)
    4|Active     |     |org.apache.logging.log4j.core (2.14.1)
    5|Active     |     |dev.galasa.framework.maven.repository.spi (0.18.0-93bcaf2103ffc72b27f0a46c3379998369254cfd)
    6|Active     |     |dev.galasa.framework.maven.repository (0.18.0-93bcaf2103ffc72b27f0a46c3379998369254cfd)
    7|Active     |     |org.apache.felix.bundlerepository (2.0.2)
23/11/2021 12:17:01.424 TRACE dev.galasa.boot.felix.FelixFramework.loadBundleRepositories - Loading OBR OSGi Bundle Repository file:/Users/reecewilliams/TestEclipseWorkspace/.metadata/.plugins/dev.galasa.eclipse/workspace.obr
23/11/2021 12:17:01.433 TRACE dev.galasa.boot.felix.FelixFramework.loadBundleRepositories - Loaded repository null from URI file:/Users/reecewilliams/TestEclipseWorkspace/.metadata/.plugins/dev.galasa.eclipse/workspace.obr
23/11/2021 12:17:01.433 TRACE dev.galasa.boot.felix.FelixFramework.loadBundleRepositories -    dev.galasa.simbank.manager/0.0.1.SNAPSHOT
23/11/2021 12:17:01.433 TRACE dev.galasa.boot.felix.FelixFramework.loadBundleRepositories -       reference:file:/Users/reecewilliams/TestEclipseWorkspace/dev.galasa.simbank.manager/target/dev.galasa.simbank.manager-0.0.1-SNAPSHOT.jar
23/11/2021 12:17:01.433 TRACE dev.galasa.boot.felix.FelixFramework.loadBundleRepositories -       dev.galasa.simbank.manager
23/11/2021 12:17:01.433 TRACE dev.galasa.boot.felix.FelixFramework.loadBundleRepositories -       dev.galasa.simbank.manager
23/11/2021 12:17:01.434 TRACE dev.galasa.boot.felix.FelixFramework.loadBundleRepositories -       requirements:
23/11/2021 12:17:01.434 TRACE dev.galasa.boot.felix.FelixFramework.loadBundleRepositories -         (&(package=dev.galasa)(version>=0.15.0)(!(version>=1.0.0))) optional=false
23/11/2021 12:17:01.434 TRACE dev.galasa.boot.felix.FelixFramework.loadBundleRepositories -         (&(package=dev.galasa.artifact)(version>=0.15.0)(!(version>=1.0.0))) optional=false
23/11/2021 12:17:01.434 TRACE dev.galasa.boot.felix.FelixFramework.loadBundleRepositories -         (&(package=dev.galasa.docker)(version>=0.15.0)(!(version>=1.0.0))) optional=false
23/11/2021 12:17:01.435 TRACE dev.galasa.boot.felix.FelixFramework.loadBundleRepositories -         (&(package=dev.galasa.docker.spi)(version>=0.15.0)(!(version>=1.0.0))) optional=false
23/11/2021 12:17:01.435 TRACE dev.galasa.boot.felix.FelixFramework.loadBundleRepositories -         (&(package=dev.galasa.framework.spi)(version>=0.15.0)(!(version>=1.0.0))) optional=false
23/11/2021 12:17:01.435 TRACE dev.galasa.boot.felix.FelixFramework.loadBundleRepositories -         (&(package=dev.galasa.framework.spi.cps)(version>=0.15.0)(!(version>=1.0.0))) optional=false
23/11/2021 12:17:01.435 TRACE dev.galasa.boot.felix.FelixFramework.loadBundleRepositories -         (&(package=dev.galasa.framework.spi.creds)(version>=0.15.0)(!(version>=1.0.0))) optional=false
23/11/2021 12:17:01.435 TRACE dev.galasa.boot.felix.FelixFramework.loadBundleRepositories -         (&(package=dev.galasa.framework.spi.language)(version>=0.15.0)(!(version>=1.0.0))) optional=false
23/11/2021 12:17:01.435 TRACE dev.galasa.boot.felix.FelixFramework.loadBundleRepositories -         (&(package=dev.galasa.framework.spi.language.gherkin)(version>=0.15.0)(!(version>=1.0.0))) optional=false
23/11/2021 12:17:01.435 TRACE dev.galasa.boot.felix.FelixFramework.loadBundleRepositories -         (&(package=dev.galasa.http)(version>=0.15.0)(!(version>=1.0.0))) optional=false
23/11/2021 12:17:01.436 TRACE dev.galasa.boot.felix.FelixFramework.loadBundleRepositories -         (&(package=dev.galasa.http.spi)(version>=0.15.0)(!(version>=1.0.0))) optional=false
23/11/2021 12:17:01.436 TRACE dev.galasa.boot.felix.FelixFramework.loadBundleRepositories -         (&(package=dev.galasa.ipnetwork)(version>=0.15.0)(!(version>=1.0.0))) optional=false
23/11/2021 12:17:01.436 TRACE dev.galasa.boot.felix.FelixFramework.loadBundleRepositories -         (&(package=dev.galasa.simbank.manager.spi)(!(version>=1.0.0))) optional=false
23/11/2021 12:17:01.436 TRACE dev.galasa.boot.felix.FelixFramework.loadBundleRepositories -         (&(package=dev.galasa.zos)(version>=0.15.0)(!(version>=1.0.0))) optional=false
23/11/2021 12:17:01.436 TRACE dev.galasa.boot.felix.FelixFramework.loadBundleRepositories -         (&(package=dev.galasa.zos.spi)(version>=0.15.0)(!(version>=1.0.0))) optional=false
23/11/2021 12:17:01.436 TRACE dev.galasa.boot.felix.FelixFramework.loadBundleRepositories -         (&(package=dev.galasa.zos3270)(version>=0.15.0)(!(version>=1.0.0))) optional=false
23/11/2021 12:17:01.436 TRACE dev.galasa.boot.felix.FelixFramework.loadBundleRepositories -         (&(package=dev.galasa.zos3270.spi)(version>=0.15.0)(!(version>=1.0.0))) optional=false
23/11/2021 12:17:01.437 TRACE dev.galasa.boot.felix.FelixFramework.loadBundleRepositories -         (&(package=javax.validation.constraints)(version>=2.0.0)(!(version>=3.0.0))) optional=false
23/11/2021 12:17:01.437 TRACE dev.galasa.boot.felix.FelixFramework.loadBundleRepositories -         (&(package=org.apache.commons.logging)(version>=1.2.0)(!(version>=2.0.0))) optional=false
23/11/2021 12:17:01.437 TRACE dev.galasa.boot.felix.FelixFramework.loadBundleRepositories -         (&(package=org.apache.derby.jdbc)) optional=false
23/11/2021 12:17:01.437 TRACE dev.galasa.boot.felix.FelixFramework.loadBundleRepositories -    dev.galasa.simbank.tests/0.0.1.SNAPSHOT
23/11/2021 12:17:01.437 TRACE dev.galasa.boot.felix.FelixFramework.loadBundleRepositories -       reference:file:/Users/reecewilliams/TestEclipseWorkspace/dev.galasa.simbank.tests/target/dev.galasa.simbank.tests-0.0.1-SNAPSHOT.jar
23/11/2021 12:17:01.437 TRACE dev.galasa.boot.felix.FelixFramework.loadBundleRepositories -       dev.galasa.simbank.tests
23/11/2021 12:17:01.437 TRACE dev.galasa.boot.felix.FelixFramework.loadBundleRepositories -       dev.galasa.simbank.tests
23/11/2021 12:17:01.437 TRACE dev.galasa.boot.felix.FelixFramework.loadBundleRepositories -       requirements:
23/11/2021 12:17:01.438 TRACE dev.galasa.boot.felix.FelixFramework.loadBundleRepositories -         (&(package=dev.galasa)(version>=0.15.0)(!(version>=1.0.0))) optional=false
23/11/2021 12:17:01.438 TRACE dev.galasa.boot.felix.FelixFramework.loadBundleRepositories -         (&(package=dev.galasa.artifact)(version>=0.15.0)(!(version>=1.0.0))) optional=false
23/11/2021 12:17:01.438 TRACE dev.galasa.boot.felix.FelixFramework.loadBundleRepositories -         (&(package=dev.galasa.core.manager)(version>=0.15.0)(!(version>=1.0.0))) optional=false
23/11/2021 12:17:01.438 TRACE dev.galasa.boot.felix.FelixFramework.loadBundleRepositories -         (&(package=dev.galasa.http)(version>=0.15.0)(!(version>=1.0.0))) optional=false
23/11/2021 12:17:01.438 TRACE dev.galasa.boot.felix.FelixFramework.loadBundleRepositories -         (&(package=dev.galasa.selenium)(version>=0.15.0)(!(version>=1.0.0))) optional=false
23/11/2021 12:17:01.438 TRACE dev.galasa.boot.felix.FelixFramework.loadBundleRepositories -         (&(package=dev.galasa.simbank.manager)(!(version>=1.0.0))) optional=false
23/11/2021 12:17:01.438 TRACE dev.galasa.boot.felix.FelixFramework.loadBundleRepositories -         (&(package=dev.galasa.zos)(version>=0.15.0)(!(version>=1.0.0))) optional=false
23/11/2021 12:17:01.438 TRACE dev.galasa.boot.felix.FelixFramework.loadBundleRepositories -         (&(package=dev.galasa.zos3270)(version>=0.15.0)(!(version>=1.0.0))) optional=false
23/11/2021 12:17:01.439 TRACE dev.galasa.boot.felix.FelixFramework.loadBundleRepositories -         (&(package=dev.galasa.zos3270.spi)(version>=0.15.0)(!(version>=1.0.0))) optional=false
23/11/2021 12:17:01.439 TRACE dev.galasa.boot.felix.FelixFramework.loadBundleRepositories -         (&(package=dev.galasa.zosbatch)(version>=0.15.0)(!(version>=1.0.0))) optional=false
23/11/2021 12:17:01.439 TRACE dev.galasa.boot.felix.FelixFramework.loadBundleRepositories -         (&(package=org.apache.commons.logging)(version>=1.2.0)(!(version>=2.0.0))) optional=false
23/11/2021 12:17:01.439 TRACE dev.galasa.boot.felix.FelixFramework.loadBundleRepositories -         (&(package=org.assertj.core.api)(version>=3.11.0)(!(version>=4.0.0))) optional=false
23/11/2021 12:17:01.439 TRACE dev.galasa.boot.felix.FelixFramework.loadBundleRepositories -         (&(package=org.openqa.selenium)(version>=0.15.0)(!(version>=1.0.0))) optional=false
23/11/2021 12:17:01.439 TRACE dev.galasa.boot.felix.FelixFramework.loadBundleRepositories - Loading OBR OSGi Bundle Repository mvn:dev.galasa/dev.galasa.uber.obr/LATEST/obr
23/11/2021 12:17:01.439 ERROR dev.galasa.boot.Launcher.launch - Unable to run test class
dev.galasa.boot.LauncherException: Unable to create and initialize Felix framework
	at dev.galasa.boot.Launcher.buildFramework(Launcher.java:204)
	at dev.galasa.boot.Launcher.launch(Launcher.java:147)
	at dev.galasa.boot.Launcher.main(Launcher.java:117)
Caused by: dev.galasa.boot.LauncherException: Unable to load repository mvn:dev.galasa/dev.galasa.uber.obr/LATEST/obr
	at dev.galasa.boot.felix.FelixFramework.loadBundleRepositories(FelixFramework.java:770)
	at dev.galasa.boot.felix.FelixFramework.buildFramework(FelixFramework.java:109)
	at dev.galasa.boot.Launcher.buildFramework(Launcher.java:201)
	... 2 more
Caused by: java.net.MalformedURLException: unknown protocol: mvn
	at java.base/java.net.URL.<init>(URL.java:681)
	at java.base/java.net.URL.<init>(URL.java:569)
	at java.base/java.net.URL.<init>(URL.java:516)
	at org.apache.felix.bundlerepository.impl.RepositoryAdminImpl.addRepository(RepositoryAdminImpl.java:94)
	at dev.galasa.boot.felix.FelixFramework.loadBundleRepositories(FelixFramework.java:768)
	... 4 more
23/11/2021 12:17:01.440 DEBUG dev.galasa.boot.felix.FelixFramework.stopFramework - Stopping Felix framework
23/11/2021 12:17:01.454 DEBUG dev.galasa.boot.felix.FelixFramework.stopFramework - Felix framework stopped
23/11/2021 12:17:01.454 ERROR dev.galasa.boot.Launcher.main - Exiting launcher due to exception
dev.galasa.boot.LauncherException: Unable to create and initialize Felix framework
	at dev.galasa.boot.Launcher.buildFramework(Launcher.java:204)
	at dev.galasa.boot.Launcher.launch(Launcher.java:147)
	at dev.galasa.boot.Launcher.main(Launcher.java:117)
Caused by: dev.galasa.boot.LauncherException: Unable to load repository mvn:dev.galasa/dev.galasa.uber.obr/LATEST/obr
	at dev.galasa.boot.felix.FelixFramework.loadBundleRepositories(FelixFramework.java:770)
	at dev.galasa.boot.felix.FelixFramework.buildFramework(FelixFramework.java:109)
	at dev.galasa.boot.Launcher.buildFramework(Launcher.java:201)
	... 2 more
Caused by: java.net.MalformedURLException: unknown protocol: mvn
	at java.base/java.net.URL.<init>(URL.java:681)
	at java.base/java.net.URL.<init>(URL.java:569)
	at java.base/java.net.URL.<init>(URL.java:516)
	at org.apache.felix.bundlerepository.impl.RepositoryAdminImpl.addRepository(RepositoryAdminImpl.java:94)
	at dev.galasa.boot.felix.FelixFramework.loadBundleRepositories(FelixFramework.java:768)
	... 4 more

**Comment by hobbit1983** [comment]
So for clarity we think you are using the justJ 17 JDK that is shipped as part of eclipse.  We have not yet tested with 17 and have based our testing on the adopt open JDK 8, 11, 16 versions.  We are going to try an earlier release of Just J to see if the problem is isolated to 17.  If you could install another JDK to try that would be great and should allow you to keep using Galasa.  However we will keep this issue updated as we investigate more

**Comment by ReeceWilliams1105** [comment]
A quick update on the status of this issue, we have now tried to use other versions of the JustJ installation and the problem seems to be isolated to the Java 17 version. We have suspicions that this issue is being cause by the sun.misc package however we cannot be certain at this time. For now we advise using a Java 8 or 11 JDK.

**Comment by ApurvaS28** [comment]
I tried it with the older version ,its working now.Thanks

**Comment by ReeceWilliams1105** [comment]
Just a small update on the issue. I have discovered what is causing the issue within the Java 17 update with Galasa. I believe this [JEP 403](https://openjdk.java.net/jeps/403) describes the issue we have come across perfectly. I have not got a fix in hand for this at this time however we will invesitgate possible solutions going forwards.

**Comment by Rune-Christensen** [comment]
I would like to request that the docs be updated with this, as I have spent a lot of time trying to fix this in my eclipse installation.

**Comment by hobbit1983** [comment]
We will get this added. @CaroMac can you check the docs to see how clear this is and amend if possible?

**Comment by CaroMac** [comment]
@hobbit1983 . Yes, I will do this. Thank you.
