### ISSUE TITLE
provision generate failed

### ISSUE THREAD

**Issue by ApurvaS28** [galasa-dev/projectmanagement#921]
How can i fix this ?

29/11/2021 13:32:21.403 INFO  d.g.f.TestRunner - Provision Generate failed
dev.galasa.framework.spi.FrameworkException: Problem in provision generate for manager dev.galasa.zos.internal.ZosManagerImpl
	at dev.galasa.framework.TestRunManagers.provisionGenerate(TestRunManagers.java:480) ~[-1638172939342:?]
	at dev.galasa.framework.TestRunner.generateEnvironment(TestRunner.java:438) [-1638172939342:?]
	at dev.galasa.framework.TestRunner.runTest(TestRunner.java:371) [-1638172939342:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at dev.galasa.boot.felix.FelixFramework.runTest(FelixFramework.java:223) [galasa-boot.jar:?]
	at dev.galasa.boot.Launcher.launch(Launcher.java:163) [galasa-boot.jar:?]
	at dev.galasa.boot.Launcher.main(Launcher.java:117) [galasa-boot.jar:?]
Caused by: dev.galasa.zos.ZosManagerException: zOS Credentials missing for image LMNT id LMNT
	at dev.galasa.zos.internal.ZosBaseImageImpl.getDefaultCredentials(ZosBaseImageImpl.java:120) ~[?:?]
	at dev.galasa.zos.internal.properties.RunUNIXPathPrefix.get(RunUNIXPathPrefix.java:44) ~[?:?]
	at dev.galasa.zos.internal.ZosManagerImpl.getRunUNIXPathPrefix(ZosManagerImpl.java:551) ~[?:?]
	at dev.galasa.zos.internal.ZosBaseImageImpl.<init>(ZosBaseImageImpl.java:60) ~[?:?]
	at dev.galasa.zos.internal.ZosDseImageImpl.<init>(ZosDseImageImpl.java:13) ~[?:?]
	at dev.galasa.zos.internal.ZosManagerImpl.generateZosImage(ZosManagerImpl.java:293) ~[?:?]
	at dev.galasa.zos.internal.ZosManagerImpl.generateZosImage(ZosManagerImpl.java:269) ~[?:?]
	at dev.galasa.zos.internal.ZosManagerImpl.provisionGenerate(ZosManagerImpl.java:234) ~[?:?]
	at dev.galasa.framework.TestRunManagers.provisionGenerate(TestRunManagers.java:475) ~[-1638172939342:?]
	... 9 more
29/11/2021 13:32:21.880 INFO  d.g.f.Framework - Shutting down the framework
29/11/2021 13:32:21.880 INFO  d.g.f.Framework - Framework shutdown
29/11/2021 13:32:21.881 DEBUG dev.galasa.boot.felix.FelixFramework.stopFramework - Stopping Felix framework
29/11/2021 13:32:21.901 INFO  d.g.f.Framework - Framework service deactivated
29/11/2021 13:32:21.918 DEBUG dev.galasa.boot.felix.FelixFramework.stopFramework - Felix framework stopped
29/11/2021 13:32:21.918 INFO dev.galasa.boot.Launcher.launch - Boot complete

**Comment by hobbit1983** [comment]
Hi. In your test you are referencing some credentials by the token LMNT. However the galasa framework cannot find them in the credentials.properties file. Try updating that with the right creds and try again. If you need any further support do not hesitate to get back in contact

**Comment by hobbit1983** [comment]
@ApurvaS28 do you need any further assistance to fix this problem?

**Comment by ApurvaS28** [comment]
No i Do not require any further assistance .Thanks for guiding.

**Comment by hobbit1983** [comment]
Thanks - closing
