### ISSUE TITLE
Docker Manager Store file (+ others?) exceptions

### ISSUE THREAD

**Issue by rsomers1998** [galasa-dev/projectmanagement#98]
Exception thrown during storing a file incorrectly only returning a null pointer exception and nothing else. More descriptive exception messages would be useful to the tester

`05/02/2020 10:50:04.848 INFO dev.galasa.docker.internal.DockerExecImpl.<init> - Issuing command to docker container 'mkdir test_scripts'
05/02/2020 10:50:04.849 INFO dev.galasa.docker.internal.DockerExecImpl.<init> - Command started
05/02/2020 10:50:04.973 DEBUG dev.galasa.docker.internal.DockerExecImpl.run - Command completed with exitcode 0
05/02/2020 10:50:05.057 INFO dev.galasa.framework.GenericMethodWrapper.invoke - Ending
----------------------- ****************************************************************************************************
----------------------- *** Failed - Test method dev.galasa.inttests.DockerManagerTests#ManipulateFilesOnAContainer,type=Test
----------------------- ****************************************************************************************************
java.lang.NullPointerException
        at dev.galasa.docker.internal.DockerContainerImpl.storeFile(DockerContainerImpl.java:609)
        at dev.galasa.inttests.DockerManagerTests.ManipulateFilesOnAContainer(DockerManagerTests.java:149)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at dev.galasa.framework.GenericMethodWrapper.invoke(GenericMethodWrapper.java:80)
        at dev.galasa.framework.TestMethodWrapper.invoke(TestMethodWrapper.java:55)
        at dev.galasa.framework.TestClassWrapper.runTestMethods(TestClassWrapper.java:175)
        at dev.galasa.framework.TestRunner.runTest(TestRunner.java:342)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at dev.galasa.boot.felix.FelixFramework.runTest(FelixFramework.java:217)
        at dev.galasa.boot.Launcher.launch(Launcher.java:145)
        at dev.galasa.boot.Launcher.main(Launcher.java:102)`

**Comment by Michael-Baylis** [comment]
need the stack trace please

**Comment by rsomers1998** [comment]
Stack trace added, method worksncorrectly if you use it right, just learning to use it can be confusing with non descriptive exception messages

**Comment by Michael-Baylis** [comment]
@Jimbo4794  Need this sorting asap.  Should never have a NPE

**Comment by Jimbo4794** [comment]
Wokring on it. @rsomers1998, what did you pass to the storeFile() to result in a NPE

**Comment by rsomers1998** [comment]
`.storeFile("", is);`

**Comment by Jimbo4794** [comment]
fixes contained in PR 76
